"use client"

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Loader2, FileText, Download, Eye, Calendar, FileBarChart, BookOpen, Sparkles, FolderOpen } from "lucide-react"
import { useState } from "react"
import { getDriveDownloadUrl, isGoogleDriveUrl } from "@/lib/google-sheets"

interface Report {
  id: string
  name: string
  date: string
  type: string
  driveFileUrl?: string
  size?: string
  description?: string
  period?: string
  generatedBy?: string
  [key: string]: string | number | null | undefined
}

interface ReportsSectionProps {
  reports: Report[]
  isLoading: boolean
}

export function ReportsSection({ reports, isLoading }: ReportsSectionProps) {
  const [downloadingId, setDownloadingId] = useState<string | null>(null)
  const [viewingId, setViewingId] = useState<string | null>(null)

  const getTypeConfig = (type: string) => {
    switch (type?.toLowerCase()) {
      case "monthly":
        return { icon: Calendar, color: "bg-primary/10 text-primary", gradient: "from-primary/10 to-primary/5" }
      case "quarterly":
        return {
          icon: FileBarChart,
          color: "bg-secondary/10 text-secondary",
          gradient: "from-secondary/10 to-secondary/5",
        }
      case "annual":
        return { icon: BookOpen, color: "bg-accent/10 text-accent", gradient: "from-accent/10 to-accent/5" }
      default:
        return { icon: FileText, color: "bg-muted text-muted-foreground", gradient: "from-muted/50 to-muted/20" }
    }
  }

  const handleDownload = async (report: Report) => {
    setDownloadingId(report.id)

    // Check if there's a Google Drive URL
    if (report.driveFileUrl && isGoogleDriveUrl(report.driveFileUrl)) {
      const downloadUrl = getDriveDownloadUrl(report.driveFileUrl)
      window.open(downloadUrl, "_blank")
      setDownloadingId(null)
      return
    }

    // Fallback: Generate demo report content
    await new Promise((resolve) => setTimeout(resolve, 1200))

    const content = `
================================================================================
                        BUFFINDIA SUSTAINABILITY REPORT
================================================================================

Report: ${report.name}
Type: ${report.type}
Date: ${report.date}
Period: ${report.period || "N/A"}
Size: ${report.size || "N/A"}
Generated By: ${report.generatedBy || "System"}

--------------------------------------------------------------------------------
                              EXECUTIVE SUMMARY
--------------------------------------------------------------------------------

${report.description || "This report summarizes your organization's environmental impact through partnership with Buffindia's cigarette waste recycling program."}

KEY HIGHLIGHTS:
- Total waste collected and recycled
- Carbon footprint reduction metrics
- Environmental equivalents (trees saved, CO2 prevented)
- ESG compliance status
- Future sustainability targets

--------------------------------------------------------------------------------
                           IMPACT METRICS
--------------------------------------------------------------------------------

Your contribution helps:
✓ Reduce landfill waste
✓ Prevent ocean pollution
✓ Create sustainable materials
✓ Support circular economy initiatives

--------------------------------------------------------------------------------

Thank you for being part of the solution.

Buffindia - Transforming Waste into Value
www.buffindia.com

================================================================================
    `.trim()

    const blob = new Blob([content], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `${report.name.replace(/\s+/g, "-")}-report.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)

    setDownloadingId(null)
  }

  const handleView = async (report: Report) => {
    setViewingId(report.id)

    if (report.driveFileUrl && isGoogleDriveUrl(report.driveFileUrl)) {
      window.open(report.driveFileUrl, "_blank")
      setViewingId(null)
      return
    }

    await handleDownload(report)
    setViewingId(null)
  }

  const handleDownloadAll = async () => {
    for (const report of reports) {
      await handleDownload(report)
      await new Promise((resolve) => setTimeout(resolve, 500))
    }
  }

  return (
    <Card className="glass border-border/50">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="text-lg font-semibold flex items-center gap-2">
              <FileText className="w-5 h-5 text-primary" />
              Reports & Documents
            </CardTitle>
            <CardDescription>Download your sustainability and impact reports</CardDescription>
          </div>
          <Button variant="outline" className="bg-transparent hover:bg-primary/10" onClick={handleDownloadAll}>
            <FolderOpen className="w-4 h-4 mr-2" />
            Download All
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        {isLoading ? (
          <div className="flex items-center justify-center py-8">
            <Loader2 className="w-6 h-6 animate-spin text-primary" />
          </div>
        ) : (
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {reports.map((report, index) => {
              const config = getTypeConfig(report.type?.toString() || "")
              const TypeIcon = config.icon
              const isDownloading = downloadingId === report.id
              const isViewing = viewingId === report.id
              const hasGoogleDrive = report.driveFileUrl && isGoogleDriveUrl(report.driveFileUrl)

              return (
                <div
                  key={report.id || index}
                  className={`p-4 rounded-xl bg-gradient-to-br ${config.gradient} border border-border/50 hover:shadow-lg hover:scale-[1.02] transition-all duration-300 group`}
                >
                  <div className="flex items-start gap-3 mb-3">
                    <div
                      className={`w-11 h-11 rounded-xl ${config.color} flex items-center justify-center shrink-0 shadow-sm group-hover:scale-110 transition-transform`}
                    >
                      <TypeIcon className="w-5 h-5" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <h4 className="font-medium text-foreground text-sm leading-tight mb-1 line-clamp-2">
                        {report.name || "Report"}
                      </h4>
                      <div className="flex items-center gap-2 flex-wrap">
                        <Badge variant="outline" className="text-[10px] px-1.5 py-0 bg-background/50">
                          {report.type || "Report"}
                        </Badge>
                        {report.size && <span className="text-[10px] text-muted-foreground">{report.size}</span>}
                      </div>
                    </div>
                  </div>

                  {report.description && (
                    <p className="text-xs text-muted-foreground mb-2 line-clamp-2">{report.description}</p>
                  )}

                  <div className="flex items-center gap-1 text-xs text-muted-foreground mb-3">
                    <Calendar className="w-3 h-3" />
                    <span>{report.date || "N/A"}</span>
                    {report.period && (
                      <>
                        <span className="mx-1">|</span>
                        <span>{report.period}</span>
                      </>
                    )}
                  </div>

                  <div className="flex gap-2">
                    <Button
                      size="sm"
                      variant="outline"
                      className="flex-1 h-9 text-xs bg-background/50 hover:bg-background group-hover:border-primary/30"
                      onClick={() => handleDownload(report)}
                      disabled={isDownloading}
                    >
                      {isDownloading ? (
                        <>
                          <Loader2 className="w-3 h-3 mr-1 animate-spin" />
                          Downloading...
                        </>
                      ) : (
                        <>
                          <Download className="w-3 h-3 mr-1" />
                          {hasGoogleDrive ? "Download PDF" : "Download"}
                        </>
                      )}
                    </Button>
                    <Button
                      size="sm"
                      variant="ghost"
                      className="h-9 px-3 hover:bg-primary/10"
                      onClick={() => handleView(report)}
                      disabled={isViewing}
                    >
                      {isViewing ? <Loader2 className="w-3 h-3 animate-spin" /> : <Eye className="w-3 h-3" />}
                    </Button>
                  </div>
                </div>
              )
            })}
          </div>
        )}

        {/* Quick Stats */}
        <div className="mt-6 p-4 rounded-xl bg-gradient-to-r from-primary/5 via-secondary/5 to-accent/5 border border-border/30">
          <div className="flex items-center gap-2 mb-3">
            <Sparkles className="w-4 h-4 text-primary" />
            <span className="text-sm font-medium text-foreground">Report Summary</span>
          </div>
          <div className="grid grid-cols-3 gap-4 text-center">
            <div>
              <p className="text-2xl font-bold text-primary">
                {reports.filter((r) => r.type?.toLowerCase() === "monthly").length}
              </p>
              <p className="text-xs text-muted-foreground">Monthly Reports</p>
            </div>
            <div>
              <p className="text-2xl font-bold text-secondary">
                {reports.filter((r) => r.type?.toLowerCase() === "quarterly").length}
              </p>
              <p className="text-xs text-muted-foreground">Quarterly Reports</p>
            </div>
            <div>
              <p className="text-2xl font-bold text-accent">
                {reports.filter((r) => r.type?.toLowerCase() === "annual").length}
              </p>
              <p className="text-xs text-muted-foreground">Annual Reports</p>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
