
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Customer: 'Customer',
  Notification: 'Notification',
  Collection: 'Collection',
  Certificate: 'Certificate',
  Report: 'Report',
  GlobalImpact: 'GlobalImpact',
  Product: 'Product',
  ShopOrder: 'ShopOrder',
  OrderItem: 'OrderItem',
  PasswordResetOtp: 'PasswordResetOtp',
  AdminCredential: 'AdminCredential',
  VerifiedCertificate: 'VerifiedCertificate',
  SupportTicket: 'SupportTicket'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const CustomerScalarFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  companyName: 'companyName',
  contactPerson: 'contactPerson',
  phone: 'phone',
  address: 'address',
  industry: 'industry',
  employeeCount: 'employeeCount',
  joinDate: 'joinDate',
  status: 'status',
  disposalUnitInstalled: 'disposalUnitInstalled',
  isGroup: 'isGroup',
  parentCustomerId: 'parentCustomerId',
  totalWasteCollected: 'totalWasteCollected',
  cigaretteButtsCollected: 'cigaretteButtsCollected',
  microplasticsUpcycled: 'microplasticsUpcycled',
  waterResourcesProtected: 'waterResourcesProtected',
  pendingCollection: 'pendingCollection',
  certificatesEarned: 'certificatesEarned',
  co2Saved: 'co2Saved',
  kraftrebornCredits: 'kraftrebornCredits',
  treesEquivalent: 'treesEquivalent',
  monthlyTarget: 'monthlyTarget',
  profileImageUrl: 'profileImageUrl',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CustomerScalarFieldEnum = (typeof CustomerScalarFieldEnum)[keyof typeof CustomerScalarFieldEnum]


export const NotificationScalarFieldEnum = {
  id: 'id',
  customerId: 'customerId',
  title: 'title',
  body: 'body',
  linkUrl: 'linkUrl',
  readAt: 'readAt',
  createdAt: 'createdAt'
} as const

export type NotificationScalarFieldEnum = (typeof NotificationScalarFieldEnum)[keyof typeof NotificationScalarFieldEnum]


export const CollectionScalarFieldEnum = {
  id: 'id',
  customerId: 'customerId',
  date: 'date',
  weight: 'weight',
  location: 'location',
  status: 'status',
  co2Saved: 'co2Saved',
  collectorName: 'collectorName',
  vehicleNumber: 'vehicleNumber',
  notes: 'notes'
} as const

export type CollectionScalarFieldEnum = (typeof CollectionScalarFieldEnum)[keyof typeof CollectionScalarFieldEnum]


export const CertificateScalarFieldEnum = {
  id: 'id',
  customerId: 'customerId',
  name: 'name',
  issueDate: 'issueDate',
  type: 'type',
  description: 'description',
  driveFileUrl: 'driveFileUrl',
  validUntil: 'validUntil',
  issuedBy: 'issuedBy',
  certificateNumber: 'certificateNumber'
} as const

export type CertificateScalarFieldEnum = (typeof CertificateScalarFieldEnum)[keyof typeof CertificateScalarFieldEnum]


export const ReportScalarFieldEnum = {
  id: 'id',
  customerId: 'customerId',
  name: 'name',
  date: 'date',
  type: 'type',
  driveFileUrl: 'driveFileUrl',
  size: 'size',
  description: 'description',
  period: 'period',
  generatedBy: 'generatedBy'
} as const

export type ReportScalarFieldEnum = (typeof ReportScalarFieldEnum)[keyof typeof ReportScalarFieldEnum]


export const GlobalImpactScalarFieldEnum = {
  id: 'id',
  wasteCollected: 'wasteCollected',
  productsCreated: 'productsCreated',
  treesEquivalent: 'treesEquivalent',
  co2Prevented: 'co2Prevented',
  updatedAt: 'updatedAt'
} as const

export type GlobalImpactScalarFieldEnum = (typeof GlobalImpactScalarFieldEnum)[keyof typeof GlobalImpactScalarFieldEnum]


export const ProductScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  price: 'price',
  category: 'category',
  tagline: 'tagline',
  buttsRescued: 'buttsRescued',
  imageUrl: 'imageUrl',
  imageGradient: 'imageGradient',
  allowsLogo: 'allowsLogo',
  active: 'active',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProductScalarFieldEnum = (typeof ProductScalarFieldEnum)[keyof typeof ProductScalarFieldEnum]


export const ShopOrderScalarFieldEnum = {
  id: 'id',
  orderNumber: 'orderNumber',
  customerId: 'customerId',
  status: 'status',
  subtotal: 'subtotal',
  useKrCredits: 'useKrCredits',
  creditsDeducted: 'creditsDeducted',
  logoRequested: 'logoRequested',
  logoUrl: 'logoUrl',
  shippingName: 'shippingName',
  shippingEmail: 'shippingEmail',
  shippingPhone: 'shippingPhone',
  shippingAddress: 'shippingAddress',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  completedAt: 'completedAt'
} as const

export type ShopOrderScalarFieldEnum = (typeof ShopOrderScalarFieldEnum)[keyof typeof ShopOrderScalarFieldEnum]


export const OrderItemScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  productId: 'productId',
  productName: 'productName',
  price: 'price',
  quantity: 'quantity',
  allowsLogo: 'allowsLogo'
} as const

export type OrderItemScalarFieldEnum = (typeof OrderItemScalarFieldEnum)[keyof typeof OrderItemScalarFieldEnum]


export const PasswordResetOtpScalarFieldEnum = {
  id: 'id',
  email: 'email',
  purpose: 'purpose',
  otpHash: 'otpHash',
  resetToken: 'resetToken',
  expiresAt: 'expiresAt',
  verifiedAt: 'verifiedAt',
  usedAt: 'usedAt',
  attempts: 'attempts',
  createdAt: 'createdAt'
} as const

export type PasswordResetOtpScalarFieldEnum = (typeof PasswordResetOtpScalarFieldEnum)[keyof typeof PasswordResetOtpScalarFieldEnum]


export const AdminCredentialScalarFieldEnum = {
  id: 'id',
  email: 'email',
  passwordHash: 'passwordHash',
  updatedAt: 'updatedAt'
} as const

export type AdminCredentialScalarFieldEnum = (typeof AdminCredentialScalarFieldEnum)[keyof typeof AdminCredentialScalarFieldEnum]


export const VerifiedCertificateScalarFieldEnum = {
  id: 'id',
  title: 'title',
  issuer: 'issuer',
  validUntil: 'validUntil',
  type: 'type',
  icon: 'icon',
  pdfUrl: 'pdfUrl',
  sortOrder: 'sortOrder',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type VerifiedCertificateScalarFieldEnum = (typeof VerifiedCertificateScalarFieldEnum)[keyof typeof VerifiedCertificateScalarFieldEnum]


export const SupportTicketScalarFieldEnum = {
  id: 'id',
  customerId: 'customerId',
  name: 'name',
  email: 'email',
  subject: 'subject',
  message: 'message',
  category: 'category',
  status: 'status',
  source: 'source',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SupportTicketScalarFieldEnum = (typeof SupportTicketScalarFieldEnum)[keyof typeof SupportTicketScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

