
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Customer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Customer
 * 
 */
export type CustomerModel = runtime.Types.Result.DefaultSelection<Prisma.$CustomerPayload>

export type AggregateCustomer = {
  _count: CustomerCountAggregateOutputType | null
  _avg: CustomerAvgAggregateOutputType | null
  _sum: CustomerSumAggregateOutputType | null
  _min: CustomerMinAggregateOutputType | null
  _max: CustomerMaxAggregateOutputType | null
}

export type CustomerAvgAggregateOutputType = {
  employeeCount: number | null
  totalWasteCollected: number | null
  pendingCollection: number | null
  certificatesEarned: number | null
  co2Saved: number | null
  treesEquivalent: number | null
  monthlyTarget: number | null
}

export type CustomerSumAggregateOutputType = {
  employeeCount: number | null
  totalWasteCollected: number | null
  pendingCollection: number | null
  certificatesEarned: number | null
  co2Saved: number | null
  treesEquivalent: number | null
  monthlyTarget: number | null
}

export type CustomerMinAggregateOutputType = {
  id: string | null
  email: string | null
  password: string | null
  companyName: string | null
  contactPerson: string | null
  phone: string | null
  address: string | null
  industry: string | null
  employeeCount: number | null
  joinDate: Date | null
  status: string | null
  totalWasteCollected: number | null
  pendingCollection: number | null
  certificatesEarned: number | null
  co2Saved: number | null
  treesEquivalent: number | null
  monthlyTarget: number | null
  profileImageUrl: string | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CustomerMaxAggregateOutputType = {
  id: string | null
  email: string | null
  password: string | null
  companyName: string | null
  contactPerson: string | null
  phone: string | null
  address: string | null
  industry: string | null
  employeeCount: number | null
  joinDate: Date | null
  status: string | null
  totalWasteCollected: number | null
  pendingCollection: number | null
  certificatesEarned: number | null
  co2Saved: number | null
  treesEquivalent: number | null
  monthlyTarget: number | null
  profileImageUrl: string | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CustomerCountAggregateOutputType = {
  id: number
  email: number
  password: number
  companyName: number
  contactPerson: number
  phone: number
  address: number
  industry: number
  employeeCount: number
  joinDate: number
  status: number
  totalWasteCollected: number
  pendingCollection: number
  certificatesEarned: number
  co2Saved: number
  treesEquivalent: number
  monthlyTarget: number
  profileImageUrl: number
  notes: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CustomerAvgAggregateInputType = {
  employeeCount?: true
  totalWasteCollected?: true
  pendingCollection?: true
  certificatesEarned?: true
  co2Saved?: true
  treesEquivalent?: true
  monthlyTarget?: true
}

export type CustomerSumAggregateInputType = {
  employeeCount?: true
  totalWasteCollected?: true
  pendingCollection?: true
  certificatesEarned?: true
  co2Saved?: true
  treesEquivalent?: true
  monthlyTarget?: true
}

export type CustomerMinAggregateInputType = {
  id?: true
  email?: true
  password?: true
  companyName?: true
  contactPerson?: true
  phone?: true
  address?: true
  industry?: true
  employeeCount?: true
  joinDate?: true
  status?: true
  totalWasteCollected?: true
  pendingCollection?: true
  certificatesEarned?: true
  co2Saved?: true
  treesEquivalent?: true
  monthlyTarget?: true
  profileImageUrl?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
}

export type CustomerMaxAggregateInputType = {
  id?: true
  email?: true
  password?: true
  companyName?: true
  contactPerson?: true
  phone?: true
  address?: true
  industry?: true
  employeeCount?: true
  joinDate?: true
  status?: true
  totalWasteCollected?: true
  pendingCollection?: true
  certificatesEarned?: true
  co2Saved?: true
  treesEquivalent?: true
  monthlyTarget?: true
  profileImageUrl?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
}

export type CustomerCountAggregateInputType = {
  id?: true
  email?: true
  password?: true
  companyName?: true
  contactPerson?: true
  phone?: true
  address?: true
  industry?: true
  employeeCount?: true
  joinDate?: true
  status?: true
  totalWasteCollected?: true
  pendingCollection?: true
  certificatesEarned?: true
  co2Saved?: true
  treesEquivalent?: true
  monthlyTarget?: true
  profileImageUrl?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CustomerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Customer to aggregate.
   */
  where?: Prisma.CustomerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Customers to fetch.
   */
  orderBy?: Prisma.CustomerOrderByWithRelationInput | Prisma.CustomerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CustomerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Customers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Customers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Customers
  **/
  _count?: true | CustomerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CustomerAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CustomerSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CustomerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CustomerMaxAggregateInputType
}

export type GetCustomerAggregateType<T extends CustomerAggregateArgs> = {
      [P in keyof T & keyof AggregateCustomer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCustomer[P]>
    : Prisma.GetScalarType<T[P], AggregateCustomer[P]>
}




export type CustomerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CustomerWhereInput
  orderBy?: Prisma.CustomerOrderByWithAggregationInput | Prisma.CustomerOrderByWithAggregationInput[]
  by: Prisma.CustomerScalarFieldEnum[] | Prisma.CustomerScalarFieldEnum
  having?: Prisma.CustomerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CustomerCountAggregateInputType | true
  _avg?: CustomerAvgAggregateInputType
  _sum?: CustomerSumAggregateInputType
  _min?: CustomerMinAggregateInputType
  _max?: CustomerMaxAggregateInputType
}

export type CustomerGroupByOutputType = {
  id: string
  email: string
  password: string
  companyName: string
  contactPerson: string | null
  phone: string | null
  address: string | null
  industry: string | null
  employeeCount: number | null
  joinDate: Date
  status: string
  totalWasteCollected: number
  pendingCollection: number
  certificatesEarned: number
  co2Saved: number
  treesEquivalent: number
  monthlyTarget: number
  profileImageUrl: string | null
  notes: string | null
  createdAt: Date
  updatedAt: Date
  _count: CustomerCountAggregateOutputType | null
  _avg: CustomerAvgAggregateOutputType | null
  _sum: CustomerSumAggregateOutputType | null
  _min: CustomerMinAggregateOutputType | null
  _max: CustomerMaxAggregateOutputType | null
}

type GetCustomerGroupByPayload<T extends CustomerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CustomerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CustomerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CustomerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CustomerGroupByOutputType[P]>
      }
    >
  >



export type CustomerWhereInput = {
  AND?: Prisma.CustomerWhereInput | Prisma.CustomerWhereInput[]
  OR?: Prisma.CustomerWhereInput[]
  NOT?: Prisma.CustomerWhereInput | Prisma.CustomerWhereInput[]
  id?: Prisma.StringFilter<"Customer"> | string
  email?: Prisma.StringFilter<"Customer"> | string
  password?: Prisma.StringFilter<"Customer"> | string
  companyName?: Prisma.StringFilter<"Customer"> | string
  contactPerson?: Prisma.StringNullableFilter<"Customer"> | string | null
  phone?: Prisma.StringNullableFilter<"Customer"> | string | null
  address?: Prisma.StringNullableFilter<"Customer"> | string | null
  industry?: Prisma.StringNullableFilter<"Customer"> | string | null
  employeeCount?: Prisma.IntNullableFilter<"Customer"> | number | null
  joinDate?: Prisma.DateTimeFilter<"Customer"> | Date | string
  status?: Prisma.StringFilter<"Customer"> | string
  totalWasteCollected?: Prisma.FloatFilter<"Customer"> | number
  pendingCollection?: Prisma.FloatFilter<"Customer"> | number
  certificatesEarned?: Prisma.IntFilter<"Customer"> | number
  co2Saved?: Prisma.FloatFilter<"Customer"> | number
  treesEquivalent?: Prisma.IntFilter<"Customer"> | number
  monthlyTarget?: Prisma.FloatFilter<"Customer"> | number
  profileImageUrl?: Prisma.StringNullableFilter<"Customer"> | string | null
  notes?: Prisma.StringNullableFilter<"Customer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Customer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Customer"> | Date | string
  collections?: Prisma.CollectionListRelationFilter
  certificates?: Prisma.CertificateListRelationFilter
  reports?: Prisma.ReportListRelationFilter
  passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter
}

export type CustomerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  companyName?: Prisma.SortOrder
  contactPerson?: Prisma.SortOrderInput | Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  industry?: Prisma.SortOrderInput | Prisma.SortOrder
  employeeCount?: Prisma.SortOrderInput | Prisma.SortOrder
  joinDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalWasteCollected?: Prisma.SortOrder
  pendingCollection?: Prisma.SortOrder
  certificatesEarned?: Prisma.SortOrder
  co2Saved?: Prisma.SortOrder
  treesEquivalent?: Prisma.SortOrder
  monthlyTarget?: Prisma.SortOrder
  profileImageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  collections?: Prisma.CollectionOrderByRelationAggregateInput
  certificates?: Prisma.CertificateOrderByRelationAggregateInput
  reports?: Prisma.ReportOrderByRelationAggregateInput
  passwordResetTokens?: Prisma.PasswordResetTokenOrderByRelationAggregateInput
}

export type CustomerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  AND?: Prisma.CustomerWhereInput | Prisma.CustomerWhereInput[]
  OR?: Prisma.CustomerWhereInput[]
  NOT?: Prisma.CustomerWhereInput | Prisma.CustomerWhereInput[]
  password?: Prisma.StringFilter<"Customer"> | string
  companyName?: Prisma.StringFilter<"Customer"> | string
  contactPerson?: Prisma.StringNullableFilter<"Customer"> | string | null
  phone?: Prisma.StringNullableFilter<"Customer"> | string | null
  address?: Prisma.StringNullableFilter<"Customer"> | string | null
  industry?: Prisma.StringNullableFilter<"Customer"> | string | null
  employeeCount?: Prisma.IntNullableFilter<"Customer"> | number | null
  joinDate?: Prisma.DateTimeFilter<"Customer"> | Date | string
  status?: Prisma.StringFilter<"Customer"> | string
  totalWasteCollected?: Prisma.FloatFilter<"Customer"> | number
  pendingCollection?: Prisma.FloatFilter<"Customer"> | number
  certificatesEarned?: Prisma.IntFilter<"Customer"> | number
  co2Saved?: Prisma.FloatFilter<"Customer"> | number
  treesEquivalent?: Prisma.IntFilter<"Customer"> | number
  monthlyTarget?: Prisma.FloatFilter<"Customer"> | number
  profileImageUrl?: Prisma.StringNullableFilter<"Customer"> | string | null
  notes?: Prisma.StringNullableFilter<"Customer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Customer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Customer"> | Date | string
  collections?: Prisma.CollectionListRelationFilter
  certificates?: Prisma.CertificateListRelationFilter
  reports?: Prisma.ReportListRelationFilter
  passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter
}, "id" | "email">

export type CustomerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  companyName?: Prisma.SortOrder
  contactPerson?: Prisma.SortOrderInput | Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  industry?: Prisma.SortOrderInput | Prisma.SortOrder
  employeeCount?: Prisma.SortOrderInput | Prisma.SortOrder
  joinDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalWasteCollected?: Prisma.SortOrder
  pendingCollection?: Prisma.SortOrder
  certificatesEarned?: Prisma.SortOrder
  co2Saved?: Prisma.SortOrder
  treesEquivalent?: Prisma.SortOrder
  monthlyTarget?: Prisma.SortOrder
  profileImageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CustomerCountOrderByAggregateInput
  _avg?: Prisma.CustomerAvgOrderByAggregateInput
  _max?: Prisma.CustomerMaxOrderByAggregateInput
  _min?: Prisma.CustomerMinOrderByAggregateInput
  _sum?: Prisma.CustomerSumOrderByAggregateInput
}

export type CustomerScalarWhereWithAggregatesInput = {
  AND?: Prisma.CustomerScalarWhereWithAggregatesInput | Prisma.CustomerScalarWhereWithAggregatesInput[]
  OR?: Prisma.CustomerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CustomerScalarWhereWithAggregatesInput | Prisma.CustomerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Customer"> | string
  email?: Prisma.StringWithAggregatesFilter<"Customer"> | string
  password?: Prisma.StringWithAggregatesFilter<"Customer"> | string
  companyName?: Prisma.StringWithAggregatesFilter<"Customer"> | string
  contactPerson?: Prisma.StringNullableWithAggregatesFilter<"Customer"> | string | null
  phone?: Prisma.StringNullableWithAggregatesFilter<"Customer"> | string | null
  address?: Prisma.StringNullableWithAggregatesFilter<"Customer"> | string | null
  industry?: Prisma.StringNullableWithAggregatesFilter<"Customer"> | string | null
  employeeCount?: Prisma.IntNullableWithAggregatesFilter<"Customer"> | number | null
  joinDate?: Prisma.DateTimeWithAggregatesFilter<"Customer"> | Date | string
  status?: Prisma.StringWithAggregatesFilter<"Customer"> | string
  totalWasteCollected?: Prisma.FloatWithAggregatesFilter<"Customer"> | number
  pendingCollection?: Prisma.FloatWithAggregatesFilter<"Customer"> | number
  certificatesEarned?: Prisma.IntWithAggregatesFilter<"Customer"> | number
  co2Saved?: Prisma.FloatWithAggregatesFilter<"Customer"> | number
  treesEquivalent?: Prisma.IntWithAggregatesFilter<"Customer"> | number
  monthlyTarget?: Prisma.FloatWithAggregatesFilter<"Customer"> | number
  profileImageUrl?: Prisma.StringNullableWithAggregatesFilter<"Customer"> | string | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"Customer"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Customer"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Customer"> | Date | string
}

export type CustomerCreateInput = {
  id?: string
  email: string
  password: string
  companyName: string
  contactPerson?: string | null
  phone?: string | null
  address?: string | null
  industry?: string | null
  employeeCount?: number | null
  joinDate?: Date | string
  status?: string
  totalWasteCollected?: number
  pendingCollection?: number
  certificatesEarned?: number
  co2Saved?: number
  treesEquivalent?: number
  monthlyTarget?: number
  profileImageUrl?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  collections?: Prisma.CollectionCreateNestedManyWithoutCustomerInput
  certificates?: Prisma.CertificateCreateNestedManyWithoutCustomerInput
  reports?: Prisma.ReportCreateNestedManyWithoutCustomerInput
  passwordResetTokens?: Prisma.PasswordResetTokenCreateNestedManyWithoutCustomerInput
}

export type CustomerUncheckedCreateInput = {
  id?: string
  email: string
  password: string
  companyName: string
  contactPerson?: string | null
  phone?: string | null
  address?: string | null
  industry?: string | null
  employeeCount?: number | null
  joinDate?: Date | string
  status?: string
  totalWasteCollected?: number
  pendingCollection?: number
  certificatesEarned?: number
  co2Saved?: number
  treesEquivalent?: number
  monthlyTarget?: number
  profileImageUrl?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  collections?: Prisma.CollectionUncheckedCreateNestedManyWithoutCustomerInput
  certificates?: Prisma.CertificateUncheckedCreateNestedManyWithoutCustomerInput
  reports?: Prisma.ReportUncheckedCreateNestedManyWithoutCustomerInput
  passwordResetTokens?: Prisma.PasswordResetTokenUncheckedCreateNestedManyWithoutCustomerInput
}

export type CustomerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  companyName?: Prisma.StringFieldUpdateOperationsInput | string
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  industry?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  employeeCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  joinDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalWasteCollected?: Prisma.FloatFieldUpdateOperationsInput | number
  pendingCollection?: Prisma.FloatFieldUpdateOperationsInput | number
  certificatesEarned?: Prisma.IntFieldUpdateOperationsInput | number
  co2Saved?: Prisma.FloatFieldUpdateOperationsInput | number
  treesEquivalent?: Prisma.IntFieldUpdateOperationsInput | number
  monthlyTarget?: Prisma.FloatFieldUpdateOperationsInput | number
  profileImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  collections?: Prisma.CollectionUpdateManyWithoutCustomerNestedInput
  certificates?: Prisma.CertificateUpdateManyWithoutCustomerNestedInput
  reports?: Prisma.ReportUpdateManyWithoutCustomerNestedInput
  passwordResetTokens?: Prisma.PasswordResetTokenUpdateManyWithoutCustomerNestedInput
}

export type CustomerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  companyName?: Prisma.StringFieldUpdateOperationsInput | string
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  industry?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  employeeCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  joinDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalWasteCollected?: Prisma.FloatFieldUpdateOperationsInput | number
  pendingCollection?: Prisma.FloatFieldUpdateOperationsInput | number
  certificatesEarned?: Prisma.IntFieldUpdateOperationsInput | number
  co2Saved?: Prisma.FloatFieldUpdateOperationsInput | number
  treesEquivalent?: Prisma.IntFieldUpdateOperationsInput | number
  monthlyTarget?: Prisma.FloatFieldUpdateOperationsInput | number
  profileImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  collections?: Prisma.CollectionUncheckedUpdateManyWithoutCustomerNestedInput
  certificates?: Prisma.CertificateUncheckedUpdateManyWithoutCustomerNestedInput
  reports?: Prisma.ReportUncheckedUpdateManyWithoutCustomerNestedInput
  passwordResetTokens?: Prisma.PasswordResetTokenUncheckedUpdateManyWithoutCustomerNestedInput
}

export type CustomerCreateManyInput = {
  id?: string
  email: string
  password: string
  companyName: string
  contactPerson?: string | null
  phone?: string | null
  address?: string | null
  industry?: string | null
  employeeCount?: number | null
  joinDate?: Date | string
  status?: string
  totalWasteCollected?: number
  pendingCollection?: number
  certificatesEarned?: number
  co2Saved?: number
  treesEquivalent?: number
  monthlyTarget?: number
  profileImageUrl?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CustomerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  companyName?: Prisma.StringFieldUpdateOperationsInput | string
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  industry?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  employeeCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  joinDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalWasteCollected?: Prisma.FloatFieldUpdateOperationsInput | number
  pendingCollection?: Prisma.FloatFieldUpdateOperationsInput | number
  certificatesEarned?: Prisma.IntFieldUpdateOperationsInput | number
  co2Saved?: Prisma.FloatFieldUpdateOperationsInput | number
  treesEquivalent?: Prisma.IntFieldUpdateOperationsInput | number
  monthlyTarget?: Prisma.FloatFieldUpdateOperationsInput | number
  profileImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  companyName?: Prisma.StringFieldUpdateOperationsInput | string
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  industry?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  employeeCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  joinDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalWasteCollected?: Prisma.FloatFieldUpdateOperationsInput | number
  pendingCollection?: Prisma.FloatFieldUpdateOperationsInput | number
  certificatesEarned?: Prisma.IntFieldUpdateOperationsInput | number
  co2Saved?: Prisma.FloatFieldUpdateOperationsInput | number
  treesEquivalent?: Prisma.IntFieldUpdateOperationsInput | number
  monthlyTarget?: Prisma.FloatFieldUpdateOperationsInput | number
  profileImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  companyName?: Prisma.SortOrder
  contactPerson?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  address?: Prisma.SortOrder
  industry?: Prisma.SortOrder
  employeeCount?: Prisma.SortOrder
  joinDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalWasteCollected?: Prisma.SortOrder
  pendingCollection?: Prisma.SortOrder
  certificatesEarned?: Prisma.SortOrder
  co2Saved?: Prisma.SortOrder
  treesEquivalent?: Prisma.SortOrder
  monthlyTarget?: Prisma.SortOrder
  profileImageUrl?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CustomerAvgOrderByAggregateInput = {
  employeeCount?: Prisma.SortOrder
  totalWasteCollected?: Prisma.SortOrder
  pendingCollection?: Prisma.SortOrder
  certificatesEarned?: Prisma.SortOrder
  co2Saved?: Prisma.SortOrder
  treesEquivalent?: Prisma.SortOrder
  monthlyTarget?: Prisma.SortOrder
}

export type CustomerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  companyName?: Prisma.SortOrder
  contactPerson?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  address?: Prisma.SortOrder
  industry?: Prisma.SortOrder
  employeeCount?: Prisma.SortOrder
  joinDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalWasteCollected?: Prisma.SortOrder
  pendingCollection?: Prisma.SortOrder
  certificatesEarned?: Prisma.SortOrder
  co2Saved?: Prisma.SortOrder
  treesEquivalent?: Prisma.SortOrder
  monthlyTarget?: Prisma.SortOrder
  profileImageUrl?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CustomerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  companyName?: Prisma.SortOrder
  contactPerson?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  address?: Prisma.SortOrder
  industry?: Prisma.SortOrder
  employeeCount?: Prisma.SortOrder
  joinDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalWasteCollected?: Prisma.SortOrder
  pendingCollection?: Prisma.SortOrder
  certificatesEarned?: Prisma.SortOrder
  co2Saved?: Prisma.SortOrder
  treesEquivalent?: Prisma.SortOrder
  monthlyTarget?: Prisma.SortOrder
  profileImageUrl?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CustomerSumOrderByAggregateInput = {
  employeeCount?: Prisma.SortOrder
  totalWasteCollected?: Prisma.SortOrder
  pendingCollection?: Prisma.SortOrder
  certificatesEarned?: Prisma.SortOrder
  co2Saved?: Prisma.SortOrder
  treesEquivalent?: Prisma.SortOrder
  monthlyTarget?: Prisma.SortOrder
}

export type CustomerScalarRelationFilter = {
  is?: Prisma.CustomerWhereInput
  isNot?: Prisma.CustomerWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type CustomerCreateNestedOneWithoutCollectionsInput = {
  create?: Prisma.XOR<Prisma.CustomerCreateWithoutCollectionsInput, Prisma.CustomerUncheckedCreateWithoutCollectionsInput>
  connectOrCreate?: Prisma.CustomerCreateOrConnectWithoutCollectionsInput
  connect?: Prisma.CustomerWhereUniqueInput
}

export type CustomerUpdateOneRequiredWithoutCollectionsNestedInput = {
  create?: Prisma.XOR<Prisma.CustomerCreateWithoutCollectionsInput, Prisma.CustomerUncheckedCreateWithoutCollectionsInput>
  connectOrCreate?: Prisma.CustomerCreateOrConnectWithoutCollectionsInput
  upsert?: Prisma.CustomerUpsertWithoutCollectionsInput
  connect?: Prisma.CustomerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CustomerUpdateToOneWithWhereWithoutCollectionsInput, Prisma.CustomerUpdateWithoutCollectionsInput>, Prisma.CustomerUncheckedUpdateWithoutCollectionsInput>
}

export type CustomerCreateNestedOneWithoutCertificatesInput = {
  create?: Prisma.XOR<Prisma.CustomerCreateWithoutCertificatesInput, Prisma.CustomerUncheckedCreateWithoutCertificatesInput>
  connectOrCreate?: Prisma.CustomerCreateOrConnectWithoutCertificatesInput
  connect?: Prisma.CustomerWhereUniqueInput
}

export type CustomerUpdateOneRequiredWithoutCertificatesNestedInput = {
  create?: Prisma.XOR<Prisma.CustomerCreateWithoutCertificatesInput, Prisma.CustomerUncheckedCreateWithoutCertificatesInput>
  connectOrCreate?: Prisma.CustomerCreateOrConnectWithoutCertificatesInput
  upsert?: Prisma.CustomerUpsertWithoutCertificatesInput
  connect?: Prisma.CustomerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CustomerUpdateToOneWithWhereWithoutCertificatesInput, Prisma.CustomerUpdateWithoutCertificatesInput>, Prisma.CustomerUncheckedUpdateWithoutCertificatesInput>
}

export type CustomerCreateNestedOneWithoutReportsInput = {
  create?: Prisma.XOR<Prisma.CustomerCreateWithoutReportsInput, Prisma.CustomerUncheckedCreateWithoutReportsInput>
  connectOrCreate?: Prisma.CustomerCreateOrConnectWithoutReportsInput
  connect?: Prisma.CustomerWhereUniqueInput
}

export type CustomerUpdateOneRequiredWithoutReportsNestedInput = {
  create?: Prisma.XOR<Prisma.CustomerCreateWithoutReportsInput, Prisma.CustomerUncheckedCreateWithoutReportsInput>
  connectOrCreate?: Prisma.CustomerCreateOrConnectWithoutReportsInput
  upsert?: Prisma.CustomerUpsertWithoutReportsInput
  connect?: Prisma.CustomerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CustomerUpdateToOneWithWhereWithoutReportsInput, Prisma.CustomerUpdateWithoutReportsInput>, Prisma.CustomerUncheckedUpdateWithoutReportsInput>
}

export type CustomerCreateNestedOneWithoutPasswordResetTokensInput = {
  create?: Prisma.XOR<Prisma.CustomerCreateWithoutPasswordResetTokensInput, Prisma.CustomerUncheckedCreateWithoutPasswordResetTokensInput>
  connectOrCreate?: Prisma.CustomerCreateOrConnectWithoutPasswordResetTokensInput
  connect?: Prisma.CustomerWhereUniqueInput
}

export type CustomerUpdateOneRequiredWithoutPasswordResetTokensNestedInput = {
  create?: Prisma.XOR<Prisma.CustomerCreateWithoutPasswordResetTokensInput, Prisma.CustomerUncheckedCreateWithoutPasswordResetTokensInput>
  connectOrCreate?: Prisma.CustomerCreateOrConnectWithoutPasswordResetTokensInput
  upsert?: Prisma.CustomerUpsertWithoutPasswordResetTokensInput
  connect?: Prisma.CustomerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CustomerUpdateToOneWithWhereWithoutPasswordResetTokensInput, Prisma.CustomerUpdateWithoutPasswordResetTokensInput>, Prisma.CustomerUncheckedUpdateWithoutPasswordResetTokensInput>
}

export type CustomerCreateWithoutCollectionsInput = {
  id?: string
  email: string
  password: string
  companyName: string
  contactPerson?: string | null
  phone?: string | null
  address?: string | null
  industry?: string | null
  employeeCount?: number | null
  joinDate?: Date | string
  status?: string
  totalWasteCollected?: number
  pendingCollection?: number
  certificatesEarned?: number
  co2Saved?: number
  treesEquivalent?: number
  monthlyTarget?: number
  profileImageUrl?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  certificates?: Prisma.CertificateCreateNestedManyWithoutCustomerInput
  reports?: Prisma.ReportCreateNestedManyWithoutCustomerInput
  passwordResetTokens?: Prisma.PasswordResetTokenCreateNestedManyWithoutCustomerInput
}

export type CustomerUncheckedCreateWithoutCollectionsInput = {
  id?: string
  email: string
  password: string
  companyName: string
  contactPerson?: string | null
  phone?: string | null
  address?: string | null
  industry?: string | null
  employeeCount?: number | null
  joinDate?: Date | string
  status?: string
  totalWasteCollected?: number
  pendingCollection?: number
  certificatesEarned?: number
  co2Saved?: number
  treesEquivalent?: number
  monthlyTarget?: number
  profileImageUrl?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  certificates?: Prisma.CertificateUncheckedCreateNestedManyWithoutCustomerInput
  reports?: Prisma.ReportUncheckedCreateNestedManyWithoutCustomerInput
  passwordResetTokens?: Prisma.PasswordResetTokenUncheckedCreateNestedManyWithoutCustomerInput
}

export type CustomerCreateOrConnectWithoutCollectionsInput = {
  where: Prisma.CustomerWhereUniqueInput
  create: Prisma.XOR<Prisma.CustomerCreateWithoutCollectionsInput, Prisma.CustomerUncheckedCreateWithoutCollectionsInput>
}

export type CustomerUpsertWithoutCollectionsInput = {
  update: Prisma.XOR<Prisma.CustomerUpdateWithoutCollectionsInput, Prisma.CustomerUncheckedUpdateWithoutCollectionsInput>
  create: Prisma.XOR<Prisma.CustomerCreateWithoutCollectionsInput, Prisma.CustomerUncheckedCreateWithoutCollectionsInput>
  where?: Prisma.CustomerWhereInput
}

export type CustomerUpdateToOneWithWhereWithoutCollectionsInput = {
  where?: Prisma.CustomerWhereInput
  data: Prisma.XOR<Prisma.CustomerUpdateWithoutCollectionsInput, Prisma.CustomerUncheckedUpdateWithoutCollectionsInput>
}

export type CustomerUpdateWithoutCollectionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  companyName?: Prisma.StringFieldUpdateOperationsInput | string
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  industry?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  employeeCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  joinDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalWasteCollected?: Prisma.FloatFieldUpdateOperationsInput | number
  pendingCollection?: Prisma.FloatFieldUpdateOperationsInput | number
  certificatesEarned?: Prisma.IntFieldUpdateOperationsInput | number
  co2Saved?: Prisma.FloatFieldUpdateOperationsInput | number
  treesEquivalent?: Prisma.IntFieldUpdateOperationsInput | number
  monthlyTarget?: Prisma.FloatFieldUpdateOperationsInput | number
  profileImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  certificates?: Prisma.CertificateUpdateManyWithoutCustomerNestedInput
  reports?: Prisma.ReportUpdateManyWithoutCustomerNestedInput
  passwordResetTokens?: Prisma.PasswordResetTokenUpdateManyWithoutCustomerNestedInput
}

export type CustomerUncheckedUpdateWithoutCollectionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  companyName?: Prisma.StringFieldUpdateOperationsInput | string
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  industry?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  employeeCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  joinDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalWasteCollected?: Prisma.FloatFieldUpdateOperationsInput | number
  pendingCollection?: Prisma.FloatFieldUpdateOperationsInput | number
  certificatesEarned?: Prisma.IntFieldUpdateOperationsInput | number
  co2Saved?: Prisma.FloatFieldUpdateOperationsInput | number
  treesEquivalent?: Prisma.IntFieldUpdateOperationsInput | number
  monthlyTarget?: Prisma.FloatFieldUpdateOperationsInput | number
  profileImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  certificates?: Prisma.CertificateUncheckedUpdateManyWithoutCustomerNestedInput
  reports?: Prisma.ReportUncheckedUpdateManyWithoutCustomerNestedInput
  passwordResetTokens?: Prisma.PasswordResetTokenUncheckedUpdateManyWithoutCustomerNestedInput
}

export type CustomerCreateWithoutCertificatesInput = {
  id?: string
  email: string
  password: string
  companyName: string
  contactPerson?: string | null
  phone?: string | null
  address?: string | null
  industry?: string | null
  employeeCount?: number | null
  joinDate?: Date | string
  status?: string
  totalWasteCollected?: number
  pendingCollection?: number
  certificatesEarned?: number
  co2Saved?: number
  treesEquivalent?: number
  monthlyTarget?: number
  profileImageUrl?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  collections?: Prisma.CollectionCreateNestedManyWithoutCustomerInput
  reports?: Prisma.ReportCreateNestedManyWithoutCustomerInput
  passwordResetTokens?: Prisma.PasswordResetTokenCreateNestedManyWithoutCustomerInput
}

export type CustomerUncheckedCreateWithoutCertificatesInput = {
  id?: string
  email: string
  password: string
  companyName: string
  contactPerson?: string | null
  phone?: string | null
  address?: string | null
  industry?: string | null
  employeeCount?: number | null
  joinDate?: Date | string
  status?: string
  totalWasteCollected?: number
  pendingCollection?: number
  certificatesEarned?: number
  co2Saved?: number
  treesEquivalent?: number
  monthlyTarget?: number
  profileImageUrl?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  collections?: Prisma.CollectionUncheckedCreateNestedManyWithoutCustomerInput
  reports?: Prisma.ReportUncheckedCreateNestedManyWithoutCustomerInput
  passwordResetTokens?: Prisma.PasswordResetTokenUncheckedCreateNestedManyWithoutCustomerInput
}

export type CustomerCreateOrConnectWithoutCertificatesInput = {
  where: Prisma.CustomerWhereUniqueInput
  create: Prisma.XOR<Prisma.CustomerCreateWithoutCertificatesInput, Prisma.CustomerUncheckedCreateWithoutCertificatesInput>
}

export type CustomerUpsertWithoutCertificatesInput = {
  update: Prisma.XOR<Prisma.CustomerUpdateWithoutCertificatesInput, Prisma.CustomerUncheckedUpdateWithoutCertificatesInput>
  create: Prisma.XOR<Prisma.CustomerCreateWithoutCertificatesInput, Prisma.CustomerUncheckedCreateWithoutCertificatesInput>
  where?: Prisma.CustomerWhereInput
}

export type CustomerUpdateToOneWithWhereWithoutCertificatesInput = {
  where?: Prisma.CustomerWhereInput
  data: Prisma.XOR<Prisma.CustomerUpdateWithoutCertificatesInput, Prisma.CustomerUncheckedUpdateWithoutCertificatesInput>
}

export type CustomerUpdateWithoutCertificatesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  companyName?: Prisma.StringFieldUpdateOperationsInput | string
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  industry?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  employeeCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  joinDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalWasteCollected?: Prisma.FloatFieldUpdateOperationsInput | number
  pendingCollection?: Prisma.FloatFieldUpdateOperationsInput | number
  certificatesEarned?: Prisma.IntFieldUpdateOperationsInput | number
  co2Saved?: Prisma.FloatFieldUpdateOperationsInput | number
  treesEquivalent?: Prisma.IntFieldUpdateOperationsInput | number
  monthlyTarget?: Prisma.FloatFieldUpdateOperationsInput | number
  profileImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  collections?: Prisma.CollectionUpdateManyWithoutCustomerNestedInput
  reports?: Prisma.ReportUpdateManyWithoutCustomerNestedInput
  passwordResetTokens?: Prisma.PasswordResetTokenUpdateManyWithoutCustomerNestedInput
}

export type CustomerUncheckedUpdateWithoutCertificatesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  companyName?: Prisma.StringFieldUpdateOperationsInput | string
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  industry?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  employeeCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  joinDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalWasteCollected?: Prisma.FloatFieldUpdateOperationsInput | number
  pendingCollection?: Prisma.FloatFieldUpdateOperationsInput | number
  certificatesEarned?: Prisma.IntFieldUpdateOperationsInput | number
  co2Saved?: Prisma.FloatFieldUpdateOperationsInput | number
  treesEquivalent?: Prisma.IntFieldUpdateOperationsInput | number
  monthlyTarget?: Prisma.FloatFieldUpdateOperationsInput | number
  profileImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  collections?: Prisma.CollectionUncheckedUpdateManyWithoutCustomerNestedInput
  reports?: Prisma.ReportUncheckedUpdateManyWithoutCustomerNestedInput
  passwordResetTokens?: Prisma.PasswordResetTokenUncheckedUpdateManyWithoutCustomerNestedInput
}

export type CustomerCreateWithoutReportsInput = {
  id?: string
  email: string
  password: string
  companyName: string
  contactPerson?: string | null
  phone?: string | null
  address?: string | null
  industry?: string | null
  employeeCount?: number | null
  joinDate?: Date | string
  status?: string
  totalWasteCollected?: number
  pendingCollection?: number
  certificatesEarned?: number
  co2Saved?: number
  treesEquivalent?: number
  monthlyTarget?: number
  profileImageUrl?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  collections?: Prisma.CollectionCreateNestedManyWithoutCustomerInput
  certificates?: Prisma.CertificateCreateNestedManyWithoutCustomerInput
  passwordResetTokens?: Prisma.PasswordResetTokenCreateNestedManyWithoutCustomerInput
}

export type CustomerUncheckedCreateWithoutReportsInput = {
  id?: string
  email: string
  password: string
  companyName: string
  contactPerson?: string | null
  phone?: string | null
  address?: string | null
  industry?: string | null
  employeeCount?: number | null
  joinDate?: Date | string
  status?: string
  totalWasteCollected?: number
  pendingCollection?: number
  certificatesEarned?: number
  co2Saved?: number
  treesEquivalent?: number
  monthlyTarget?: number
  profileImageUrl?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  collections?: Prisma.CollectionUncheckedCreateNestedManyWithoutCustomerInput
  certificates?: Prisma.CertificateUncheckedCreateNestedManyWithoutCustomerInput
  passwordResetTokens?: Prisma.PasswordResetTokenUncheckedCreateNestedManyWithoutCustomerInput
}

export type CustomerCreateOrConnectWithoutReportsInput = {
  where: Prisma.CustomerWhereUniqueInput
  create: Prisma.XOR<Prisma.CustomerCreateWithoutReportsInput, Prisma.CustomerUncheckedCreateWithoutReportsInput>
}

export type CustomerUpsertWithoutReportsInput = {
  update: Prisma.XOR<Prisma.CustomerUpdateWithoutReportsInput, Prisma.CustomerUncheckedUpdateWithoutReportsInput>
  create: Prisma.XOR<Prisma.CustomerCreateWithoutReportsInput, Prisma.CustomerUncheckedCreateWithoutReportsInput>
  where?: Prisma.CustomerWhereInput
}

export type CustomerUpdateToOneWithWhereWithoutReportsInput = {
  where?: Prisma.CustomerWhereInput
  data: Prisma.XOR<Prisma.CustomerUpdateWithoutReportsInput, Prisma.CustomerUncheckedUpdateWithoutReportsInput>
}

export type CustomerUpdateWithoutReportsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  companyName?: Prisma.StringFieldUpdateOperationsInput | string
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  industry?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  employeeCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  joinDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalWasteCollected?: Prisma.FloatFieldUpdateOperationsInput | number
  pendingCollection?: Prisma.FloatFieldUpdateOperationsInput | number
  certificatesEarned?: Prisma.IntFieldUpdateOperationsInput | number
  co2Saved?: Prisma.FloatFieldUpdateOperationsInput | number
  treesEquivalent?: Prisma.IntFieldUpdateOperationsInput | number
  monthlyTarget?: Prisma.FloatFieldUpdateOperationsInput | number
  profileImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  collections?: Prisma.CollectionUpdateManyWithoutCustomerNestedInput
  certificates?: Prisma.CertificateUpdateManyWithoutCustomerNestedInput
  passwordResetTokens?: Prisma.PasswordResetTokenUpdateManyWithoutCustomerNestedInput
}

export type CustomerUncheckedUpdateWithoutReportsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  companyName?: Prisma.StringFieldUpdateOperationsInput | string
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  industry?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  employeeCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  joinDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalWasteCollected?: Prisma.FloatFieldUpdateOperationsInput | number
  pendingCollection?: Prisma.FloatFieldUpdateOperationsInput | number
  certificatesEarned?: Prisma.IntFieldUpdateOperationsInput | number
  co2Saved?: Prisma.FloatFieldUpdateOperationsInput | number
  treesEquivalent?: Prisma.IntFieldUpdateOperationsInput | number
  monthlyTarget?: Prisma.FloatFieldUpdateOperationsInput | number
  profileImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  collections?: Prisma.CollectionUncheckedUpdateManyWithoutCustomerNestedInput
  certificates?: Prisma.CertificateUncheckedUpdateManyWithoutCustomerNestedInput
  passwordResetTokens?: Prisma.PasswordResetTokenUncheckedUpdateManyWithoutCustomerNestedInput
}

export type CustomerCreateWithoutPasswordResetTokensInput = {
  id?: string
  email: string
  password: string
  companyName: string
  contactPerson?: string | null
  phone?: string | null
  address?: string | null
  industry?: string | null
  employeeCount?: number | null
  joinDate?: Date | string
  status?: string
  totalWasteCollected?: number
  pendingCollection?: number
  certificatesEarned?: number
  co2Saved?: number
  treesEquivalent?: number
  monthlyTarget?: number
  profileImageUrl?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  collections?: Prisma.CollectionCreateNestedManyWithoutCustomerInput
  certificates?: Prisma.CertificateCreateNestedManyWithoutCustomerInput
  reports?: Prisma.ReportCreateNestedManyWithoutCustomerInput
}

export type CustomerUncheckedCreateWithoutPasswordResetTokensInput = {
  id?: string
  email: string
  password: string
  companyName: string
  contactPerson?: string | null
  phone?: string | null
  address?: string | null
  industry?: string | null
  employeeCount?: number | null
  joinDate?: Date | string
  status?: string
  totalWasteCollected?: number
  pendingCollection?: number
  certificatesEarned?: number
  co2Saved?: number
  treesEquivalent?: number
  monthlyTarget?: number
  profileImageUrl?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  collections?: Prisma.CollectionUncheckedCreateNestedManyWithoutCustomerInput
  certificates?: Prisma.CertificateUncheckedCreateNestedManyWithoutCustomerInput
  reports?: Prisma.ReportUncheckedCreateNestedManyWithoutCustomerInput
}

export type CustomerCreateOrConnectWithoutPasswordResetTokensInput = {
  where: Prisma.CustomerWhereUniqueInput
  create: Prisma.XOR<Prisma.CustomerCreateWithoutPasswordResetTokensInput, Prisma.CustomerUncheckedCreateWithoutPasswordResetTokensInput>
}

export type CustomerUpsertWithoutPasswordResetTokensInput = {
  update: Prisma.XOR<Prisma.CustomerUpdateWithoutPasswordResetTokensInput, Prisma.CustomerUncheckedUpdateWithoutPasswordResetTokensInput>
  create: Prisma.XOR<Prisma.CustomerCreateWithoutPasswordResetTokensInput, Prisma.CustomerUncheckedCreateWithoutPasswordResetTokensInput>
  where?: Prisma.CustomerWhereInput
}

export type CustomerUpdateToOneWithWhereWithoutPasswordResetTokensInput = {
  where?: Prisma.CustomerWhereInput
  data: Prisma.XOR<Prisma.CustomerUpdateWithoutPasswordResetTokensInput, Prisma.CustomerUncheckedUpdateWithoutPasswordResetTokensInput>
}

export type CustomerUpdateWithoutPasswordResetTokensInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  companyName?: Prisma.StringFieldUpdateOperationsInput | string
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  industry?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  employeeCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  joinDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalWasteCollected?: Prisma.FloatFieldUpdateOperationsInput | number
  pendingCollection?: Prisma.FloatFieldUpdateOperationsInput | number
  certificatesEarned?: Prisma.IntFieldUpdateOperationsInput | number
  co2Saved?: Prisma.FloatFieldUpdateOperationsInput | number
  treesEquivalent?: Prisma.IntFieldUpdateOperationsInput | number
  monthlyTarget?: Prisma.FloatFieldUpdateOperationsInput | number
  profileImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  collections?: Prisma.CollectionUpdateManyWithoutCustomerNestedInput
  certificates?: Prisma.CertificateUpdateManyWithoutCustomerNestedInput
  reports?: Prisma.ReportUpdateManyWithoutCustomerNestedInput
}

export type CustomerUncheckedUpdateWithoutPasswordResetTokensInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  companyName?: Prisma.StringFieldUpdateOperationsInput | string
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  industry?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  employeeCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  joinDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalWasteCollected?: Prisma.FloatFieldUpdateOperationsInput | number
  pendingCollection?: Prisma.FloatFieldUpdateOperationsInput | number
  certificatesEarned?: Prisma.IntFieldUpdateOperationsInput | number
  co2Saved?: Prisma.FloatFieldUpdateOperationsInput | number
  treesEquivalent?: Prisma.IntFieldUpdateOperationsInput | number
  monthlyTarget?: Prisma.FloatFieldUpdateOperationsInput | number
  profileImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  collections?: Prisma.CollectionUncheckedUpdateManyWithoutCustomerNestedInput
  certificates?: Prisma.CertificateUncheckedUpdateManyWithoutCustomerNestedInput
  reports?: Prisma.ReportUncheckedUpdateManyWithoutCustomerNestedInput
}


/**
 * Count Type CustomerCountOutputType
 */

export type CustomerCountOutputType = {
  collections: number
  certificates: number
  reports: number
  passwordResetTokens: number
}

export type CustomerCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  collections?: boolean | CustomerCountOutputTypeCountCollectionsArgs
  certificates?: boolean | CustomerCountOutputTypeCountCertificatesArgs
  reports?: boolean | CustomerCountOutputTypeCountReportsArgs
  passwordResetTokens?: boolean | CustomerCountOutputTypeCountPasswordResetTokensArgs
}

/**
 * CustomerCountOutputType without action
 */
export type CustomerCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerCountOutputType
   */
  select?: Prisma.CustomerCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CustomerCountOutputType without action
 */
export type CustomerCountOutputTypeCountCollectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CollectionWhereInput
}

/**
 * CustomerCountOutputType without action
 */
export type CustomerCountOutputTypeCountCertificatesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CertificateWhereInput
}

/**
 * CustomerCountOutputType without action
 */
export type CustomerCountOutputTypeCountReportsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReportWhereInput
}

/**
 * CustomerCountOutputType without action
 */
export type CustomerCountOutputTypeCountPasswordResetTokensArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PasswordResetTokenWhereInput
}


export type CustomerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  password?: boolean
  companyName?: boolean
  contactPerson?: boolean
  phone?: boolean
  address?: boolean
  industry?: boolean
  employeeCount?: boolean
  joinDate?: boolean
  status?: boolean
  totalWasteCollected?: boolean
  pendingCollection?: boolean
  certificatesEarned?: boolean
  co2Saved?: boolean
  treesEquivalent?: boolean
  monthlyTarget?: boolean
  profileImageUrl?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  collections?: boolean | Prisma.Customer$collectionsArgs<ExtArgs>
  certificates?: boolean | Prisma.Customer$certificatesArgs<ExtArgs>
  reports?: boolean | Prisma.Customer$reportsArgs<ExtArgs>
  passwordResetTokens?: boolean | Prisma.Customer$passwordResetTokensArgs<ExtArgs>
  _count?: boolean | Prisma.CustomerCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["customer"]>

export type CustomerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  password?: boolean
  companyName?: boolean
  contactPerson?: boolean
  phone?: boolean
  address?: boolean
  industry?: boolean
  employeeCount?: boolean
  joinDate?: boolean
  status?: boolean
  totalWasteCollected?: boolean
  pendingCollection?: boolean
  certificatesEarned?: boolean
  co2Saved?: boolean
  treesEquivalent?: boolean
  monthlyTarget?: boolean
  profileImageUrl?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["customer"]>

export type CustomerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  password?: boolean
  companyName?: boolean
  contactPerson?: boolean
  phone?: boolean
  address?: boolean
  industry?: boolean
  employeeCount?: boolean
  joinDate?: boolean
  status?: boolean
  totalWasteCollected?: boolean
  pendingCollection?: boolean
  certificatesEarned?: boolean
  co2Saved?: boolean
  treesEquivalent?: boolean
  monthlyTarget?: boolean
  profileImageUrl?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["customer"]>

export type CustomerSelectScalar = {
  id?: boolean
  email?: boolean
  password?: boolean
  companyName?: boolean
  contactPerson?: boolean
  phone?: boolean
  address?: boolean
  industry?: boolean
  employeeCount?: boolean
  joinDate?: boolean
  status?: boolean
  totalWasteCollected?: boolean
  pendingCollection?: boolean
  certificatesEarned?: boolean
  co2Saved?: boolean
  treesEquivalent?: boolean
  monthlyTarget?: boolean
  profileImageUrl?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CustomerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "email" | "password" | "companyName" | "contactPerson" | "phone" | "address" | "industry" | "employeeCount" | "joinDate" | "status" | "totalWasteCollected" | "pendingCollection" | "certificatesEarned" | "co2Saved" | "treesEquivalent" | "monthlyTarget" | "profileImageUrl" | "notes" | "createdAt" | "updatedAt", ExtArgs["result"]["customer"]>
export type CustomerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  collections?: boolean | Prisma.Customer$collectionsArgs<ExtArgs>
  certificates?: boolean | Prisma.Customer$certificatesArgs<ExtArgs>
  reports?: boolean | Prisma.Customer$reportsArgs<ExtArgs>
  passwordResetTokens?: boolean | Prisma.Customer$passwordResetTokensArgs<ExtArgs>
  _count?: boolean | Prisma.CustomerCountOutputTypeDefaultArgs<ExtArgs>
}
export type CustomerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type CustomerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $CustomerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Customer"
  objects: {
    collections: Prisma.$CollectionPayload<ExtArgs>[]
    certificates: Prisma.$CertificatePayload<ExtArgs>[]
    reports: Prisma.$ReportPayload<ExtArgs>[]
    passwordResetTokens: Prisma.$PasswordResetTokenPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    email: string
    password: string
    companyName: string
    contactPerson: string | null
    phone: string | null
    address: string | null
    industry: string | null
    employeeCount: number | null
    joinDate: Date
    status: string
    totalWasteCollected: number
    pendingCollection: number
    certificatesEarned: number
    co2Saved: number
    treesEquivalent: number
    monthlyTarget: number
    profileImageUrl: string | null
    notes: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["customer"]>
  composites: {}
}

export type CustomerGetPayload<S extends boolean | null | undefined | CustomerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CustomerPayload, S>

export type CustomerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CustomerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CustomerCountAggregateInputType | true
  }

export interface CustomerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Customer'], meta: { name: 'Customer' } }
  /**
   * Find zero or one Customer that matches the filter.
   * @param {CustomerFindUniqueArgs} args - Arguments to find a Customer
   * @example
   * // Get one Customer
   * const customer = await prisma.customer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CustomerFindUniqueArgs>(args: Prisma.SelectSubset<T, CustomerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CustomerClient<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Customer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CustomerFindUniqueOrThrowArgs} args - Arguments to find a Customer
   * @example
   * // Get one Customer
   * const customer = await prisma.customer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CustomerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CustomerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CustomerClient<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Customer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerFindFirstArgs} args - Arguments to find a Customer
   * @example
   * // Get one Customer
   * const customer = await prisma.customer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CustomerFindFirstArgs>(args?: Prisma.SelectSubset<T, CustomerFindFirstArgs<ExtArgs>>): Prisma.Prisma__CustomerClient<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Customer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerFindFirstOrThrowArgs} args - Arguments to find a Customer
   * @example
   * // Get one Customer
   * const customer = await prisma.customer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CustomerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CustomerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CustomerClient<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Customers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Customers
   * const customers = await prisma.customer.findMany()
   * 
   * // Get first 10 Customers
   * const customers = await prisma.customer.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const customerWithIdOnly = await prisma.customer.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CustomerFindManyArgs>(args?: Prisma.SelectSubset<T, CustomerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Customer.
   * @param {CustomerCreateArgs} args - Arguments to create a Customer.
   * @example
   * // Create one Customer
   * const Customer = await prisma.customer.create({
   *   data: {
   *     // ... data to create a Customer
   *   }
   * })
   * 
   */
  create<T extends CustomerCreateArgs>(args: Prisma.SelectSubset<T, CustomerCreateArgs<ExtArgs>>): Prisma.Prisma__CustomerClient<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Customers.
   * @param {CustomerCreateManyArgs} args - Arguments to create many Customers.
   * @example
   * // Create many Customers
   * const customer = await prisma.customer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CustomerCreateManyArgs>(args?: Prisma.SelectSubset<T, CustomerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Customers and returns the data saved in the database.
   * @param {CustomerCreateManyAndReturnArgs} args - Arguments to create many Customers.
   * @example
   * // Create many Customers
   * const customer = await prisma.customer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Customers and only return the `id`
   * const customerWithIdOnly = await prisma.customer.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CustomerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CustomerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Customer.
   * @param {CustomerDeleteArgs} args - Arguments to delete one Customer.
   * @example
   * // Delete one Customer
   * const Customer = await prisma.customer.delete({
   *   where: {
   *     // ... filter to delete one Customer
   *   }
   * })
   * 
   */
  delete<T extends CustomerDeleteArgs>(args: Prisma.SelectSubset<T, CustomerDeleteArgs<ExtArgs>>): Prisma.Prisma__CustomerClient<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Customer.
   * @param {CustomerUpdateArgs} args - Arguments to update one Customer.
   * @example
   * // Update one Customer
   * const customer = await prisma.customer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CustomerUpdateArgs>(args: Prisma.SelectSubset<T, CustomerUpdateArgs<ExtArgs>>): Prisma.Prisma__CustomerClient<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Customers.
   * @param {CustomerDeleteManyArgs} args - Arguments to filter Customers to delete.
   * @example
   * // Delete a few Customers
   * const { count } = await prisma.customer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CustomerDeleteManyArgs>(args?: Prisma.SelectSubset<T, CustomerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Customers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Customers
   * const customer = await prisma.customer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CustomerUpdateManyArgs>(args: Prisma.SelectSubset<T, CustomerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Customers and returns the data updated in the database.
   * @param {CustomerUpdateManyAndReturnArgs} args - Arguments to update many Customers.
   * @example
   * // Update many Customers
   * const customer = await prisma.customer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Customers and only return the `id`
   * const customerWithIdOnly = await prisma.customer.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CustomerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CustomerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Customer.
   * @param {CustomerUpsertArgs} args - Arguments to update or create a Customer.
   * @example
   * // Update or create a Customer
   * const customer = await prisma.customer.upsert({
   *   create: {
   *     // ... data to create a Customer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Customer we want to update
   *   }
   * })
   */
  upsert<T extends CustomerUpsertArgs>(args: Prisma.SelectSubset<T, CustomerUpsertArgs<ExtArgs>>): Prisma.Prisma__CustomerClient<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Customers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerCountArgs} args - Arguments to filter Customers to count.
   * @example
   * // Count the number of Customers
   * const count = await prisma.customer.count({
   *   where: {
   *     // ... the filter for the Customers we want to count
   *   }
   * })
  **/
  count<T extends CustomerCountArgs>(
    args?: Prisma.Subset<T, CustomerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CustomerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Customer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CustomerAggregateArgs>(args: Prisma.Subset<T, CustomerAggregateArgs>): Prisma.PrismaPromise<GetCustomerAggregateType<T>>

  /**
   * Group by Customer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CustomerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CustomerGroupByArgs['orderBy'] }
      : { orderBy?: CustomerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CustomerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCustomerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Customer model
 */
readonly fields: CustomerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Customer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CustomerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  collections<T extends Prisma.Customer$collectionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Customer$collectionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CollectionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  certificates<T extends Prisma.Customer$certificatesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Customer$certificatesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CertificatePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  reports<T extends Prisma.Customer$reportsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Customer$reportsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReportPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  passwordResetTokens<T extends Prisma.Customer$passwordResetTokensArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Customer$passwordResetTokensArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PasswordResetTokenPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Customer model
 */
export interface CustomerFieldRefs {
  readonly id: Prisma.FieldRef<"Customer", 'String'>
  readonly email: Prisma.FieldRef<"Customer", 'String'>
  readonly password: Prisma.FieldRef<"Customer", 'String'>
  readonly companyName: Prisma.FieldRef<"Customer", 'String'>
  readonly contactPerson: Prisma.FieldRef<"Customer", 'String'>
  readonly phone: Prisma.FieldRef<"Customer", 'String'>
  readonly address: Prisma.FieldRef<"Customer", 'String'>
  readonly industry: Prisma.FieldRef<"Customer", 'String'>
  readonly employeeCount: Prisma.FieldRef<"Customer", 'Int'>
  readonly joinDate: Prisma.FieldRef<"Customer", 'DateTime'>
  readonly status: Prisma.FieldRef<"Customer", 'String'>
  readonly totalWasteCollected: Prisma.FieldRef<"Customer", 'Float'>
  readonly pendingCollection: Prisma.FieldRef<"Customer", 'Float'>
  readonly certificatesEarned: Prisma.FieldRef<"Customer", 'Int'>
  readonly co2Saved: Prisma.FieldRef<"Customer", 'Float'>
  readonly treesEquivalent: Prisma.FieldRef<"Customer", 'Int'>
  readonly monthlyTarget: Prisma.FieldRef<"Customer", 'Float'>
  readonly profileImageUrl: Prisma.FieldRef<"Customer", 'String'>
  readonly notes: Prisma.FieldRef<"Customer", 'String'>
  readonly createdAt: Prisma.FieldRef<"Customer", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Customer", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Customer findUnique
 */
export type CustomerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerInclude<ExtArgs> | null
  /**
   * Filter, which Customer to fetch.
   */
  where: Prisma.CustomerWhereUniqueInput
}

/**
 * Customer findUniqueOrThrow
 */
export type CustomerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerInclude<ExtArgs> | null
  /**
   * Filter, which Customer to fetch.
   */
  where: Prisma.CustomerWhereUniqueInput
}

/**
 * Customer findFirst
 */
export type CustomerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerInclude<ExtArgs> | null
  /**
   * Filter, which Customer to fetch.
   */
  where?: Prisma.CustomerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Customers to fetch.
   */
  orderBy?: Prisma.CustomerOrderByWithRelationInput | Prisma.CustomerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Customers.
   */
  cursor?: Prisma.CustomerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Customers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Customers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Customers.
   */
  distinct?: Prisma.CustomerScalarFieldEnum | Prisma.CustomerScalarFieldEnum[]
}

/**
 * Customer findFirstOrThrow
 */
export type CustomerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerInclude<ExtArgs> | null
  /**
   * Filter, which Customer to fetch.
   */
  where?: Prisma.CustomerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Customers to fetch.
   */
  orderBy?: Prisma.CustomerOrderByWithRelationInput | Prisma.CustomerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Customers.
   */
  cursor?: Prisma.CustomerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Customers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Customers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Customers.
   */
  distinct?: Prisma.CustomerScalarFieldEnum | Prisma.CustomerScalarFieldEnum[]
}

/**
 * Customer findMany
 */
export type CustomerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerInclude<ExtArgs> | null
  /**
   * Filter, which Customers to fetch.
   */
  where?: Prisma.CustomerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Customers to fetch.
   */
  orderBy?: Prisma.CustomerOrderByWithRelationInput | Prisma.CustomerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Customers.
   */
  cursor?: Prisma.CustomerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Customers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Customers.
   */
  skip?: number
  distinct?: Prisma.CustomerScalarFieldEnum | Prisma.CustomerScalarFieldEnum[]
}

/**
 * Customer create
 */
export type CustomerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerInclude<ExtArgs> | null
  /**
   * The data needed to create a Customer.
   */
  data: Prisma.XOR<Prisma.CustomerCreateInput, Prisma.CustomerUncheckedCreateInput>
}

/**
 * Customer createMany
 */
export type CustomerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Customers.
   */
  data: Prisma.CustomerCreateManyInput | Prisma.CustomerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Customer createManyAndReturn
 */
export type CustomerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * The data used to create many Customers.
   */
  data: Prisma.CustomerCreateManyInput | Prisma.CustomerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Customer update
 */
export type CustomerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerInclude<ExtArgs> | null
  /**
   * The data needed to update a Customer.
   */
  data: Prisma.XOR<Prisma.CustomerUpdateInput, Prisma.CustomerUncheckedUpdateInput>
  /**
   * Choose, which Customer to update.
   */
  where: Prisma.CustomerWhereUniqueInput
}

/**
 * Customer updateMany
 */
export type CustomerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Customers.
   */
  data: Prisma.XOR<Prisma.CustomerUpdateManyMutationInput, Prisma.CustomerUncheckedUpdateManyInput>
  /**
   * Filter which Customers to update
   */
  where?: Prisma.CustomerWhereInput
  /**
   * Limit how many Customers to update.
   */
  limit?: number
}

/**
 * Customer updateManyAndReturn
 */
export type CustomerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * The data used to update Customers.
   */
  data: Prisma.XOR<Prisma.CustomerUpdateManyMutationInput, Prisma.CustomerUncheckedUpdateManyInput>
  /**
   * Filter which Customers to update
   */
  where?: Prisma.CustomerWhereInput
  /**
   * Limit how many Customers to update.
   */
  limit?: number
}

/**
 * Customer upsert
 */
export type CustomerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerInclude<ExtArgs> | null
  /**
   * The filter to search for the Customer to update in case it exists.
   */
  where: Prisma.CustomerWhereUniqueInput
  /**
   * In case the Customer found by the `where` argument doesn't exist, create a new Customer with this data.
   */
  create: Prisma.XOR<Prisma.CustomerCreateInput, Prisma.CustomerUncheckedCreateInput>
  /**
   * In case the Customer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CustomerUpdateInput, Prisma.CustomerUncheckedUpdateInput>
}

/**
 * Customer delete
 */
export type CustomerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerInclude<ExtArgs> | null
  /**
   * Filter which Customer to delete.
   */
  where: Prisma.CustomerWhereUniqueInput
}

/**
 * Customer deleteMany
 */
export type CustomerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Customers to delete
   */
  where?: Prisma.CustomerWhereInput
  /**
   * Limit how many Customers to delete.
   */
  limit?: number
}

/**
 * Customer.collections
 */
export type Customer$collectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Collection
   */
  select?: Prisma.CollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Collection
   */
  omit?: Prisma.CollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CollectionInclude<ExtArgs> | null
  where?: Prisma.CollectionWhereInput
  orderBy?: Prisma.CollectionOrderByWithRelationInput | Prisma.CollectionOrderByWithRelationInput[]
  cursor?: Prisma.CollectionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CollectionScalarFieldEnum | Prisma.CollectionScalarFieldEnum[]
}

/**
 * Customer.certificates
 */
export type Customer$certificatesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Certificate
   */
  select?: Prisma.CertificateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Certificate
   */
  omit?: Prisma.CertificateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateInclude<ExtArgs> | null
  where?: Prisma.CertificateWhereInput
  orderBy?: Prisma.CertificateOrderByWithRelationInput | Prisma.CertificateOrderByWithRelationInput[]
  cursor?: Prisma.CertificateWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CertificateScalarFieldEnum | Prisma.CertificateScalarFieldEnum[]
}

/**
 * Customer.reports
 */
export type Customer$reportsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Report
   */
  select?: Prisma.ReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Report
   */
  omit?: Prisma.ReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReportInclude<ExtArgs> | null
  where?: Prisma.ReportWhereInput
  orderBy?: Prisma.ReportOrderByWithRelationInput | Prisma.ReportOrderByWithRelationInput[]
  cursor?: Prisma.ReportWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ReportScalarFieldEnum | Prisma.ReportScalarFieldEnum[]
}

/**
 * Customer.passwordResetTokens
 */
export type Customer$passwordResetTokensArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PasswordResetToken
   */
  select?: Prisma.PasswordResetTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PasswordResetToken
   */
  omit?: Prisma.PasswordResetTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PasswordResetTokenInclude<ExtArgs> | null
  where?: Prisma.PasswordResetTokenWhereInput
  orderBy?: Prisma.PasswordResetTokenOrderByWithRelationInput | Prisma.PasswordResetTokenOrderByWithRelationInput[]
  cursor?: Prisma.PasswordResetTokenWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PasswordResetTokenScalarFieldEnum | Prisma.PasswordResetTokenScalarFieldEnum[]
}

/**
 * Customer without action
 */
export type CustomerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerInclude<ExtArgs> | null
}
