
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `GlobalImpact` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model GlobalImpact
 * 
 */
export type GlobalImpactModel = runtime.Types.Result.DefaultSelection<Prisma.$GlobalImpactPayload>

export type AggregateGlobalImpact = {
  _count: GlobalImpactCountAggregateOutputType | null
  _avg: GlobalImpactAvgAggregateOutputType | null
  _sum: GlobalImpactSumAggregateOutputType | null
  _min: GlobalImpactMinAggregateOutputType | null
  _max: GlobalImpactMaxAggregateOutputType | null
}

export type GlobalImpactAvgAggregateOutputType = {
  wasteCollected: number | null
  productsCreated: number | null
  treesEquivalent: number | null
  co2Prevented: number | null
}

export type GlobalImpactSumAggregateOutputType = {
  wasteCollected: number | null
  productsCreated: number | null
  treesEquivalent: number | null
  co2Prevented: number | null
}

export type GlobalImpactMinAggregateOutputType = {
  id: string | null
  wasteCollected: number | null
  productsCreated: number | null
  treesEquivalent: number | null
  co2Prevented: number | null
  updatedAt: Date | null
}

export type GlobalImpactMaxAggregateOutputType = {
  id: string | null
  wasteCollected: number | null
  productsCreated: number | null
  treesEquivalent: number | null
  co2Prevented: number | null
  updatedAt: Date | null
}

export type GlobalImpactCountAggregateOutputType = {
  id: number
  wasteCollected: number
  productsCreated: number
  treesEquivalent: number
  co2Prevented: number
  updatedAt: number
  _all: number
}


export type GlobalImpactAvgAggregateInputType = {
  wasteCollected?: true
  productsCreated?: true
  treesEquivalent?: true
  co2Prevented?: true
}

export type GlobalImpactSumAggregateInputType = {
  wasteCollected?: true
  productsCreated?: true
  treesEquivalent?: true
  co2Prevented?: true
}

export type GlobalImpactMinAggregateInputType = {
  id?: true
  wasteCollected?: true
  productsCreated?: true
  treesEquivalent?: true
  co2Prevented?: true
  updatedAt?: true
}

export type GlobalImpactMaxAggregateInputType = {
  id?: true
  wasteCollected?: true
  productsCreated?: true
  treesEquivalent?: true
  co2Prevented?: true
  updatedAt?: true
}

export type GlobalImpactCountAggregateInputType = {
  id?: true
  wasteCollected?: true
  productsCreated?: true
  treesEquivalent?: true
  co2Prevented?: true
  updatedAt?: true
  _all?: true
}

export type GlobalImpactAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GlobalImpact to aggregate.
   */
  where?: Prisma.GlobalImpactWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GlobalImpacts to fetch.
   */
  orderBy?: Prisma.GlobalImpactOrderByWithRelationInput | Prisma.GlobalImpactOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GlobalImpactWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GlobalImpacts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GlobalImpacts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned GlobalImpacts
  **/
  _count?: true | GlobalImpactCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: GlobalImpactAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: GlobalImpactSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GlobalImpactMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GlobalImpactMaxAggregateInputType
}

export type GetGlobalImpactAggregateType<T extends GlobalImpactAggregateArgs> = {
      [P in keyof T & keyof AggregateGlobalImpact]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGlobalImpact[P]>
    : Prisma.GetScalarType<T[P], AggregateGlobalImpact[P]>
}




export type GlobalImpactGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GlobalImpactWhereInput
  orderBy?: Prisma.GlobalImpactOrderByWithAggregationInput | Prisma.GlobalImpactOrderByWithAggregationInput[]
  by: Prisma.GlobalImpactScalarFieldEnum[] | Prisma.GlobalImpactScalarFieldEnum
  having?: Prisma.GlobalImpactScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GlobalImpactCountAggregateInputType | true
  _avg?: GlobalImpactAvgAggregateInputType
  _sum?: GlobalImpactSumAggregateInputType
  _min?: GlobalImpactMinAggregateInputType
  _max?: GlobalImpactMaxAggregateInputType
}

export type GlobalImpactGroupByOutputType = {
  id: string
  wasteCollected: number
  productsCreated: number
  treesEquivalent: number
  co2Prevented: number
  updatedAt: Date
  _count: GlobalImpactCountAggregateOutputType | null
  _avg: GlobalImpactAvgAggregateOutputType | null
  _sum: GlobalImpactSumAggregateOutputType | null
  _min: GlobalImpactMinAggregateOutputType | null
  _max: GlobalImpactMaxAggregateOutputType | null
}

type GetGlobalImpactGroupByPayload<T extends GlobalImpactGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GlobalImpactGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GlobalImpactGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GlobalImpactGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GlobalImpactGroupByOutputType[P]>
      }
    >
  >



export type GlobalImpactWhereInput = {
  AND?: Prisma.GlobalImpactWhereInput | Prisma.GlobalImpactWhereInput[]
  OR?: Prisma.GlobalImpactWhereInput[]
  NOT?: Prisma.GlobalImpactWhereInput | Prisma.GlobalImpactWhereInput[]
  id?: Prisma.StringFilter<"GlobalImpact"> | string
  wasteCollected?: Prisma.FloatFilter<"GlobalImpact"> | number
  productsCreated?: Prisma.FloatFilter<"GlobalImpact"> | number
  treesEquivalent?: Prisma.IntFilter<"GlobalImpact"> | number
  co2Prevented?: Prisma.FloatFilter<"GlobalImpact"> | number
  updatedAt?: Prisma.DateTimeFilter<"GlobalImpact"> | Date | string
}

export type GlobalImpactOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  wasteCollected?: Prisma.SortOrder
  productsCreated?: Prisma.SortOrder
  treesEquivalent?: Prisma.SortOrder
  co2Prevented?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GlobalImpactWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.GlobalImpactWhereInput | Prisma.GlobalImpactWhereInput[]
  OR?: Prisma.GlobalImpactWhereInput[]
  NOT?: Prisma.GlobalImpactWhereInput | Prisma.GlobalImpactWhereInput[]
  wasteCollected?: Prisma.FloatFilter<"GlobalImpact"> | number
  productsCreated?: Prisma.FloatFilter<"GlobalImpact"> | number
  treesEquivalent?: Prisma.IntFilter<"GlobalImpact"> | number
  co2Prevented?: Prisma.FloatFilter<"GlobalImpact"> | number
  updatedAt?: Prisma.DateTimeFilter<"GlobalImpact"> | Date | string
}, "id">

export type GlobalImpactOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  wasteCollected?: Prisma.SortOrder
  productsCreated?: Prisma.SortOrder
  treesEquivalent?: Prisma.SortOrder
  co2Prevented?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.GlobalImpactCountOrderByAggregateInput
  _avg?: Prisma.GlobalImpactAvgOrderByAggregateInput
  _max?: Prisma.GlobalImpactMaxOrderByAggregateInput
  _min?: Prisma.GlobalImpactMinOrderByAggregateInput
  _sum?: Prisma.GlobalImpactSumOrderByAggregateInput
}

export type GlobalImpactScalarWhereWithAggregatesInput = {
  AND?: Prisma.GlobalImpactScalarWhereWithAggregatesInput | Prisma.GlobalImpactScalarWhereWithAggregatesInput[]
  OR?: Prisma.GlobalImpactScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GlobalImpactScalarWhereWithAggregatesInput | Prisma.GlobalImpactScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"GlobalImpact"> | string
  wasteCollected?: Prisma.FloatWithAggregatesFilter<"GlobalImpact"> | number
  productsCreated?: Prisma.FloatWithAggregatesFilter<"GlobalImpact"> | number
  treesEquivalent?: Prisma.IntWithAggregatesFilter<"GlobalImpact"> | number
  co2Prevented?: Prisma.FloatWithAggregatesFilter<"GlobalImpact"> | number
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"GlobalImpact"> | Date | string
}

export type GlobalImpactCreateInput = {
  id?: string
  wasteCollected?: number
  productsCreated?: number
  treesEquivalent?: number
  co2Prevented?: number
  updatedAt?: Date | string
}

export type GlobalImpactUncheckedCreateInput = {
  id?: string
  wasteCollected?: number
  productsCreated?: number
  treesEquivalent?: number
  co2Prevented?: number
  updatedAt?: Date | string
}

export type GlobalImpactUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  wasteCollected?: Prisma.FloatFieldUpdateOperationsInput | number
  productsCreated?: Prisma.FloatFieldUpdateOperationsInput | number
  treesEquivalent?: Prisma.IntFieldUpdateOperationsInput | number
  co2Prevented?: Prisma.FloatFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GlobalImpactUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  wasteCollected?: Prisma.FloatFieldUpdateOperationsInput | number
  productsCreated?: Prisma.FloatFieldUpdateOperationsInput | number
  treesEquivalent?: Prisma.IntFieldUpdateOperationsInput | number
  co2Prevented?: Prisma.FloatFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GlobalImpactCreateManyInput = {
  id?: string
  wasteCollected?: number
  productsCreated?: number
  treesEquivalent?: number
  co2Prevented?: number
  updatedAt?: Date | string
}

export type GlobalImpactUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  wasteCollected?: Prisma.FloatFieldUpdateOperationsInput | number
  productsCreated?: Prisma.FloatFieldUpdateOperationsInput | number
  treesEquivalent?: Prisma.IntFieldUpdateOperationsInput | number
  co2Prevented?: Prisma.FloatFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GlobalImpactUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  wasteCollected?: Prisma.FloatFieldUpdateOperationsInput | number
  productsCreated?: Prisma.FloatFieldUpdateOperationsInput | number
  treesEquivalent?: Prisma.IntFieldUpdateOperationsInput | number
  co2Prevented?: Prisma.FloatFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GlobalImpactCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  wasteCollected?: Prisma.SortOrder
  productsCreated?: Prisma.SortOrder
  treesEquivalent?: Prisma.SortOrder
  co2Prevented?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GlobalImpactAvgOrderByAggregateInput = {
  wasteCollected?: Prisma.SortOrder
  productsCreated?: Prisma.SortOrder
  treesEquivalent?: Prisma.SortOrder
  co2Prevented?: Prisma.SortOrder
}

export type GlobalImpactMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  wasteCollected?: Prisma.SortOrder
  productsCreated?: Prisma.SortOrder
  treesEquivalent?: Prisma.SortOrder
  co2Prevented?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GlobalImpactMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  wasteCollected?: Prisma.SortOrder
  productsCreated?: Prisma.SortOrder
  treesEquivalent?: Prisma.SortOrder
  co2Prevented?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GlobalImpactSumOrderByAggregateInput = {
  wasteCollected?: Prisma.SortOrder
  productsCreated?: Prisma.SortOrder
  treesEquivalent?: Prisma.SortOrder
  co2Prevented?: Prisma.SortOrder
}



export type GlobalImpactSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  wasteCollected?: boolean
  productsCreated?: boolean
  treesEquivalent?: boolean
  co2Prevented?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["globalImpact"]>

export type GlobalImpactSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  wasteCollected?: boolean
  productsCreated?: boolean
  treesEquivalent?: boolean
  co2Prevented?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["globalImpact"]>

export type GlobalImpactSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  wasteCollected?: boolean
  productsCreated?: boolean
  treesEquivalent?: boolean
  co2Prevented?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["globalImpact"]>

export type GlobalImpactSelectScalar = {
  id?: boolean
  wasteCollected?: boolean
  productsCreated?: boolean
  treesEquivalent?: boolean
  co2Prevented?: boolean
  updatedAt?: boolean
}

export type GlobalImpactOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "wasteCollected" | "productsCreated" | "treesEquivalent" | "co2Prevented" | "updatedAt", ExtArgs["result"]["globalImpact"]>

export type $GlobalImpactPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "GlobalImpact"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    wasteCollected: number
    productsCreated: number
    treesEquivalent: number
    co2Prevented: number
    updatedAt: Date
  }, ExtArgs["result"]["globalImpact"]>
  composites: {}
}

export type GlobalImpactGetPayload<S extends boolean | null | undefined | GlobalImpactDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GlobalImpactPayload, S>

export type GlobalImpactCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GlobalImpactFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GlobalImpactCountAggregateInputType | true
  }

export interface GlobalImpactDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['GlobalImpact'], meta: { name: 'GlobalImpact' } }
  /**
   * Find zero or one GlobalImpact that matches the filter.
   * @param {GlobalImpactFindUniqueArgs} args - Arguments to find a GlobalImpact
   * @example
   * // Get one GlobalImpact
   * const globalImpact = await prisma.globalImpact.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GlobalImpactFindUniqueArgs>(args: Prisma.SelectSubset<T, GlobalImpactFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GlobalImpactClient<runtime.Types.Result.GetResult<Prisma.$GlobalImpactPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one GlobalImpact that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GlobalImpactFindUniqueOrThrowArgs} args - Arguments to find a GlobalImpact
   * @example
   * // Get one GlobalImpact
   * const globalImpact = await prisma.globalImpact.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GlobalImpactFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GlobalImpactFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GlobalImpactClient<runtime.Types.Result.GetResult<Prisma.$GlobalImpactPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GlobalImpact that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalImpactFindFirstArgs} args - Arguments to find a GlobalImpact
   * @example
   * // Get one GlobalImpact
   * const globalImpact = await prisma.globalImpact.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GlobalImpactFindFirstArgs>(args?: Prisma.SelectSubset<T, GlobalImpactFindFirstArgs<ExtArgs>>): Prisma.Prisma__GlobalImpactClient<runtime.Types.Result.GetResult<Prisma.$GlobalImpactPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GlobalImpact that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalImpactFindFirstOrThrowArgs} args - Arguments to find a GlobalImpact
   * @example
   * // Get one GlobalImpact
   * const globalImpact = await prisma.globalImpact.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GlobalImpactFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GlobalImpactFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GlobalImpactClient<runtime.Types.Result.GetResult<Prisma.$GlobalImpactPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GlobalImpacts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalImpactFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all GlobalImpacts
   * const globalImpacts = await prisma.globalImpact.findMany()
   * 
   * // Get first 10 GlobalImpacts
   * const globalImpacts = await prisma.globalImpact.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const globalImpactWithIdOnly = await prisma.globalImpact.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GlobalImpactFindManyArgs>(args?: Prisma.SelectSubset<T, GlobalImpactFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GlobalImpactPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a GlobalImpact.
   * @param {GlobalImpactCreateArgs} args - Arguments to create a GlobalImpact.
   * @example
   * // Create one GlobalImpact
   * const GlobalImpact = await prisma.globalImpact.create({
   *   data: {
   *     // ... data to create a GlobalImpact
   *   }
   * })
   * 
   */
  create<T extends GlobalImpactCreateArgs>(args: Prisma.SelectSubset<T, GlobalImpactCreateArgs<ExtArgs>>): Prisma.Prisma__GlobalImpactClient<runtime.Types.Result.GetResult<Prisma.$GlobalImpactPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many GlobalImpacts.
   * @param {GlobalImpactCreateManyArgs} args - Arguments to create many GlobalImpacts.
   * @example
   * // Create many GlobalImpacts
   * const globalImpact = await prisma.globalImpact.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GlobalImpactCreateManyArgs>(args?: Prisma.SelectSubset<T, GlobalImpactCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many GlobalImpacts and returns the data saved in the database.
   * @param {GlobalImpactCreateManyAndReturnArgs} args - Arguments to create many GlobalImpacts.
   * @example
   * // Create many GlobalImpacts
   * const globalImpact = await prisma.globalImpact.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many GlobalImpacts and only return the `id`
   * const globalImpactWithIdOnly = await prisma.globalImpact.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GlobalImpactCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GlobalImpactCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GlobalImpactPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a GlobalImpact.
   * @param {GlobalImpactDeleteArgs} args - Arguments to delete one GlobalImpact.
   * @example
   * // Delete one GlobalImpact
   * const GlobalImpact = await prisma.globalImpact.delete({
   *   where: {
   *     // ... filter to delete one GlobalImpact
   *   }
   * })
   * 
   */
  delete<T extends GlobalImpactDeleteArgs>(args: Prisma.SelectSubset<T, GlobalImpactDeleteArgs<ExtArgs>>): Prisma.Prisma__GlobalImpactClient<runtime.Types.Result.GetResult<Prisma.$GlobalImpactPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one GlobalImpact.
   * @param {GlobalImpactUpdateArgs} args - Arguments to update one GlobalImpact.
   * @example
   * // Update one GlobalImpact
   * const globalImpact = await prisma.globalImpact.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GlobalImpactUpdateArgs>(args: Prisma.SelectSubset<T, GlobalImpactUpdateArgs<ExtArgs>>): Prisma.Prisma__GlobalImpactClient<runtime.Types.Result.GetResult<Prisma.$GlobalImpactPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more GlobalImpacts.
   * @param {GlobalImpactDeleteManyArgs} args - Arguments to filter GlobalImpacts to delete.
   * @example
   * // Delete a few GlobalImpacts
   * const { count } = await prisma.globalImpact.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GlobalImpactDeleteManyArgs>(args?: Prisma.SelectSubset<T, GlobalImpactDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GlobalImpacts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalImpactUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many GlobalImpacts
   * const globalImpact = await prisma.globalImpact.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GlobalImpactUpdateManyArgs>(args: Prisma.SelectSubset<T, GlobalImpactUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GlobalImpacts and returns the data updated in the database.
   * @param {GlobalImpactUpdateManyAndReturnArgs} args - Arguments to update many GlobalImpacts.
   * @example
   * // Update many GlobalImpacts
   * const globalImpact = await prisma.globalImpact.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more GlobalImpacts and only return the `id`
   * const globalImpactWithIdOnly = await prisma.globalImpact.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GlobalImpactUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GlobalImpactUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GlobalImpactPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one GlobalImpact.
   * @param {GlobalImpactUpsertArgs} args - Arguments to update or create a GlobalImpact.
   * @example
   * // Update or create a GlobalImpact
   * const globalImpact = await prisma.globalImpact.upsert({
   *   create: {
   *     // ... data to create a GlobalImpact
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the GlobalImpact we want to update
   *   }
   * })
   */
  upsert<T extends GlobalImpactUpsertArgs>(args: Prisma.SelectSubset<T, GlobalImpactUpsertArgs<ExtArgs>>): Prisma.Prisma__GlobalImpactClient<runtime.Types.Result.GetResult<Prisma.$GlobalImpactPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of GlobalImpacts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalImpactCountArgs} args - Arguments to filter GlobalImpacts to count.
   * @example
   * // Count the number of GlobalImpacts
   * const count = await prisma.globalImpact.count({
   *   where: {
   *     // ... the filter for the GlobalImpacts we want to count
   *   }
   * })
  **/
  count<T extends GlobalImpactCountArgs>(
    args?: Prisma.Subset<T, GlobalImpactCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GlobalImpactCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a GlobalImpact.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalImpactAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GlobalImpactAggregateArgs>(args: Prisma.Subset<T, GlobalImpactAggregateArgs>): Prisma.PrismaPromise<GetGlobalImpactAggregateType<T>>

  /**
   * Group by GlobalImpact.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalImpactGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GlobalImpactGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GlobalImpactGroupByArgs['orderBy'] }
      : { orderBy?: GlobalImpactGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GlobalImpactGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGlobalImpactGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the GlobalImpact model
 */
readonly fields: GlobalImpactFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for GlobalImpact.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GlobalImpactClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the GlobalImpact model
 */
export interface GlobalImpactFieldRefs {
  readonly id: Prisma.FieldRef<"GlobalImpact", 'String'>
  readonly wasteCollected: Prisma.FieldRef<"GlobalImpact", 'Float'>
  readonly productsCreated: Prisma.FieldRef<"GlobalImpact", 'Float'>
  readonly treesEquivalent: Prisma.FieldRef<"GlobalImpact", 'Int'>
  readonly co2Prevented: Prisma.FieldRef<"GlobalImpact", 'Float'>
  readonly updatedAt: Prisma.FieldRef<"GlobalImpact", 'DateTime'>
}
    

// Custom InputTypes
/**
 * GlobalImpact findUnique
 */
export type GlobalImpactFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalImpact
   */
  select?: Prisma.GlobalImpactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalImpact
   */
  omit?: Prisma.GlobalImpactOmit<ExtArgs> | null
  /**
   * Filter, which GlobalImpact to fetch.
   */
  where: Prisma.GlobalImpactWhereUniqueInput
}

/**
 * GlobalImpact findUniqueOrThrow
 */
export type GlobalImpactFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalImpact
   */
  select?: Prisma.GlobalImpactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalImpact
   */
  omit?: Prisma.GlobalImpactOmit<ExtArgs> | null
  /**
   * Filter, which GlobalImpact to fetch.
   */
  where: Prisma.GlobalImpactWhereUniqueInput
}

/**
 * GlobalImpact findFirst
 */
export type GlobalImpactFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalImpact
   */
  select?: Prisma.GlobalImpactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalImpact
   */
  omit?: Prisma.GlobalImpactOmit<ExtArgs> | null
  /**
   * Filter, which GlobalImpact to fetch.
   */
  where?: Prisma.GlobalImpactWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GlobalImpacts to fetch.
   */
  orderBy?: Prisma.GlobalImpactOrderByWithRelationInput | Prisma.GlobalImpactOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GlobalImpacts.
   */
  cursor?: Prisma.GlobalImpactWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GlobalImpacts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GlobalImpacts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GlobalImpacts.
   */
  distinct?: Prisma.GlobalImpactScalarFieldEnum | Prisma.GlobalImpactScalarFieldEnum[]
}

/**
 * GlobalImpact findFirstOrThrow
 */
export type GlobalImpactFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalImpact
   */
  select?: Prisma.GlobalImpactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalImpact
   */
  omit?: Prisma.GlobalImpactOmit<ExtArgs> | null
  /**
   * Filter, which GlobalImpact to fetch.
   */
  where?: Prisma.GlobalImpactWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GlobalImpacts to fetch.
   */
  orderBy?: Prisma.GlobalImpactOrderByWithRelationInput | Prisma.GlobalImpactOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GlobalImpacts.
   */
  cursor?: Prisma.GlobalImpactWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GlobalImpacts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GlobalImpacts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GlobalImpacts.
   */
  distinct?: Prisma.GlobalImpactScalarFieldEnum | Prisma.GlobalImpactScalarFieldEnum[]
}

/**
 * GlobalImpact findMany
 */
export type GlobalImpactFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalImpact
   */
  select?: Prisma.GlobalImpactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalImpact
   */
  omit?: Prisma.GlobalImpactOmit<ExtArgs> | null
  /**
   * Filter, which GlobalImpacts to fetch.
   */
  where?: Prisma.GlobalImpactWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GlobalImpacts to fetch.
   */
  orderBy?: Prisma.GlobalImpactOrderByWithRelationInput | Prisma.GlobalImpactOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing GlobalImpacts.
   */
  cursor?: Prisma.GlobalImpactWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GlobalImpacts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GlobalImpacts.
   */
  skip?: number
  distinct?: Prisma.GlobalImpactScalarFieldEnum | Prisma.GlobalImpactScalarFieldEnum[]
}

/**
 * GlobalImpact create
 */
export type GlobalImpactCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalImpact
   */
  select?: Prisma.GlobalImpactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalImpact
   */
  omit?: Prisma.GlobalImpactOmit<ExtArgs> | null
  /**
   * The data needed to create a GlobalImpact.
   */
  data: Prisma.XOR<Prisma.GlobalImpactCreateInput, Prisma.GlobalImpactUncheckedCreateInput>
}

/**
 * GlobalImpact createMany
 */
export type GlobalImpactCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many GlobalImpacts.
   */
  data: Prisma.GlobalImpactCreateManyInput | Prisma.GlobalImpactCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * GlobalImpact createManyAndReturn
 */
export type GlobalImpactCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalImpact
   */
  select?: Prisma.GlobalImpactSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalImpact
   */
  omit?: Prisma.GlobalImpactOmit<ExtArgs> | null
  /**
   * The data used to create many GlobalImpacts.
   */
  data: Prisma.GlobalImpactCreateManyInput | Prisma.GlobalImpactCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * GlobalImpact update
 */
export type GlobalImpactUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalImpact
   */
  select?: Prisma.GlobalImpactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalImpact
   */
  omit?: Prisma.GlobalImpactOmit<ExtArgs> | null
  /**
   * The data needed to update a GlobalImpact.
   */
  data: Prisma.XOR<Prisma.GlobalImpactUpdateInput, Prisma.GlobalImpactUncheckedUpdateInput>
  /**
   * Choose, which GlobalImpact to update.
   */
  where: Prisma.GlobalImpactWhereUniqueInput
}

/**
 * GlobalImpact updateMany
 */
export type GlobalImpactUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update GlobalImpacts.
   */
  data: Prisma.XOR<Prisma.GlobalImpactUpdateManyMutationInput, Prisma.GlobalImpactUncheckedUpdateManyInput>
  /**
   * Filter which GlobalImpacts to update
   */
  where?: Prisma.GlobalImpactWhereInput
  /**
   * Limit how many GlobalImpacts to update.
   */
  limit?: number
}

/**
 * GlobalImpact updateManyAndReturn
 */
export type GlobalImpactUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalImpact
   */
  select?: Prisma.GlobalImpactSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalImpact
   */
  omit?: Prisma.GlobalImpactOmit<ExtArgs> | null
  /**
   * The data used to update GlobalImpacts.
   */
  data: Prisma.XOR<Prisma.GlobalImpactUpdateManyMutationInput, Prisma.GlobalImpactUncheckedUpdateManyInput>
  /**
   * Filter which GlobalImpacts to update
   */
  where?: Prisma.GlobalImpactWhereInput
  /**
   * Limit how many GlobalImpacts to update.
   */
  limit?: number
}

/**
 * GlobalImpact upsert
 */
export type GlobalImpactUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalImpact
   */
  select?: Prisma.GlobalImpactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalImpact
   */
  omit?: Prisma.GlobalImpactOmit<ExtArgs> | null
  /**
   * The filter to search for the GlobalImpact to update in case it exists.
   */
  where: Prisma.GlobalImpactWhereUniqueInput
  /**
   * In case the GlobalImpact found by the `where` argument doesn't exist, create a new GlobalImpact with this data.
   */
  create: Prisma.XOR<Prisma.GlobalImpactCreateInput, Prisma.GlobalImpactUncheckedCreateInput>
  /**
   * In case the GlobalImpact was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GlobalImpactUpdateInput, Prisma.GlobalImpactUncheckedUpdateInput>
}

/**
 * GlobalImpact delete
 */
export type GlobalImpactDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalImpact
   */
  select?: Prisma.GlobalImpactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalImpact
   */
  omit?: Prisma.GlobalImpactOmit<ExtArgs> | null
  /**
   * Filter which GlobalImpact to delete.
   */
  where: Prisma.GlobalImpactWhereUniqueInput
}

/**
 * GlobalImpact deleteMany
 */
export type GlobalImpactDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GlobalImpacts to delete
   */
  where?: Prisma.GlobalImpactWhereInput
  /**
   * Limit how many GlobalImpacts to delete.
   */
  limit?: number
}

/**
 * GlobalImpact without action
 */
export type GlobalImpactDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalImpact
   */
  select?: Prisma.GlobalImpactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalImpact
   */
  omit?: Prisma.GlobalImpactOmit<ExtArgs> | null
}
