
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LsuTeam` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model LsuTeam
 * LSU Name + Technician pairs for customer form dropdowns
 */
export type LsuTeamModel = runtime.Types.Result.DefaultSelection<Prisma.$LsuTeamPayload>

export type AggregateLsuTeam = {
  _count: LsuTeamCountAggregateOutputType | null
  _avg: LsuTeamAvgAggregateOutputType | null
  _sum: LsuTeamSumAggregateOutputType | null
  _min: LsuTeamMinAggregateOutputType | null
  _max: LsuTeamMaxAggregateOutputType | null
}

export type LsuTeamAvgAggregateOutputType = {
  sortOrder: number | null
}

export type LsuTeamSumAggregateOutputType = {
  sortOrder: number | null
}

export type LsuTeamMinAggregateOutputType = {
  id: string | null
  lsuName: string | null
  technicianName: string | null
  active: boolean | null
  sortOrder: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LsuTeamMaxAggregateOutputType = {
  id: string | null
  lsuName: string | null
  technicianName: string | null
  active: boolean | null
  sortOrder: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LsuTeamCountAggregateOutputType = {
  id: number
  lsuName: number
  technicianName: number
  active: number
  sortOrder: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type LsuTeamAvgAggregateInputType = {
  sortOrder?: true
}

export type LsuTeamSumAggregateInputType = {
  sortOrder?: true
}

export type LsuTeamMinAggregateInputType = {
  id?: true
  lsuName?: true
  technicianName?: true
  active?: true
  sortOrder?: true
  createdAt?: true
  updatedAt?: true
}

export type LsuTeamMaxAggregateInputType = {
  id?: true
  lsuName?: true
  technicianName?: true
  active?: true
  sortOrder?: true
  createdAt?: true
  updatedAt?: true
}

export type LsuTeamCountAggregateInputType = {
  id?: true
  lsuName?: true
  technicianName?: true
  active?: true
  sortOrder?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type LsuTeamAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LsuTeam to aggregate.
   */
  where?: Prisma.LsuTeamWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LsuTeams to fetch.
   */
  orderBy?: Prisma.LsuTeamOrderByWithRelationInput | Prisma.LsuTeamOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LsuTeamWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LsuTeams from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LsuTeams.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LsuTeams
  **/
  _count?: true | LsuTeamCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LsuTeamAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LsuTeamSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LsuTeamMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LsuTeamMaxAggregateInputType
}

export type GetLsuTeamAggregateType<T extends LsuTeamAggregateArgs> = {
      [P in keyof T & keyof AggregateLsuTeam]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLsuTeam[P]>
    : Prisma.GetScalarType<T[P], AggregateLsuTeam[P]>
}




export type LsuTeamGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LsuTeamWhereInput
  orderBy?: Prisma.LsuTeamOrderByWithAggregationInput | Prisma.LsuTeamOrderByWithAggregationInput[]
  by: Prisma.LsuTeamScalarFieldEnum[] | Prisma.LsuTeamScalarFieldEnum
  having?: Prisma.LsuTeamScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LsuTeamCountAggregateInputType | true
  _avg?: LsuTeamAvgAggregateInputType
  _sum?: LsuTeamSumAggregateInputType
  _min?: LsuTeamMinAggregateInputType
  _max?: LsuTeamMaxAggregateInputType
}

export type LsuTeamGroupByOutputType = {
  id: string
  lsuName: string
  technicianName: string
  active: boolean
  sortOrder: number
  createdAt: Date
  updatedAt: Date
  _count: LsuTeamCountAggregateOutputType | null
  _avg: LsuTeamAvgAggregateOutputType | null
  _sum: LsuTeamSumAggregateOutputType | null
  _min: LsuTeamMinAggregateOutputType | null
  _max: LsuTeamMaxAggregateOutputType | null
}

type GetLsuTeamGroupByPayload<T extends LsuTeamGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LsuTeamGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LsuTeamGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LsuTeamGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LsuTeamGroupByOutputType[P]>
      }
    >
  >



export type LsuTeamWhereInput = {
  AND?: Prisma.LsuTeamWhereInput | Prisma.LsuTeamWhereInput[]
  OR?: Prisma.LsuTeamWhereInput[]
  NOT?: Prisma.LsuTeamWhereInput | Prisma.LsuTeamWhereInput[]
  id?: Prisma.StringFilter<"LsuTeam"> | string
  lsuName?: Prisma.StringFilter<"LsuTeam"> | string
  technicianName?: Prisma.StringFilter<"LsuTeam"> | string
  active?: Prisma.BoolFilter<"LsuTeam"> | boolean
  sortOrder?: Prisma.IntFilter<"LsuTeam"> | number
  createdAt?: Prisma.DateTimeFilter<"LsuTeam"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LsuTeam"> | Date | string
}

export type LsuTeamOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  lsuName?: Prisma.SortOrder
  technicianName?: Prisma.SortOrder
  active?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LsuTeamWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  lsuName?: string
  AND?: Prisma.LsuTeamWhereInput | Prisma.LsuTeamWhereInput[]
  OR?: Prisma.LsuTeamWhereInput[]
  NOT?: Prisma.LsuTeamWhereInput | Prisma.LsuTeamWhereInput[]
  technicianName?: Prisma.StringFilter<"LsuTeam"> | string
  active?: Prisma.BoolFilter<"LsuTeam"> | boolean
  sortOrder?: Prisma.IntFilter<"LsuTeam"> | number
  createdAt?: Prisma.DateTimeFilter<"LsuTeam"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LsuTeam"> | Date | string
}, "id" | "lsuName">

export type LsuTeamOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  lsuName?: Prisma.SortOrder
  technicianName?: Prisma.SortOrder
  active?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.LsuTeamCountOrderByAggregateInput
  _avg?: Prisma.LsuTeamAvgOrderByAggregateInput
  _max?: Prisma.LsuTeamMaxOrderByAggregateInput
  _min?: Prisma.LsuTeamMinOrderByAggregateInput
  _sum?: Prisma.LsuTeamSumOrderByAggregateInput
}

export type LsuTeamScalarWhereWithAggregatesInput = {
  AND?: Prisma.LsuTeamScalarWhereWithAggregatesInput | Prisma.LsuTeamScalarWhereWithAggregatesInput[]
  OR?: Prisma.LsuTeamScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LsuTeamScalarWhereWithAggregatesInput | Prisma.LsuTeamScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"LsuTeam"> | string
  lsuName?: Prisma.StringWithAggregatesFilter<"LsuTeam"> | string
  technicianName?: Prisma.StringWithAggregatesFilter<"LsuTeam"> | string
  active?: Prisma.BoolWithAggregatesFilter<"LsuTeam"> | boolean
  sortOrder?: Prisma.IntWithAggregatesFilter<"LsuTeam"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"LsuTeam"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"LsuTeam"> | Date | string
}

export type LsuTeamCreateInput = {
  id?: string
  lsuName: string
  technicianName: string
  active?: boolean
  sortOrder?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LsuTeamUncheckedCreateInput = {
  id?: string
  lsuName: string
  technicianName: string
  active?: boolean
  sortOrder?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LsuTeamUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  lsuName?: Prisma.StringFieldUpdateOperationsInput | string
  technicianName?: Prisma.StringFieldUpdateOperationsInput | string
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LsuTeamUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  lsuName?: Prisma.StringFieldUpdateOperationsInput | string
  technicianName?: Prisma.StringFieldUpdateOperationsInput | string
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LsuTeamCreateManyInput = {
  id?: string
  lsuName: string
  technicianName: string
  active?: boolean
  sortOrder?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LsuTeamUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  lsuName?: Prisma.StringFieldUpdateOperationsInput | string
  technicianName?: Prisma.StringFieldUpdateOperationsInput | string
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LsuTeamUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  lsuName?: Prisma.StringFieldUpdateOperationsInput | string
  technicianName?: Prisma.StringFieldUpdateOperationsInput | string
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LsuTeamCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lsuName?: Prisma.SortOrder
  technicianName?: Prisma.SortOrder
  active?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LsuTeamAvgOrderByAggregateInput = {
  sortOrder?: Prisma.SortOrder
}

export type LsuTeamMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lsuName?: Prisma.SortOrder
  technicianName?: Prisma.SortOrder
  active?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LsuTeamMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lsuName?: Prisma.SortOrder
  technicianName?: Prisma.SortOrder
  active?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LsuTeamSumOrderByAggregateInput = {
  sortOrder?: Prisma.SortOrder
}



export type LsuTeamSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lsuName?: boolean
  technicianName?: boolean
  active?: boolean
  sortOrder?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["lsuTeam"]>

export type LsuTeamSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lsuName?: boolean
  technicianName?: boolean
  active?: boolean
  sortOrder?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["lsuTeam"]>

export type LsuTeamSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lsuName?: boolean
  technicianName?: boolean
  active?: boolean
  sortOrder?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["lsuTeam"]>

export type LsuTeamSelectScalar = {
  id?: boolean
  lsuName?: boolean
  technicianName?: boolean
  active?: boolean
  sortOrder?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type LsuTeamOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "lsuName" | "technicianName" | "active" | "sortOrder" | "createdAt" | "updatedAt", ExtArgs["result"]["lsuTeam"]>

export type $LsuTeamPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LsuTeam"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    lsuName: string
    technicianName: string
    active: boolean
    sortOrder: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["lsuTeam"]>
  composites: {}
}

export type LsuTeamGetPayload<S extends boolean | null | undefined | LsuTeamDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LsuTeamPayload, S>

export type LsuTeamCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LsuTeamFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LsuTeamCountAggregateInputType | true
  }

export interface LsuTeamDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LsuTeam'], meta: { name: 'LsuTeam' } }
  /**
   * Find zero or one LsuTeam that matches the filter.
   * @param {LsuTeamFindUniqueArgs} args - Arguments to find a LsuTeam
   * @example
   * // Get one LsuTeam
   * const lsuTeam = await prisma.lsuTeam.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LsuTeamFindUniqueArgs>(args: Prisma.SelectSubset<T, LsuTeamFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LsuTeamClient<runtime.Types.Result.GetResult<Prisma.$LsuTeamPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LsuTeam that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LsuTeamFindUniqueOrThrowArgs} args - Arguments to find a LsuTeam
   * @example
   * // Get one LsuTeam
   * const lsuTeam = await prisma.lsuTeam.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LsuTeamFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LsuTeamFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LsuTeamClient<runtime.Types.Result.GetResult<Prisma.$LsuTeamPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LsuTeam that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LsuTeamFindFirstArgs} args - Arguments to find a LsuTeam
   * @example
   * // Get one LsuTeam
   * const lsuTeam = await prisma.lsuTeam.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LsuTeamFindFirstArgs>(args?: Prisma.SelectSubset<T, LsuTeamFindFirstArgs<ExtArgs>>): Prisma.Prisma__LsuTeamClient<runtime.Types.Result.GetResult<Prisma.$LsuTeamPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LsuTeam that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LsuTeamFindFirstOrThrowArgs} args - Arguments to find a LsuTeam
   * @example
   * // Get one LsuTeam
   * const lsuTeam = await prisma.lsuTeam.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LsuTeamFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LsuTeamFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LsuTeamClient<runtime.Types.Result.GetResult<Prisma.$LsuTeamPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LsuTeams that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LsuTeamFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LsuTeams
   * const lsuTeams = await prisma.lsuTeam.findMany()
   * 
   * // Get first 10 LsuTeams
   * const lsuTeams = await prisma.lsuTeam.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const lsuTeamWithIdOnly = await prisma.lsuTeam.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LsuTeamFindManyArgs>(args?: Prisma.SelectSubset<T, LsuTeamFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LsuTeamPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LsuTeam.
   * @param {LsuTeamCreateArgs} args - Arguments to create a LsuTeam.
   * @example
   * // Create one LsuTeam
   * const LsuTeam = await prisma.lsuTeam.create({
   *   data: {
   *     // ... data to create a LsuTeam
   *   }
   * })
   * 
   */
  create<T extends LsuTeamCreateArgs>(args: Prisma.SelectSubset<T, LsuTeamCreateArgs<ExtArgs>>): Prisma.Prisma__LsuTeamClient<runtime.Types.Result.GetResult<Prisma.$LsuTeamPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LsuTeams.
   * @param {LsuTeamCreateManyArgs} args - Arguments to create many LsuTeams.
   * @example
   * // Create many LsuTeams
   * const lsuTeam = await prisma.lsuTeam.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LsuTeamCreateManyArgs>(args?: Prisma.SelectSubset<T, LsuTeamCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LsuTeams and returns the data saved in the database.
   * @param {LsuTeamCreateManyAndReturnArgs} args - Arguments to create many LsuTeams.
   * @example
   * // Create many LsuTeams
   * const lsuTeam = await prisma.lsuTeam.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LsuTeams and only return the `id`
   * const lsuTeamWithIdOnly = await prisma.lsuTeam.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LsuTeamCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LsuTeamCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LsuTeamPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LsuTeam.
   * @param {LsuTeamDeleteArgs} args - Arguments to delete one LsuTeam.
   * @example
   * // Delete one LsuTeam
   * const LsuTeam = await prisma.lsuTeam.delete({
   *   where: {
   *     // ... filter to delete one LsuTeam
   *   }
   * })
   * 
   */
  delete<T extends LsuTeamDeleteArgs>(args: Prisma.SelectSubset<T, LsuTeamDeleteArgs<ExtArgs>>): Prisma.Prisma__LsuTeamClient<runtime.Types.Result.GetResult<Prisma.$LsuTeamPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LsuTeam.
   * @param {LsuTeamUpdateArgs} args - Arguments to update one LsuTeam.
   * @example
   * // Update one LsuTeam
   * const lsuTeam = await prisma.lsuTeam.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LsuTeamUpdateArgs>(args: Prisma.SelectSubset<T, LsuTeamUpdateArgs<ExtArgs>>): Prisma.Prisma__LsuTeamClient<runtime.Types.Result.GetResult<Prisma.$LsuTeamPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LsuTeams.
   * @param {LsuTeamDeleteManyArgs} args - Arguments to filter LsuTeams to delete.
   * @example
   * // Delete a few LsuTeams
   * const { count } = await prisma.lsuTeam.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LsuTeamDeleteManyArgs>(args?: Prisma.SelectSubset<T, LsuTeamDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LsuTeams.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LsuTeamUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LsuTeams
   * const lsuTeam = await prisma.lsuTeam.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LsuTeamUpdateManyArgs>(args: Prisma.SelectSubset<T, LsuTeamUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LsuTeams and returns the data updated in the database.
   * @param {LsuTeamUpdateManyAndReturnArgs} args - Arguments to update many LsuTeams.
   * @example
   * // Update many LsuTeams
   * const lsuTeam = await prisma.lsuTeam.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LsuTeams and only return the `id`
   * const lsuTeamWithIdOnly = await prisma.lsuTeam.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LsuTeamUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LsuTeamUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LsuTeamPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LsuTeam.
   * @param {LsuTeamUpsertArgs} args - Arguments to update or create a LsuTeam.
   * @example
   * // Update or create a LsuTeam
   * const lsuTeam = await prisma.lsuTeam.upsert({
   *   create: {
   *     // ... data to create a LsuTeam
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LsuTeam we want to update
   *   }
   * })
   */
  upsert<T extends LsuTeamUpsertArgs>(args: Prisma.SelectSubset<T, LsuTeamUpsertArgs<ExtArgs>>): Prisma.Prisma__LsuTeamClient<runtime.Types.Result.GetResult<Prisma.$LsuTeamPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LsuTeams.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LsuTeamCountArgs} args - Arguments to filter LsuTeams to count.
   * @example
   * // Count the number of LsuTeams
   * const count = await prisma.lsuTeam.count({
   *   where: {
   *     // ... the filter for the LsuTeams we want to count
   *   }
   * })
  **/
  count<T extends LsuTeamCountArgs>(
    args?: Prisma.Subset<T, LsuTeamCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LsuTeamCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LsuTeam.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LsuTeamAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LsuTeamAggregateArgs>(args: Prisma.Subset<T, LsuTeamAggregateArgs>): Prisma.PrismaPromise<GetLsuTeamAggregateType<T>>

  /**
   * Group by LsuTeam.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LsuTeamGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LsuTeamGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LsuTeamGroupByArgs['orderBy'] }
      : { orderBy?: LsuTeamGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LsuTeamGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLsuTeamGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LsuTeam model
 */
readonly fields: LsuTeamFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LsuTeam.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LsuTeamClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LsuTeam model
 */
export interface LsuTeamFieldRefs {
  readonly id: Prisma.FieldRef<"LsuTeam", 'String'>
  readonly lsuName: Prisma.FieldRef<"LsuTeam", 'String'>
  readonly technicianName: Prisma.FieldRef<"LsuTeam", 'String'>
  readonly active: Prisma.FieldRef<"LsuTeam", 'Boolean'>
  readonly sortOrder: Prisma.FieldRef<"LsuTeam", 'Int'>
  readonly createdAt: Prisma.FieldRef<"LsuTeam", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"LsuTeam", 'DateTime'>
}
    

// Custom InputTypes
/**
 * LsuTeam findUnique
 */
export type LsuTeamFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LsuTeam
   */
  select?: Prisma.LsuTeamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LsuTeam
   */
  omit?: Prisma.LsuTeamOmit<ExtArgs> | null
  /**
   * Filter, which LsuTeam to fetch.
   */
  where: Prisma.LsuTeamWhereUniqueInput
}

/**
 * LsuTeam findUniqueOrThrow
 */
export type LsuTeamFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LsuTeam
   */
  select?: Prisma.LsuTeamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LsuTeam
   */
  omit?: Prisma.LsuTeamOmit<ExtArgs> | null
  /**
   * Filter, which LsuTeam to fetch.
   */
  where: Prisma.LsuTeamWhereUniqueInput
}

/**
 * LsuTeam findFirst
 */
export type LsuTeamFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LsuTeam
   */
  select?: Prisma.LsuTeamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LsuTeam
   */
  omit?: Prisma.LsuTeamOmit<ExtArgs> | null
  /**
   * Filter, which LsuTeam to fetch.
   */
  where?: Prisma.LsuTeamWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LsuTeams to fetch.
   */
  orderBy?: Prisma.LsuTeamOrderByWithRelationInput | Prisma.LsuTeamOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LsuTeams.
   */
  cursor?: Prisma.LsuTeamWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LsuTeams from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LsuTeams.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LsuTeams.
   */
  distinct?: Prisma.LsuTeamScalarFieldEnum | Prisma.LsuTeamScalarFieldEnum[]
}

/**
 * LsuTeam findFirstOrThrow
 */
export type LsuTeamFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LsuTeam
   */
  select?: Prisma.LsuTeamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LsuTeam
   */
  omit?: Prisma.LsuTeamOmit<ExtArgs> | null
  /**
   * Filter, which LsuTeam to fetch.
   */
  where?: Prisma.LsuTeamWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LsuTeams to fetch.
   */
  orderBy?: Prisma.LsuTeamOrderByWithRelationInput | Prisma.LsuTeamOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LsuTeams.
   */
  cursor?: Prisma.LsuTeamWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LsuTeams from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LsuTeams.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LsuTeams.
   */
  distinct?: Prisma.LsuTeamScalarFieldEnum | Prisma.LsuTeamScalarFieldEnum[]
}

/**
 * LsuTeam findMany
 */
export type LsuTeamFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LsuTeam
   */
  select?: Prisma.LsuTeamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LsuTeam
   */
  omit?: Prisma.LsuTeamOmit<ExtArgs> | null
  /**
   * Filter, which LsuTeams to fetch.
   */
  where?: Prisma.LsuTeamWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LsuTeams to fetch.
   */
  orderBy?: Prisma.LsuTeamOrderByWithRelationInput | Prisma.LsuTeamOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LsuTeams.
   */
  cursor?: Prisma.LsuTeamWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LsuTeams from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LsuTeams.
   */
  skip?: number
  distinct?: Prisma.LsuTeamScalarFieldEnum | Prisma.LsuTeamScalarFieldEnum[]
}

/**
 * LsuTeam create
 */
export type LsuTeamCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LsuTeam
   */
  select?: Prisma.LsuTeamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LsuTeam
   */
  omit?: Prisma.LsuTeamOmit<ExtArgs> | null
  /**
   * The data needed to create a LsuTeam.
   */
  data: Prisma.XOR<Prisma.LsuTeamCreateInput, Prisma.LsuTeamUncheckedCreateInput>
}

/**
 * LsuTeam createMany
 */
export type LsuTeamCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LsuTeams.
   */
  data: Prisma.LsuTeamCreateManyInput | Prisma.LsuTeamCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LsuTeam createManyAndReturn
 */
export type LsuTeamCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LsuTeam
   */
  select?: Prisma.LsuTeamSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LsuTeam
   */
  omit?: Prisma.LsuTeamOmit<ExtArgs> | null
  /**
   * The data used to create many LsuTeams.
   */
  data: Prisma.LsuTeamCreateManyInput | Prisma.LsuTeamCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LsuTeam update
 */
export type LsuTeamUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LsuTeam
   */
  select?: Prisma.LsuTeamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LsuTeam
   */
  omit?: Prisma.LsuTeamOmit<ExtArgs> | null
  /**
   * The data needed to update a LsuTeam.
   */
  data: Prisma.XOR<Prisma.LsuTeamUpdateInput, Prisma.LsuTeamUncheckedUpdateInput>
  /**
   * Choose, which LsuTeam to update.
   */
  where: Prisma.LsuTeamWhereUniqueInput
}

/**
 * LsuTeam updateMany
 */
export type LsuTeamUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LsuTeams.
   */
  data: Prisma.XOR<Prisma.LsuTeamUpdateManyMutationInput, Prisma.LsuTeamUncheckedUpdateManyInput>
  /**
   * Filter which LsuTeams to update
   */
  where?: Prisma.LsuTeamWhereInput
  /**
   * Limit how many LsuTeams to update.
   */
  limit?: number
}

/**
 * LsuTeam updateManyAndReturn
 */
export type LsuTeamUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LsuTeam
   */
  select?: Prisma.LsuTeamSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LsuTeam
   */
  omit?: Prisma.LsuTeamOmit<ExtArgs> | null
  /**
   * The data used to update LsuTeams.
   */
  data: Prisma.XOR<Prisma.LsuTeamUpdateManyMutationInput, Prisma.LsuTeamUncheckedUpdateManyInput>
  /**
   * Filter which LsuTeams to update
   */
  where?: Prisma.LsuTeamWhereInput
  /**
   * Limit how many LsuTeams to update.
   */
  limit?: number
}

/**
 * LsuTeam upsert
 */
export type LsuTeamUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LsuTeam
   */
  select?: Prisma.LsuTeamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LsuTeam
   */
  omit?: Prisma.LsuTeamOmit<ExtArgs> | null
  /**
   * The filter to search for the LsuTeam to update in case it exists.
   */
  where: Prisma.LsuTeamWhereUniqueInput
  /**
   * In case the LsuTeam found by the `where` argument doesn't exist, create a new LsuTeam with this data.
   */
  create: Prisma.XOR<Prisma.LsuTeamCreateInput, Prisma.LsuTeamUncheckedCreateInput>
  /**
   * In case the LsuTeam was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LsuTeamUpdateInput, Prisma.LsuTeamUncheckedUpdateInput>
}

/**
 * LsuTeam delete
 */
export type LsuTeamDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LsuTeam
   */
  select?: Prisma.LsuTeamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LsuTeam
   */
  omit?: Prisma.LsuTeamOmit<ExtArgs> | null
  /**
   * Filter which LsuTeam to delete.
   */
  where: Prisma.LsuTeamWhereUniqueInput
}

/**
 * LsuTeam deleteMany
 */
export type LsuTeamDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LsuTeams to delete
   */
  where?: Prisma.LsuTeamWhereInput
  /**
   * Limit how many LsuTeams to delete.
   */
  limit?: number
}

/**
 * LsuTeam without action
 */
export type LsuTeamDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LsuTeam
   */
  select?: Prisma.LsuTeamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LsuTeam
   */
  omit?: Prisma.LsuTeamOmit<ExtArgs> | null
}
