
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ShopOrder` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ShopOrder
 * 
 */
export type ShopOrderModel = runtime.Types.Result.DefaultSelection<Prisma.$ShopOrderPayload>

export type AggregateShopOrder = {
  _count: ShopOrderCountAggregateOutputType | null
  _avg: ShopOrderAvgAggregateOutputType | null
  _sum: ShopOrderSumAggregateOutputType | null
  _min: ShopOrderMinAggregateOutputType | null
  _max: ShopOrderMaxAggregateOutputType | null
}

export type ShopOrderAvgAggregateOutputType = {
  subtotal: number | null
}

export type ShopOrderSumAggregateOutputType = {
  subtotal: number | null
}

export type ShopOrderMinAggregateOutputType = {
  id: string | null
  orderNumber: string | null
  customerId: string | null
  status: string | null
  subtotal: number | null
  useKrCredits: boolean | null
  creditsDeducted: boolean | null
  logoRequested: boolean | null
  logoUrl: string | null
  shippingName: string | null
  shippingEmail: string | null
  shippingPhone: string | null
  shippingAddress: string | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
  completedAt: Date | null
}

export type ShopOrderMaxAggregateOutputType = {
  id: string | null
  orderNumber: string | null
  customerId: string | null
  status: string | null
  subtotal: number | null
  useKrCredits: boolean | null
  creditsDeducted: boolean | null
  logoRequested: boolean | null
  logoUrl: string | null
  shippingName: string | null
  shippingEmail: string | null
  shippingPhone: string | null
  shippingAddress: string | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
  completedAt: Date | null
}

export type ShopOrderCountAggregateOutputType = {
  id: number
  orderNumber: number
  customerId: number
  status: number
  subtotal: number
  useKrCredits: number
  creditsDeducted: number
  logoRequested: number
  logoUrl: number
  shippingName: number
  shippingEmail: number
  shippingPhone: number
  shippingAddress: number
  notes: number
  createdAt: number
  updatedAt: number
  completedAt: number
  _all: number
}


export type ShopOrderAvgAggregateInputType = {
  subtotal?: true
}

export type ShopOrderSumAggregateInputType = {
  subtotal?: true
}

export type ShopOrderMinAggregateInputType = {
  id?: true
  orderNumber?: true
  customerId?: true
  status?: true
  subtotal?: true
  useKrCredits?: true
  creditsDeducted?: true
  logoRequested?: true
  logoUrl?: true
  shippingName?: true
  shippingEmail?: true
  shippingPhone?: true
  shippingAddress?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
  completedAt?: true
}

export type ShopOrderMaxAggregateInputType = {
  id?: true
  orderNumber?: true
  customerId?: true
  status?: true
  subtotal?: true
  useKrCredits?: true
  creditsDeducted?: true
  logoRequested?: true
  logoUrl?: true
  shippingName?: true
  shippingEmail?: true
  shippingPhone?: true
  shippingAddress?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
  completedAt?: true
}

export type ShopOrderCountAggregateInputType = {
  id?: true
  orderNumber?: true
  customerId?: true
  status?: true
  subtotal?: true
  useKrCredits?: true
  creditsDeducted?: true
  logoRequested?: true
  logoUrl?: true
  shippingName?: true
  shippingEmail?: true
  shippingPhone?: true
  shippingAddress?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
  completedAt?: true
  _all?: true
}

export type ShopOrderAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ShopOrder to aggregate.
   */
  where?: Prisma.ShopOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShopOrders to fetch.
   */
  orderBy?: Prisma.ShopOrderOrderByWithRelationInput | Prisma.ShopOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ShopOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShopOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShopOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ShopOrders
  **/
  _count?: true | ShopOrderCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ShopOrderAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ShopOrderSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ShopOrderMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ShopOrderMaxAggregateInputType
}

export type GetShopOrderAggregateType<T extends ShopOrderAggregateArgs> = {
      [P in keyof T & keyof AggregateShopOrder]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateShopOrder[P]>
    : Prisma.GetScalarType<T[P], AggregateShopOrder[P]>
}




export type ShopOrderGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ShopOrderWhereInput
  orderBy?: Prisma.ShopOrderOrderByWithAggregationInput | Prisma.ShopOrderOrderByWithAggregationInput[]
  by: Prisma.ShopOrderScalarFieldEnum[] | Prisma.ShopOrderScalarFieldEnum
  having?: Prisma.ShopOrderScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ShopOrderCountAggregateInputType | true
  _avg?: ShopOrderAvgAggregateInputType
  _sum?: ShopOrderSumAggregateInputType
  _min?: ShopOrderMinAggregateInputType
  _max?: ShopOrderMaxAggregateInputType
}

export type ShopOrderGroupByOutputType = {
  id: string
  orderNumber: string
  customerId: string
  status: string
  subtotal: number
  useKrCredits: boolean
  creditsDeducted: boolean
  logoRequested: boolean
  logoUrl: string | null
  shippingName: string | null
  shippingEmail: string | null
  shippingPhone: string | null
  shippingAddress: string | null
  notes: string | null
  createdAt: Date
  updatedAt: Date
  completedAt: Date | null
  _count: ShopOrderCountAggregateOutputType | null
  _avg: ShopOrderAvgAggregateOutputType | null
  _sum: ShopOrderSumAggregateOutputType | null
  _min: ShopOrderMinAggregateOutputType | null
  _max: ShopOrderMaxAggregateOutputType | null
}

type GetShopOrderGroupByPayload<T extends ShopOrderGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ShopOrderGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ShopOrderGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ShopOrderGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ShopOrderGroupByOutputType[P]>
      }
    >
  >



export type ShopOrderWhereInput = {
  AND?: Prisma.ShopOrderWhereInput | Prisma.ShopOrderWhereInput[]
  OR?: Prisma.ShopOrderWhereInput[]
  NOT?: Prisma.ShopOrderWhereInput | Prisma.ShopOrderWhereInput[]
  id?: Prisma.StringFilter<"ShopOrder"> | string
  orderNumber?: Prisma.StringFilter<"ShopOrder"> | string
  customerId?: Prisma.StringFilter<"ShopOrder"> | string
  status?: Prisma.StringFilter<"ShopOrder"> | string
  subtotal?: Prisma.FloatFilter<"ShopOrder"> | number
  useKrCredits?: Prisma.BoolFilter<"ShopOrder"> | boolean
  creditsDeducted?: Prisma.BoolFilter<"ShopOrder"> | boolean
  logoRequested?: Prisma.BoolFilter<"ShopOrder"> | boolean
  logoUrl?: Prisma.StringNullableFilter<"ShopOrder"> | string | null
  shippingName?: Prisma.StringNullableFilter<"ShopOrder"> | string | null
  shippingEmail?: Prisma.StringNullableFilter<"ShopOrder"> | string | null
  shippingPhone?: Prisma.StringNullableFilter<"ShopOrder"> | string | null
  shippingAddress?: Prisma.StringNullableFilter<"ShopOrder"> | string | null
  notes?: Prisma.StringNullableFilter<"ShopOrder"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ShopOrder"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ShopOrder"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"ShopOrder"> | Date | string | null
  customer?: Prisma.XOR<Prisma.CustomerScalarRelationFilter, Prisma.CustomerWhereInput>
  items?: Prisma.OrderItemListRelationFilter
}

export type ShopOrderOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  orderNumber?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  useKrCredits?: Prisma.SortOrder
  creditsDeducted?: Prisma.SortOrder
  logoRequested?: Prisma.SortOrder
  logoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  shippingName?: Prisma.SortOrderInput | Prisma.SortOrder
  shippingEmail?: Prisma.SortOrderInput | Prisma.SortOrder
  shippingPhone?: Prisma.SortOrderInput | Prisma.SortOrder
  shippingAddress?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  customer?: Prisma.CustomerOrderByWithRelationInput
  items?: Prisma.OrderItemOrderByRelationAggregateInput
}

export type ShopOrderWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  orderNumber?: string
  AND?: Prisma.ShopOrderWhereInput | Prisma.ShopOrderWhereInput[]
  OR?: Prisma.ShopOrderWhereInput[]
  NOT?: Prisma.ShopOrderWhereInput | Prisma.ShopOrderWhereInput[]
  customerId?: Prisma.StringFilter<"ShopOrder"> | string
  status?: Prisma.StringFilter<"ShopOrder"> | string
  subtotal?: Prisma.FloatFilter<"ShopOrder"> | number
  useKrCredits?: Prisma.BoolFilter<"ShopOrder"> | boolean
  creditsDeducted?: Prisma.BoolFilter<"ShopOrder"> | boolean
  logoRequested?: Prisma.BoolFilter<"ShopOrder"> | boolean
  logoUrl?: Prisma.StringNullableFilter<"ShopOrder"> | string | null
  shippingName?: Prisma.StringNullableFilter<"ShopOrder"> | string | null
  shippingEmail?: Prisma.StringNullableFilter<"ShopOrder"> | string | null
  shippingPhone?: Prisma.StringNullableFilter<"ShopOrder"> | string | null
  shippingAddress?: Prisma.StringNullableFilter<"ShopOrder"> | string | null
  notes?: Prisma.StringNullableFilter<"ShopOrder"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ShopOrder"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ShopOrder"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"ShopOrder"> | Date | string | null
  customer?: Prisma.XOR<Prisma.CustomerScalarRelationFilter, Prisma.CustomerWhereInput>
  items?: Prisma.OrderItemListRelationFilter
}, "id" | "orderNumber">

export type ShopOrderOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  orderNumber?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  useKrCredits?: Prisma.SortOrder
  creditsDeducted?: Prisma.SortOrder
  logoRequested?: Prisma.SortOrder
  logoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  shippingName?: Prisma.SortOrderInput | Prisma.SortOrder
  shippingEmail?: Prisma.SortOrderInput | Prisma.SortOrder
  shippingPhone?: Prisma.SortOrderInput | Prisma.SortOrder
  shippingAddress?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ShopOrderCountOrderByAggregateInput
  _avg?: Prisma.ShopOrderAvgOrderByAggregateInput
  _max?: Prisma.ShopOrderMaxOrderByAggregateInput
  _min?: Prisma.ShopOrderMinOrderByAggregateInput
  _sum?: Prisma.ShopOrderSumOrderByAggregateInput
}

export type ShopOrderScalarWhereWithAggregatesInput = {
  AND?: Prisma.ShopOrderScalarWhereWithAggregatesInput | Prisma.ShopOrderScalarWhereWithAggregatesInput[]
  OR?: Prisma.ShopOrderScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ShopOrderScalarWhereWithAggregatesInput | Prisma.ShopOrderScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ShopOrder"> | string
  orderNumber?: Prisma.StringWithAggregatesFilter<"ShopOrder"> | string
  customerId?: Prisma.StringWithAggregatesFilter<"ShopOrder"> | string
  status?: Prisma.StringWithAggregatesFilter<"ShopOrder"> | string
  subtotal?: Prisma.FloatWithAggregatesFilter<"ShopOrder"> | number
  useKrCredits?: Prisma.BoolWithAggregatesFilter<"ShopOrder"> | boolean
  creditsDeducted?: Prisma.BoolWithAggregatesFilter<"ShopOrder"> | boolean
  logoRequested?: Prisma.BoolWithAggregatesFilter<"ShopOrder"> | boolean
  logoUrl?: Prisma.StringNullableWithAggregatesFilter<"ShopOrder"> | string | null
  shippingName?: Prisma.StringNullableWithAggregatesFilter<"ShopOrder"> | string | null
  shippingEmail?: Prisma.StringNullableWithAggregatesFilter<"ShopOrder"> | string | null
  shippingPhone?: Prisma.StringNullableWithAggregatesFilter<"ShopOrder"> | string | null
  shippingAddress?: Prisma.StringNullableWithAggregatesFilter<"ShopOrder"> | string | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"ShopOrder"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ShopOrder"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ShopOrder"> | Date | string
  completedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ShopOrder"> | Date | string | null
}

export type ShopOrderCreateInput = {
  id?: string
  orderNumber: string
  status?: string
  subtotal: number
  useKrCredits?: boolean
  creditsDeducted?: boolean
  logoRequested?: boolean
  logoUrl?: string | null
  shippingName?: string | null
  shippingEmail?: string | null
  shippingPhone?: string | null
  shippingAddress?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
  customer: Prisma.CustomerCreateNestedOneWithoutShopOrdersInput
  items?: Prisma.OrderItemCreateNestedManyWithoutOrderInput
}

export type ShopOrderUncheckedCreateInput = {
  id?: string
  orderNumber: string
  customerId: string
  status?: string
  subtotal: number
  useKrCredits?: boolean
  creditsDeducted?: boolean
  logoRequested?: boolean
  logoUrl?: string | null
  shippingName?: string | null
  shippingEmail?: string | null
  shippingPhone?: string | null
  shippingAddress?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
  items?: Prisma.OrderItemUncheckedCreateNestedManyWithoutOrderInput
}

export type ShopOrderUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderNumber?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  subtotal?: Prisma.FloatFieldUpdateOperationsInput | number
  useKrCredits?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creditsDeducted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logoRequested?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customer?: Prisma.CustomerUpdateOneRequiredWithoutShopOrdersNestedInput
  items?: Prisma.OrderItemUpdateManyWithoutOrderNestedInput
}

export type ShopOrderUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderNumber?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  subtotal?: Prisma.FloatFieldUpdateOperationsInput | number
  useKrCredits?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creditsDeducted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logoRequested?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  items?: Prisma.OrderItemUncheckedUpdateManyWithoutOrderNestedInput
}

export type ShopOrderCreateManyInput = {
  id?: string
  orderNumber: string
  customerId: string
  status?: string
  subtotal: number
  useKrCredits?: boolean
  creditsDeducted?: boolean
  logoRequested?: boolean
  logoUrl?: string | null
  shippingName?: string | null
  shippingEmail?: string | null
  shippingPhone?: string | null
  shippingAddress?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
}

export type ShopOrderUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderNumber?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  subtotal?: Prisma.FloatFieldUpdateOperationsInput | number
  useKrCredits?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creditsDeducted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logoRequested?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ShopOrderUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderNumber?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  subtotal?: Prisma.FloatFieldUpdateOperationsInput | number
  useKrCredits?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creditsDeducted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logoRequested?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ShopOrderListRelationFilter = {
  every?: Prisma.ShopOrderWhereInput
  some?: Prisma.ShopOrderWhereInput
  none?: Prisma.ShopOrderWhereInput
}

export type ShopOrderOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ShopOrderCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderNumber?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  useKrCredits?: Prisma.SortOrder
  creditsDeducted?: Prisma.SortOrder
  logoRequested?: Prisma.SortOrder
  logoUrl?: Prisma.SortOrder
  shippingName?: Prisma.SortOrder
  shippingEmail?: Prisma.SortOrder
  shippingPhone?: Prisma.SortOrder
  shippingAddress?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type ShopOrderAvgOrderByAggregateInput = {
  subtotal?: Prisma.SortOrder
}

export type ShopOrderMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderNumber?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  useKrCredits?: Prisma.SortOrder
  creditsDeducted?: Prisma.SortOrder
  logoRequested?: Prisma.SortOrder
  logoUrl?: Prisma.SortOrder
  shippingName?: Prisma.SortOrder
  shippingEmail?: Prisma.SortOrder
  shippingPhone?: Prisma.SortOrder
  shippingAddress?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type ShopOrderMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderNumber?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  useKrCredits?: Prisma.SortOrder
  creditsDeducted?: Prisma.SortOrder
  logoRequested?: Prisma.SortOrder
  logoUrl?: Prisma.SortOrder
  shippingName?: Prisma.SortOrder
  shippingEmail?: Prisma.SortOrder
  shippingPhone?: Prisma.SortOrder
  shippingAddress?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type ShopOrderSumOrderByAggregateInput = {
  subtotal?: Prisma.SortOrder
}

export type ShopOrderScalarRelationFilter = {
  is?: Prisma.ShopOrderWhereInput
  isNot?: Prisma.ShopOrderWhereInput
}

export type ShopOrderCreateNestedManyWithoutCustomerInput = {
  create?: Prisma.XOR<Prisma.ShopOrderCreateWithoutCustomerInput, Prisma.ShopOrderUncheckedCreateWithoutCustomerInput> | Prisma.ShopOrderCreateWithoutCustomerInput[] | Prisma.ShopOrderUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.ShopOrderCreateOrConnectWithoutCustomerInput | Prisma.ShopOrderCreateOrConnectWithoutCustomerInput[]
  createMany?: Prisma.ShopOrderCreateManyCustomerInputEnvelope
  connect?: Prisma.ShopOrderWhereUniqueInput | Prisma.ShopOrderWhereUniqueInput[]
}

export type ShopOrderUncheckedCreateNestedManyWithoutCustomerInput = {
  create?: Prisma.XOR<Prisma.ShopOrderCreateWithoutCustomerInput, Prisma.ShopOrderUncheckedCreateWithoutCustomerInput> | Prisma.ShopOrderCreateWithoutCustomerInput[] | Prisma.ShopOrderUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.ShopOrderCreateOrConnectWithoutCustomerInput | Prisma.ShopOrderCreateOrConnectWithoutCustomerInput[]
  createMany?: Prisma.ShopOrderCreateManyCustomerInputEnvelope
  connect?: Prisma.ShopOrderWhereUniqueInput | Prisma.ShopOrderWhereUniqueInput[]
}

export type ShopOrderUpdateManyWithoutCustomerNestedInput = {
  create?: Prisma.XOR<Prisma.ShopOrderCreateWithoutCustomerInput, Prisma.ShopOrderUncheckedCreateWithoutCustomerInput> | Prisma.ShopOrderCreateWithoutCustomerInput[] | Prisma.ShopOrderUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.ShopOrderCreateOrConnectWithoutCustomerInput | Prisma.ShopOrderCreateOrConnectWithoutCustomerInput[]
  upsert?: Prisma.ShopOrderUpsertWithWhereUniqueWithoutCustomerInput | Prisma.ShopOrderUpsertWithWhereUniqueWithoutCustomerInput[]
  createMany?: Prisma.ShopOrderCreateManyCustomerInputEnvelope
  set?: Prisma.ShopOrderWhereUniqueInput | Prisma.ShopOrderWhereUniqueInput[]
  disconnect?: Prisma.ShopOrderWhereUniqueInput | Prisma.ShopOrderWhereUniqueInput[]
  delete?: Prisma.ShopOrderWhereUniqueInput | Prisma.ShopOrderWhereUniqueInput[]
  connect?: Prisma.ShopOrderWhereUniqueInput | Prisma.ShopOrderWhereUniqueInput[]
  update?: Prisma.ShopOrderUpdateWithWhereUniqueWithoutCustomerInput | Prisma.ShopOrderUpdateWithWhereUniqueWithoutCustomerInput[]
  updateMany?: Prisma.ShopOrderUpdateManyWithWhereWithoutCustomerInput | Prisma.ShopOrderUpdateManyWithWhereWithoutCustomerInput[]
  deleteMany?: Prisma.ShopOrderScalarWhereInput | Prisma.ShopOrderScalarWhereInput[]
}

export type ShopOrderUncheckedUpdateManyWithoutCustomerNestedInput = {
  create?: Prisma.XOR<Prisma.ShopOrderCreateWithoutCustomerInput, Prisma.ShopOrderUncheckedCreateWithoutCustomerInput> | Prisma.ShopOrderCreateWithoutCustomerInput[] | Prisma.ShopOrderUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.ShopOrderCreateOrConnectWithoutCustomerInput | Prisma.ShopOrderCreateOrConnectWithoutCustomerInput[]
  upsert?: Prisma.ShopOrderUpsertWithWhereUniqueWithoutCustomerInput | Prisma.ShopOrderUpsertWithWhereUniqueWithoutCustomerInput[]
  createMany?: Prisma.ShopOrderCreateManyCustomerInputEnvelope
  set?: Prisma.ShopOrderWhereUniqueInput | Prisma.ShopOrderWhereUniqueInput[]
  disconnect?: Prisma.ShopOrderWhereUniqueInput | Prisma.ShopOrderWhereUniqueInput[]
  delete?: Prisma.ShopOrderWhereUniqueInput | Prisma.ShopOrderWhereUniqueInput[]
  connect?: Prisma.ShopOrderWhereUniqueInput | Prisma.ShopOrderWhereUniqueInput[]
  update?: Prisma.ShopOrderUpdateWithWhereUniqueWithoutCustomerInput | Prisma.ShopOrderUpdateWithWhereUniqueWithoutCustomerInput[]
  updateMany?: Prisma.ShopOrderUpdateManyWithWhereWithoutCustomerInput | Prisma.ShopOrderUpdateManyWithWhereWithoutCustomerInput[]
  deleteMany?: Prisma.ShopOrderScalarWhereInput | Prisma.ShopOrderScalarWhereInput[]
}

export type ShopOrderCreateNestedOneWithoutItemsInput = {
  create?: Prisma.XOR<Prisma.ShopOrderCreateWithoutItemsInput, Prisma.ShopOrderUncheckedCreateWithoutItemsInput>
  connectOrCreate?: Prisma.ShopOrderCreateOrConnectWithoutItemsInput
  connect?: Prisma.ShopOrderWhereUniqueInput
}

export type ShopOrderUpdateOneRequiredWithoutItemsNestedInput = {
  create?: Prisma.XOR<Prisma.ShopOrderCreateWithoutItemsInput, Prisma.ShopOrderUncheckedCreateWithoutItemsInput>
  connectOrCreate?: Prisma.ShopOrderCreateOrConnectWithoutItemsInput
  upsert?: Prisma.ShopOrderUpsertWithoutItemsInput
  connect?: Prisma.ShopOrderWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ShopOrderUpdateToOneWithWhereWithoutItemsInput, Prisma.ShopOrderUpdateWithoutItemsInput>, Prisma.ShopOrderUncheckedUpdateWithoutItemsInput>
}

export type ShopOrderCreateWithoutCustomerInput = {
  id?: string
  orderNumber: string
  status?: string
  subtotal: number
  useKrCredits?: boolean
  creditsDeducted?: boolean
  logoRequested?: boolean
  logoUrl?: string | null
  shippingName?: string | null
  shippingEmail?: string | null
  shippingPhone?: string | null
  shippingAddress?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
  items?: Prisma.OrderItemCreateNestedManyWithoutOrderInput
}

export type ShopOrderUncheckedCreateWithoutCustomerInput = {
  id?: string
  orderNumber: string
  status?: string
  subtotal: number
  useKrCredits?: boolean
  creditsDeducted?: boolean
  logoRequested?: boolean
  logoUrl?: string | null
  shippingName?: string | null
  shippingEmail?: string | null
  shippingPhone?: string | null
  shippingAddress?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
  items?: Prisma.OrderItemUncheckedCreateNestedManyWithoutOrderInput
}

export type ShopOrderCreateOrConnectWithoutCustomerInput = {
  where: Prisma.ShopOrderWhereUniqueInput
  create: Prisma.XOR<Prisma.ShopOrderCreateWithoutCustomerInput, Prisma.ShopOrderUncheckedCreateWithoutCustomerInput>
}

export type ShopOrderCreateManyCustomerInputEnvelope = {
  data: Prisma.ShopOrderCreateManyCustomerInput | Prisma.ShopOrderCreateManyCustomerInput[]
  skipDuplicates?: boolean
}

export type ShopOrderUpsertWithWhereUniqueWithoutCustomerInput = {
  where: Prisma.ShopOrderWhereUniqueInput
  update: Prisma.XOR<Prisma.ShopOrderUpdateWithoutCustomerInput, Prisma.ShopOrderUncheckedUpdateWithoutCustomerInput>
  create: Prisma.XOR<Prisma.ShopOrderCreateWithoutCustomerInput, Prisma.ShopOrderUncheckedCreateWithoutCustomerInput>
}

export type ShopOrderUpdateWithWhereUniqueWithoutCustomerInput = {
  where: Prisma.ShopOrderWhereUniqueInput
  data: Prisma.XOR<Prisma.ShopOrderUpdateWithoutCustomerInput, Prisma.ShopOrderUncheckedUpdateWithoutCustomerInput>
}

export type ShopOrderUpdateManyWithWhereWithoutCustomerInput = {
  where: Prisma.ShopOrderScalarWhereInput
  data: Prisma.XOR<Prisma.ShopOrderUpdateManyMutationInput, Prisma.ShopOrderUncheckedUpdateManyWithoutCustomerInput>
}

export type ShopOrderScalarWhereInput = {
  AND?: Prisma.ShopOrderScalarWhereInput | Prisma.ShopOrderScalarWhereInput[]
  OR?: Prisma.ShopOrderScalarWhereInput[]
  NOT?: Prisma.ShopOrderScalarWhereInput | Prisma.ShopOrderScalarWhereInput[]
  id?: Prisma.StringFilter<"ShopOrder"> | string
  orderNumber?: Prisma.StringFilter<"ShopOrder"> | string
  customerId?: Prisma.StringFilter<"ShopOrder"> | string
  status?: Prisma.StringFilter<"ShopOrder"> | string
  subtotal?: Prisma.FloatFilter<"ShopOrder"> | number
  useKrCredits?: Prisma.BoolFilter<"ShopOrder"> | boolean
  creditsDeducted?: Prisma.BoolFilter<"ShopOrder"> | boolean
  logoRequested?: Prisma.BoolFilter<"ShopOrder"> | boolean
  logoUrl?: Prisma.StringNullableFilter<"ShopOrder"> | string | null
  shippingName?: Prisma.StringNullableFilter<"ShopOrder"> | string | null
  shippingEmail?: Prisma.StringNullableFilter<"ShopOrder"> | string | null
  shippingPhone?: Prisma.StringNullableFilter<"ShopOrder"> | string | null
  shippingAddress?: Prisma.StringNullableFilter<"ShopOrder"> | string | null
  notes?: Prisma.StringNullableFilter<"ShopOrder"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ShopOrder"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ShopOrder"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"ShopOrder"> | Date | string | null
}

export type ShopOrderCreateWithoutItemsInput = {
  id?: string
  orderNumber: string
  status?: string
  subtotal: number
  useKrCredits?: boolean
  creditsDeducted?: boolean
  logoRequested?: boolean
  logoUrl?: string | null
  shippingName?: string | null
  shippingEmail?: string | null
  shippingPhone?: string | null
  shippingAddress?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
  customer: Prisma.CustomerCreateNestedOneWithoutShopOrdersInput
}

export type ShopOrderUncheckedCreateWithoutItemsInput = {
  id?: string
  orderNumber: string
  customerId: string
  status?: string
  subtotal: number
  useKrCredits?: boolean
  creditsDeducted?: boolean
  logoRequested?: boolean
  logoUrl?: string | null
  shippingName?: string | null
  shippingEmail?: string | null
  shippingPhone?: string | null
  shippingAddress?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
}

export type ShopOrderCreateOrConnectWithoutItemsInput = {
  where: Prisma.ShopOrderWhereUniqueInput
  create: Prisma.XOR<Prisma.ShopOrderCreateWithoutItemsInput, Prisma.ShopOrderUncheckedCreateWithoutItemsInput>
}

export type ShopOrderUpsertWithoutItemsInput = {
  update: Prisma.XOR<Prisma.ShopOrderUpdateWithoutItemsInput, Prisma.ShopOrderUncheckedUpdateWithoutItemsInput>
  create: Prisma.XOR<Prisma.ShopOrderCreateWithoutItemsInput, Prisma.ShopOrderUncheckedCreateWithoutItemsInput>
  where?: Prisma.ShopOrderWhereInput
}

export type ShopOrderUpdateToOneWithWhereWithoutItemsInput = {
  where?: Prisma.ShopOrderWhereInput
  data: Prisma.XOR<Prisma.ShopOrderUpdateWithoutItemsInput, Prisma.ShopOrderUncheckedUpdateWithoutItemsInput>
}

export type ShopOrderUpdateWithoutItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderNumber?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  subtotal?: Prisma.FloatFieldUpdateOperationsInput | number
  useKrCredits?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creditsDeducted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logoRequested?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customer?: Prisma.CustomerUpdateOneRequiredWithoutShopOrdersNestedInput
}

export type ShopOrderUncheckedUpdateWithoutItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderNumber?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  subtotal?: Prisma.FloatFieldUpdateOperationsInput | number
  useKrCredits?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creditsDeducted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logoRequested?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ShopOrderCreateManyCustomerInput = {
  id?: string
  orderNumber: string
  status?: string
  subtotal: number
  useKrCredits?: boolean
  creditsDeducted?: boolean
  logoRequested?: boolean
  logoUrl?: string | null
  shippingName?: string | null
  shippingEmail?: string | null
  shippingPhone?: string | null
  shippingAddress?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  completedAt?: Date | string | null
}

export type ShopOrderUpdateWithoutCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderNumber?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  subtotal?: Prisma.FloatFieldUpdateOperationsInput | number
  useKrCredits?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creditsDeducted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logoRequested?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  items?: Prisma.OrderItemUpdateManyWithoutOrderNestedInput
}

export type ShopOrderUncheckedUpdateWithoutCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderNumber?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  subtotal?: Prisma.FloatFieldUpdateOperationsInput | number
  useKrCredits?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creditsDeducted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logoRequested?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  items?: Prisma.OrderItemUncheckedUpdateManyWithoutOrderNestedInput
}

export type ShopOrderUncheckedUpdateManyWithoutCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderNumber?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  subtotal?: Prisma.FloatFieldUpdateOperationsInput | number
  useKrCredits?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creditsDeducted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logoRequested?: Prisma.BoolFieldUpdateOperationsInput | boolean
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shippingAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type ShopOrderCountOutputType
 */

export type ShopOrderCountOutputType = {
  items: number
}

export type ShopOrderCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  items?: boolean | ShopOrderCountOutputTypeCountItemsArgs
}

/**
 * ShopOrderCountOutputType without action
 */
export type ShopOrderCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopOrderCountOutputType
   */
  select?: Prisma.ShopOrderCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ShopOrderCountOutputType without action
 */
export type ShopOrderCountOutputTypeCountItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderItemWhereInput
}


export type ShopOrderSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orderNumber?: boolean
  customerId?: boolean
  status?: boolean
  subtotal?: boolean
  useKrCredits?: boolean
  creditsDeducted?: boolean
  logoRequested?: boolean
  logoUrl?: boolean
  shippingName?: boolean
  shippingEmail?: boolean
  shippingPhone?: boolean
  shippingAddress?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  completedAt?: boolean
  customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
  items?: boolean | Prisma.ShopOrder$itemsArgs<ExtArgs>
  _count?: boolean | Prisma.ShopOrderCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["shopOrder"]>

export type ShopOrderSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orderNumber?: boolean
  customerId?: boolean
  status?: boolean
  subtotal?: boolean
  useKrCredits?: boolean
  creditsDeducted?: boolean
  logoRequested?: boolean
  logoUrl?: boolean
  shippingName?: boolean
  shippingEmail?: boolean
  shippingPhone?: boolean
  shippingAddress?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  completedAt?: boolean
  customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["shopOrder"]>

export type ShopOrderSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orderNumber?: boolean
  customerId?: boolean
  status?: boolean
  subtotal?: boolean
  useKrCredits?: boolean
  creditsDeducted?: boolean
  logoRequested?: boolean
  logoUrl?: boolean
  shippingName?: boolean
  shippingEmail?: boolean
  shippingPhone?: boolean
  shippingAddress?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  completedAt?: boolean
  customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["shopOrder"]>

export type ShopOrderSelectScalar = {
  id?: boolean
  orderNumber?: boolean
  customerId?: boolean
  status?: boolean
  subtotal?: boolean
  useKrCredits?: boolean
  creditsDeducted?: boolean
  logoRequested?: boolean
  logoUrl?: boolean
  shippingName?: boolean
  shippingEmail?: boolean
  shippingPhone?: boolean
  shippingAddress?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  completedAt?: boolean
}

export type ShopOrderOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "orderNumber" | "customerId" | "status" | "subtotal" | "useKrCredits" | "creditsDeducted" | "logoRequested" | "logoUrl" | "shippingName" | "shippingEmail" | "shippingPhone" | "shippingAddress" | "notes" | "createdAt" | "updatedAt" | "completedAt", ExtArgs["result"]["shopOrder"]>
export type ShopOrderInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
  items?: boolean | Prisma.ShopOrder$itemsArgs<ExtArgs>
  _count?: boolean | Prisma.ShopOrderCountOutputTypeDefaultArgs<ExtArgs>
}
export type ShopOrderIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
}
export type ShopOrderIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
}

export type $ShopOrderPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ShopOrder"
  objects: {
    customer: Prisma.$CustomerPayload<ExtArgs>
    items: Prisma.$OrderItemPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    orderNumber: string
    customerId: string
    status: string
    subtotal: number
    useKrCredits: boolean
    creditsDeducted: boolean
    logoRequested: boolean
    logoUrl: string | null
    shippingName: string | null
    shippingEmail: string | null
    shippingPhone: string | null
    shippingAddress: string | null
    notes: string | null
    createdAt: Date
    updatedAt: Date
    completedAt: Date | null
  }, ExtArgs["result"]["shopOrder"]>
  composites: {}
}

export type ShopOrderGetPayload<S extends boolean | null | undefined | ShopOrderDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ShopOrderPayload, S>

export type ShopOrderCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ShopOrderFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ShopOrderCountAggregateInputType | true
  }

export interface ShopOrderDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ShopOrder'], meta: { name: 'ShopOrder' } }
  /**
   * Find zero or one ShopOrder that matches the filter.
   * @param {ShopOrderFindUniqueArgs} args - Arguments to find a ShopOrder
   * @example
   * // Get one ShopOrder
   * const shopOrder = await prisma.shopOrder.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ShopOrderFindUniqueArgs>(args: Prisma.SelectSubset<T, ShopOrderFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ShopOrderClient<runtime.Types.Result.GetResult<Prisma.$ShopOrderPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ShopOrder that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ShopOrderFindUniqueOrThrowArgs} args - Arguments to find a ShopOrder
   * @example
   * // Get one ShopOrder
   * const shopOrder = await prisma.shopOrder.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ShopOrderFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ShopOrderFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ShopOrderClient<runtime.Types.Result.GetResult<Prisma.$ShopOrderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ShopOrder that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShopOrderFindFirstArgs} args - Arguments to find a ShopOrder
   * @example
   * // Get one ShopOrder
   * const shopOrder = await prisma.shopOrder.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ShopOrderFindFirstArgs>(args?: Prisma.SelectSubset<T, ShopOrderFindFirstArgs<ExtArgs>>): Prisma.Prisma__ShopOrderClient<runtime.Types.Result.GetResult<Prisma.$ShopOrderPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ShopOrder that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShopOrderFindFirstOrThrowArgs} args - Arguments to find a ShopOrder
   * @example
   * // Get one ShopOrder
   * const shopOrder = await prisma.shopOrder.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ShopOrderFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ShopOrderFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ShopOrderClient<runtime.Types.Result.GetResult<Prisma.$ShopOrderPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ShopOrders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShopOrderFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ShopOrders
   * const shopOrders = await prisma.shopOrder.findMany()
   * 
   * // Get first 10 ShopOrders
   * const shopOrders = await prisma.shopOrder.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const shopOrderWithIdOnly = await prisma.shopOrder.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ShopOrderFindManyArgs>(args?: Prisma.SelectSubset<T, ShopOrderFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShopOrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ShopOrder.
   * @param {ShopOrderCreateArgs} args - Arguments to create a ShopOrder.
   * @example
   * // Create one ShopOrder
   * const ShopOrder = await prisma.shopOrder.create({
   *   data: {
   *     // ... data to create a ShopOrder
   *   }
   * })
   * 
   */
  create<T extends ShopOrderCreateArgs>(args: Prisma.SelectSubset<T, ShopOrderCreateArgs<ExtArgs>>): Prisma.Prisma__ShopOrderClient<runtime.Types.Result.GetResult<Prisma.$ShopOrderPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ShopOrders.
   * @param {ShopOrderCreateManyArgs} args - Arguments to create many ShopOrders.
   * @example
   * // Create many ShopOrders
   * const shopOrder = await prisma.shopOrder.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ShopOrderCreateManyArgs>(args?: Prisma.SelectSubset<T, ShopOrderCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ShopOrders and returns the data saved in the database.
   * @param {ShopOrderCreateManyAndReturnArgs} args - Arguments to create many ShopOrders.
   * @example
   * // Create many ShopOrders
   * const shopOrder = await prisma.shopOrder.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ShopOrders and only return the `id`
   * const shopOrderWithIdOnly = await prisma.shopOrder.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ShopOrderCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ShopOrderCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShopOrderPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ShopOrder.
   * @param {ShopOrderDeleteArgs} args - Arguments to delete one ShopOrder.
   * @example
   * // Delete one ShopOrder
   * const ShopOrder = await prisma.shopOrder.delete({
   *   where: {
   *     // ... filter to delete one ShopOrder
   *   }
   * })
   * 
   */
  delete<T extends ShopOrderDeleteArgs>(args: Prisma.SelectSubset<T, ShopOrderDeleteArgs<ExtArgs>>): Prisma.Prisma__ShopOrderClient<runtime.Types.Result.GetResult<Prisma.$ShopOrderPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ShopOrder.
   * @param {ShopOrderUpdateArgs} args - Arguments to update one ShopOrder.
   * @example
   * // Update one ShopOrder
   * const shopOrder = await prisma.shopOrder.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ShopOrderUpdateArgs>(args: Prisma.SelectSubset<T, ShopOrderUpdateArgs<ExtArgs>>): Prisma.Prisma__ShopOrderClient<runtime.Types.Result.GetResult<Prisma.$ShopOrderPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ShopOrders.
   * @param {ShopOrderDeleteManyArgs} args - Arguments to filter ShopOrders to delete.
   * @example
   * // Delete a few ShopOrders
   * const { count } = await prisma.shopOrder.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ShopOrderDeleteManyArgs>(args?: Prisma.SelectSubset<T, ShopOrderDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ShopOrders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShopOrderUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ShopOrders
   * const shopOrder = await prisma.shopOrder.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ShopOrderUpdateManyArgs>(args: Prisma.SelectSubset<T, ShopOrderUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ShopOrders and returns the data updated in the database.
   * @param {ShopOrderUpdateManyAndReturnArgs} args - Arguments to update many ShopOrders.
   * @example
   * // Update many ShopOrders
   * const shopOrder = await prisma.shopOrder.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ShopOrders and only return the `id`
   * const shopOrderWithIdOnly = await prisma.shopOrder.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ShopOrderUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ShopOrderUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShopOrderPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ShopOrder.
   * @param {ShopOrderUpsertArgs} args - Arguments to update or create a ShopOrder.
   * @example
   * // Update or create a ShopOrder
   * const shopOrder = await prisma.shopOrder.upsert({
   *   create: {
   *     // ... data to create a ShopOrder
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ShopOrder we want to update
   *   }
   * })
   */
  upsert<T extends ShopOrderUpsertArgs>(args: Prisma.SelectSubset<T, ShopOrderUpsertArgs<ExtArgs>>): Prisma.Prisma__ShopOrderClient<runtime.Types.Result.GetResult<Prisma.$ShopOrderPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ShopOrders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShopOrderCountArgs} args - Arguments to filter ShopOrders to count.
   * @example
   * // Count the number of ShopOrders
   * const count = await prisma.shopOrder.count({
   *   where: {
   *     // ... the filter for the ShopOrders we want to count
   *   }
   * })
  **/
  count<T extends ShopOrderCountArgs>(
    args?: Prisma.Subset<T, ShopOrderCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ShopOrderCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ShopOrder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShopOrderAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ShopOrderAggregateArgs>(args: Prisma.Subset<T, ShopOrderAggregateArgs>): Prisma.PrismaPromise<GetShopOrderAggregateType<T>>

  /**
   * Group by ShopOrder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShopOrderGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ShopOrderGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ShopOrderGroupByArgs['orderBy'] }
      : { orderBy?: ShopOrderGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ShopOrderGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetShopOrderGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ShopOrder model
 */
readonly fields: ShopOrderFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ShopOrder.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ShopOrderClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  customer<T extends Prisma.CustomerDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CustomerDefaultArgs<ExtArgs>>): Prisma.Prisma__CustomerClient<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  items<T extends Prisma.ShopOrder$itemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ShopOrder$itemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ShopOrder model
 */
export interface ShopOrderFieldRefs {
  readonly id: Prisma.FieldRef<"ShopOrder", 'String'>
  readonly orderNumber: Prisma.FieldRef<"ShopOrder", 'String'>
  readonly customerId: Prisma.FieldRef<"ShopOrder", 'String'>
  readonly status: Prisma.FieldRef<"ShopOrder", 'String'>
  readonly subtotal: Prisma.FieldRef<"ShopOrder", 'Float'>
  readonly useKrCredits: Prisma.FieldRef<"ShopOrder", 'Boolean'>
  readonly creditsDeducted: Prisma.FieldRef<"ShopOrder", 'Boolean'>
  readonly logoRequested: Prisma.FieldRef<"ShopOrder", 'Boolean'>
  readonly logoUrl: Prisma.FieldRef<"ShopOrder", 'String'>
  readonly shippingName: Prisma.FieldRef<"ShopOrder", 'String'>
  readonly shippingEmail: Prisma.FieldRef<"ShopOrder", 'String'>
  readonly shippingPhone: Prisma.FieldRef<"ShopOrder", 'String'>
  readonly shippingAddress: Prisma.FieldRef<"ShopOrder", 'String'>
  readonly notes: Prisma.FieldRef<"ShopOrder", 'String'>
  readonly createdAt: Prisma.FieldRef<"ShopOrder", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ShopOrder", 'DateTime'>
  readonly completedAt: Prisma.FieldRef<"ShopOrder", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ShopOrder findUnique
 */
export type ShopOrderFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopOrder
   */
  select?: Prisma.ShopOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopOrder
   */
  omit?: Prisma.ShopOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopOrderInclude<ExtArgs> | null
  /**
   * Filter, which ShopOrder to fetch.
   */
  where: Prisma.ShopOrderWhereUniqueInput
}

/**
 * ShopOrder findUniqueOrThrow
 */
export type ShopOrderFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopOrder
   */
  select?: Prisma.ShopOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopOrder
   */
  omit?: Prisma.ShopOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopOrderInclude<ExtArgs> | null
  /**
   * Filter, which ShopOrder to fetch.
   */
  where: Prisma.ShopOrderWhereUniqueInput
}

/**
 * ShopOrder findFirst
 */
export type ShopOrderFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopOrder
   */
  select?: Prisma.ShopOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopOrder
   */
  omit?: Prisma.ShopOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopOrderInclude<ExtArgs> | null
  /**
   * Filter, which ShopOrder to fetch.
   */
  where?: Prisma.ShopOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShopOrders to fetch.
   */
  orderBy?: Prisma.ShopOrderOrderByWithRelationInput | Prisma.ShopOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ShopOrders.
   */
  cursor?: Prisma.ShopOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShopOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShopOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ShopOrders.
   */
  distinct?: Prisma.ShopOrderScalarFieldEnum | Prisma.ShopOrderScalarFieldEnum[]
}

/**
 * ShopOrder findFirstOrThrow
 */
export type ShopOrderFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopOrder
   */
  select?: Prisma.ShopOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopOrder
   */
  omit?: Prisma.ShopOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopOrderInclude<ExtArgs> | null
  /**
   * Filter, which ShopOrder to fetch.
   */
  where?: Prisma.ShopOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShopOrders to fetch.
   */
  orderBy?: Prisma.ShopOrderOrderByWithRelationInput | Prisma.ShopOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ShopOrders.
   */
  cursor?: Prisma.ShopOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShopOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShopOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ShopOrders.
   */
  distinct?: Prisma.ShopOrderScalarFieldEnum | Prisma.ShopOrderScalarFieldEnum[]
}

/**
 * ShopOrder findMany
 */
export type ShopOrderFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopOrder
   */
  select?: Prisma.ShopOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopOrder
   */
  omit?: Prisma.ShopOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopOrderInclude<ExtArgs> | null
  /**
   * Filter, which ShopOrders to fetch.
   */
  where?: Prisma.ShopOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShopOrders to fetch.
   */
  orderBy?: Prisma.ShopOrderOrderByWithRelationInput | Prisma.ShopOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ShopOrders.
   */
  cursor?: Prisma.ShopOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShopOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShopOrders.
   */
  skip?: number
  distinct?: Prisma.ShopOrderScalarFieldEnum | Prisma.ShopOrderScalarFieldEnum[]
}

/**
 * ShopOrder create
 */
export type ShopOrderCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopOrder
   */
  select?: Prisma.ShopOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopOrder
   */
  omit?: Prisma.ShopOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopOrderInclude<ExtArgs> | null
  /**
   * The data needed to create a ShopOrder.
   */
  data: Prisma.XOR<Prisma.ShopOrderCreateInput, Prisma.ShopOrderUncheckedCreateInput>
}

/**
 * ShopOrder createMany
 */
export type ShopOrderCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ShopOrders.
   */
  data: Prisma.ShopOrderCreateManyInput | Prisma.ShopOrderCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ShopOrder createManyAndReturn
 */
export type ShopOrderCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopOrder
   */
  select?: Prisma.ShopOrderSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ShopOrder
   */
  omit?: Prisma.ShopOrderOmit<ExtArgs> | null
  /**
   * The data used to create many ShopOrders.
   */
  data: Prisma.ShopOrderCreateManyInput | Prisma.ShopOrderCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopOrderIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ShopOrder update
 */
export type ShopOrderUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopOrder
   */
  select?: Prisma.ShopOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopOrder
   */
  omit?: Prisma.ShopOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopOrderInclude<ExtArgs> | null
  /**
   * The data needed to update a ShopOrder.
   */
  data: Prisma.XOR<Prisma.ShopOrderUpdateInput, Prisma.ShopOrderUncheckedUpdateInput>
  /**
   * Choose, which ShopOrder to update.
   */
  where: Prisma.ShopOrderWhereUniqueInput
}

/**
 * ShopOrder updateMany
 */
export type ShopOrderUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ShopOrders.
   */
  data: Prisma.XOR<Prisma.ShopOrderUpdateManyMutationInput, Prisma.ShopOrderUncheckedUpdateManyInput>
  /**
   * Filter which ShopOrders to update
   */
  where?: Prisma.ShopOrderWhereInput
  /**
   * Limit how many ShopOrders to update.
   */
  limit?: number
}

/**
 * ShopOrder updateManyAndReturn
 */
export type ShopOrderUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopOrder
   */
  select?: Prisma.ShopOrderSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ShopOrder
   */
  omit?: Prisma.ShopOrderOmit<ExtArgs> | null
  /**
   * The data used to update ShopOrders.
   */
  data: Prisma.XOR<Prisma.ShopOrderUpdateManyMutationInput, Prisma.ShopOrderUncheckedUpdateManyInput>
  /**
   * Filter which ShopOrders to update
   */
  where?: Prisma.ShopOrderWhereInput
  /**
   * Limit how many ShopOrders to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopOrderIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ShopOrder upsert
 */
export type ShopOrderUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopOrder
   */
  select?: Prisma.ShopOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopOrder
   */
  omit?: Prisma.ShopOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopOrderInclude<ExtArgs> | null
  /**
   * The filter to search for the ShopOrder to update in case it exists.
   */
  where: Prisma.ShopOrderWhereUniqueInput
  /**
   * In case the ShopOrder found by the `where` argument doesn't exist, create a new ShopOrder with this data.
   */
  create: Prisma.XOR<Prisma.ShopOrderCreateInput, Prisma.ShopOrderUncheckedCreateInput>
  /**
   * In case the ShopOrder was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ShopOrderUpdateInput, Prisma.ShopOrderUncheckedUpdateInput>
}

/**
 * ShopOrder delete
 */
export type ShopOrderDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopOrder
   */
  select?: Prisma.ShopOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopOrder
   */
  omit?: Prisma.ShopOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopOrderInclude<ExtArgs> | null
  /**
   * Filter which ShopOrder to delete.
   */
  where: Prisma.ShopOrderWhereUniqueInput
}

/**
 * ShopOrder deleteMany
 */
export type ShopOrderDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ShopOrders to delete
   */
  where?: Prisma.ShopOrderWhereInput
  /**
   * Limit how many ShopOrders to delete.
   */
  limit?: number
}

/**
 * ShopOrder.items
 */
export type ShopOrder$itemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderItem
   */
  select?: Prisma.OrderItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderItem
   */
  omit?: Prisma.OrderItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderItemInclude<ExtArgs> | null
  where?: Prisma.OrderItemWhereInput
  orderBy?: Prisma.OrderItemOrderByWithRelationInput | Prisma.OrderItemOrderByWithRelationInput[]
  cursor?: Prisma.OrderItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrderItemScalarFieldEnum | Prisma.OrderItemScalarFieldEnum[]
}

/**
 * ShopOrder without action
 */
export type ShopOrderDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopOrder
   */
  select?: Prisma.ShopOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopOrder
   */
  omit?: Prisma.ShopOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopOrderInclude<ExtArgs> | null
}
