
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `VerifiedCertificate` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model VerifiedCertificate
 * 
 */
export type VerifiedCertificateModel = runtime.Types.Result.DefaultSelection<Prisma.$VerifiedCertificatePayload>

export type AggregateVerifiedCertificate = {
  _count: VerifiedCertificateCountAggregateOutputType | null
  _avg: VerifiedCertificateAvgAggregateOutputType | null
  _sum: VerifiedCertificateSumAggregateOutputType | null
  _min: VerifiedCertificateMinAggregateOutputType | null
  _max: VerifiedCertificateMaxAggregateOutputType | null
}

export type VerifiedCertificateAvgAggregateOutputType = {
  sortOrder: number | null
}

export type VerifiedCertificateSumAggregateOutputType = {
  sortOrder: number | null
}

export type VerifiedCertificateMinAggregateOutputType = {
  id: string | null
  title: string | null
  issuer: string | null
  validUntil: string | null
  type: string | null
  icon: string | null
  pdfUrl: string | null
  sortOrder: number | null
  active: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type VerifiedCertificateMaxAggregateOutputType = {
  id: string | null
  title: string | null
  issuer: string | null
  validUntil: string | null
  type: string | null
  icon: string | null
  pdfUrl: string | null
  sortOrder: number | null
  active: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type VerifiedCertificateCountAggregateOutputType = {
  id: number
  title: number
  issuer: number
  validUntil: number
  type: number
  icon: number
  pdfUrl: number
  sortOrder: number
  active: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type VerifiedCertificateAvgAggregateInputType = {
  sortOrder?: true
}

export type VerifiedCertificateSumAggregateInputType = {
  sortOrder?: true
}

export type VerifiedCertificateMinAggregateInputType = {
  id?: true
  title?: true
  issuer?: true
  validUntil?: true
  type?: true
  icon?: true
  pdfUrl?: true
  sortOrder?: true
  active?: true
  createdAt?: true
  updatedAt?: true
}

export type VerifiedCertificateMaxAggregateInputType = {
  id?: true
  title?: true
  issuer?: true
  validUntil?: true
  type?: true
  icon?: true
  pdfUrl?: true
  sortOrder?: true
  active?: true
  createdAt?: true
  updatedAt?: true
}

export type VerifiedCertificateCountAggregateInputType = {
  id?: true
  title?: true
  issuer?: true
  validUntil?: true
  type?: true
  icon?: true
  pdfUrl?: true
  sortOrder?: true
  active?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type VerifiedCertificateAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VerifiedCertificate to aggregate.
   */
  where?: Prisma.VerifiedCertificateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VerifiedCertificates to fetch.
   */
  orderBy?: Prisma.VerifiedCertificateOrderByWithRelationInput | Prisma.VerifiedCertificateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.VerifiedCertificateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VerifiedCertificates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VerifiedCertificates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned VerifiedCertificates
  **/
  _count?: true | VerifiedCertificateCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: VerifiedCertificateAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: VerifiedCertificateSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VerifiedCertificateMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VerifiedCertificateMaxAggregateInputType
}

export type GetVerifiedCertificateAggregateType<T extends VerifiedCertificateAggregateArgs> = {
      [P in keyof T & keyof AggregateVerifiedCertificate]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVerifiedCertificate[P]>
    : Prisma.GetScalarType<T[P], AggregateVerifiedCertificate[P]>
}




export type VerifiedCertificateGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VerifiedCertificateWhereInput
  orderBy?: Prisma.VerifiedCertificateOrderByWithAggregationInput | Prisma.VerifiedCertificateOrderByWithAggregationInput[]
  by: Prisma.VerifiedCertificateScalarFieldEnum[] | Prisma.VerifiedCertificateScalarFieldEnum
  having?: Prisma.VerifiedCertificateScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VerifiedCertificateCountAggregateInputType | true
  _avg?: VerifiedCertificateAvgAggregateInputType
  _sum?: VerifiedCertificateSumAggregateInputType
  _min?: VerifiedCertificateMinAggregateInputType
  _max?: VerifiedCertificateMaxAggregateInputType
}

export type VerifiedCertificateGroupByOutputType = {
  id: string
  title: string
  issuer: string
  validUntil: string
  type: string
  icon: string
  pdfUrl: string | null
  sortOrder: number
  active: boolean
  createdAt: Date
  updatedAt: Date
  _count: VerifiedCertificateCountAggregateOutputType | null
  _avg: VerifiedCertificateAvgAggregateOutputType | null
  _sum: VerifiedCertificateSumAggregateOutputType | null
  _min: VerifiedCertificateMinAggregateOutputType | null
  _max: VerifiedCertificateMaxAggregateOutputType | null
}

type GetVerifiedCertificateGroupByPayload<T extends VerifiedCertificateGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VerifiedCertificateGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VerifiedCertificateGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VerifiedCertificateGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VerifiedCertificateGroupByOutputType[P]>
      }
    >
  >



export type VerifiedCertificateWhereInput = {
  AND?: Prisma.VerifiedCertificateWhereInput | Prisma.VerifiedCertificateWhereInput[]
  OR?: Prisma.VerifiedCertificateWhereInput[]
  NOT?: Prisma.VerifiedCertificateWhereInput | Prisma.VerifiedCertificateWhereInput[]
  id?: Prisma.StringFilter<"VerifiedCertificate"> | string
  title?: Prisma.StringFilter<"VerifiedCertificate"> | string
  issuer?: Prisma.StringFilter<"VerifiedCertificate"> | string
  validUntil?: Prisma.StringFilter<"VerifiedCertificate"> | string
  type?: Prisma.StringFilter<"VerifiedCertificate"> | string
  icon?: Prisma.StringFilter<"VerifiedCertificate"> | string
  pdfUrl?: Prisma.StringNullableFilter<"VerifiedCertificate"> | string | null
  sortOrder?: Prisma.IntFilter<"VerifiedCertificate"> | number
  active?: Prisma.BoolFilter<"VerifiedCertificate"> | boolean
  createdAt?: Prisma.DateTimeFilter<"VerifiedCertificate"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VerifiedCertificate"> | Date | string
}

export type VerifiedCertificateOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  issuer?: Prisma.SortOrder
  validUntil?: Prisma.SortOrder
  type?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  pdfUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VerifiedCertificateWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.VerifiedCertificateWhereInput | Prisma.VerifiedCertificateWhereInput[]
  OR?: Prisma.VerifiedCertificateWhereInput[]
  NOT?: Prisma.VerifiedCertificateWhereInput | Prisma.VerifiedCertificateWhereInput[]
  title?: Prisma.StringFilter<"VerifiedCertificate"> | string
  issuer?: Prisma.StringFilter<"VerifiedCertificate"> | string
  validUntil?: Prisma.StringFilter<"VerifiedCertificate"> | string
  type?: Prisma.StringFilter<"VerifiedCertificate"> | string
  icon?: Prisma.StringFilter<"VerifiedCertificate"> | string
  pdfUrl?: Prisma.StringNullableFilter<"VerifiedCertificate"> | string | null
  sortOrder?: Prisma.IntFilter<"VerifiedCertificate"> | number
  active?: Prisma.BoolFilter<"VerifiedCertificate"> | boolean
  createdAt?: Prisma.DateTimeFilter<"VerifiedCertificate"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VerifiedCertificate"> | Date | string
}, "id">

export type VerifiedCertificateOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  issuer?: Prisma.SortOrder
  validUntil?: Prisma.SortOrder
  type?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  pdfUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.VerifiedCertificateCountOrderByAggregateInput
  _avg?: Prisma.VerifiedCertificateAvgOrderByAggregateInput
  _max?: Prisma.VerifiedCertificateMaxOrderByAggregateInput
  _min?: Prisma.VerifiedCertificateMinOrderByAggregateInput
  _sum?: Prisma.VerifiedCertificateSumOrderByAggregateInput
}

export type VerifiedCertificateScalarWhereWithAggregatesInput = {
  AND?: Prisma.VerifiedCertificateScalarWhereWithAggregatesInput | Prisma.VerifiedCertificateScalarWhereWithAggregatesInput[]
  OR?: Prisma.VerifiedCertificateScalarWhereWithAggregatesInput[]
  NOT?: Prisma.VerifiedCertificateScalarWhereWithAggregatesInput | Prisma.VerifiedCertificateScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"VerifiedCertificate"> | string
  title?: Prisma.StringWithAggregatesFilter<"VerifiedCertificate"> | string
  issuer?: Prisma.StringWithAggregatesFilter<"VerifiedCertificate"> | string
  validUntil?: Prisma.StringWithAggregatesFilter<"VerifiedCertificate"> | string
  type?: Prisma.StringWithAggregatesFilter<"VerifiedCertificate"> | string
  icon?: Prisma.StringWithAggregatesFilter<"VerifiedCertificate"> | string
  pdfUrl?: Prisma.StringNullableWithAggregatesFilter<"VerifiedCertificate"> | string | null
  sortOrder?: Prisma.IntWithAggregatesFilter<"VerifiedCertificate"> | number
  active?: Prisma.BoolWithAggregatesFilter<"VerifiedCertificate"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"VerifiedCertificate"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"VerifiedCertificate"> | Date | string
}

export type VerifiedCertificateCreateInput = {
  id?: string
  title: string
  issuer: string
  validUntil: string
  type: string
  icon?: string
  pdfUrl?: string | null
  sortOrder?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VerifiedCertificateUncheckedCreateInput = {
  id?: string
  title: string
  issuer: string
  validUntil: string
  type: string
  icon?: string
  pdfUrl?: string | null
  sortOrder?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VerifiedCertificateUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  issuer?: Prisma.StringFieldUpdateOperationsInput | string
  validUntil?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.StringFieldUpdateOperationsInput | string
  pdfUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VerifiedCertificateUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  issuer?: Prisma.StringFieldUpdateOperationsInput | string
  validUntil?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.StringFieldUpdateOperationsInput | string
  pdfUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VerifiedCertificateCreateManyInput = {
  id?: string
  title: string
  issuer: string
  validUntil: string
  type: string
  icon?: string
  pdfUrl?: string | null
  sortOrder?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VerifiedCertificateUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  issuer?: Prisma.StringFieldUpdateOperationsInput | string
  validUntil?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.StringFieldUpdateOperationsInput | string
  pdfUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VerifiedCertificateUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  issuer?: Prisma.StringFieldUpdateOperationsInput | string
  validUntil?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.StringFieldUpdateOperationsInput | string
  pdfUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VerifiedCertificateCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  issuer?: Prisma.SortOrder
  validUntil?: Prisma.SortOrder
  type?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  pdfUrl?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VerifiedCertificateAvgOrderByAggregateInput = {
  sortOrder?: Prisma.SortOrder
}

export type VerifiedCertificateMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  issuer?: Prisma.SortOrder
  validUntil?: Prisma.SortOrder
  type?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  pdfUrl?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VerifiedCertificateMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  issuer?: Prisma.SortOrder
  validUntil?: Prisma.SortOrder
  type?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  pdfUrl?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VerifiedCertificateSumOrderByAggregateInput = {
  sortOrder?: Prisma.SortOrder
}



export type VerifiedCertificateSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  issuer?: boolean
  validUntil?: boolean
  type?: boolean
  icon?: boolean
  pdfUrl?: boolean
  sortOrder?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["verifiedCertificate"]>

export type VerifiedCertificateSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  issuer?: boolean
  validUntil?: boolean
  type?: boolean
  icon?: boolean
  pdfUrl?: boolean
  sortOrder?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["verifiedCertificate"]>

export type VerifiedCertificateSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  issuer?: boolean
  validUntil?: boolean
  type?: boolean
  icon?: boolean
  pdfUrl?: boolean
  sortOrder?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["verifiedCertificate"]>

export type VerifiedCertificateSelectScalar = {
  id?: boolean
  title?: boolean
  issuer?: boolean
  validUntil?: boolean
  type?: boolean
  icon?: boolean
  pdfUrl?: boolean
  sortOrder?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type VerifiedCertificateOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "issuer" | "validUntil" | "type" | "icon" | "pdfUrl" | "sortOrder" | "active" | "createdAt" | "updatedAt", ExtArgs["result"]["verifiedCertificate"]>

export type $VerifiedCertificatePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "VerifiedCertificate"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    issuer: string
    validUntil: string
    type: string
    icon: string
    pdfUrl: string | null
    sortOrder: number
    active: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["verifiedCertificate"]>
  composites: {}
}

export type VerifiedCertificateGetPayload<S extends boolean | null | undefined | VerifiedCertificateDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$VerifiedCertificatePayload, S>

export type VerifiedCertificateCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<VerifiedCertificateFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VerifiedCertificateCountAggregateInputType | true
  }

export interface VerifiedCertificateDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['VerifiedCertificate'], meta: { name: 'VerifiedCertificate' } }
  /**
   * Find zero or one VerifiedCertificate that matches the filter.
   * @param {VerifiedCertificateFindUniqueArgs} args - Arguments to find a VerifiedCertificate
   * @example
   * // Get one VerifiedCertificate
   * const verifiedCertificate = await prisma.verifiedCertificate.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VerifiedCertificateFindUniqueArgs>(args: Prisma.SelectSubset<T, VerifiedCertificateFindUniqueArgs<ExtArgs>>): Prisma.Prisma__VerifiedCertificateClient<runtime.Types.Result.GetResult<Prisma.$VerifiedCertificatePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one VerifiedCertificate that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VerifiedCertificateFindUniqueOrThrowArgs} args - Arguments to find a VerifiedCertificate
   * @example
   * // Get one VerifiedCertificate
   * const verifiedCertificate = await prisma.verifiedCertificate.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VerifiedCertificateFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, VerifiedCertificateFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__VerifiedCertificateClient<runtime.Types.Result.GetResult<Prisma.$VerifiedCertificatePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VerifiedCertificate that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VerifiedCertificateFindFirstArgs} args - Arguments to find a VerifiedCertificate
   * @example
   * // Get one VerifiedCertificate
   * const verifiedCertificate = await prisma.verifiedCertificate.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VerifiedCertificateFindFirstArgs>(args?: Prisma.SelectSubset<T, VerifiedCertificateFindFirstArgs<ExtArgs>>): Prisma.Prisma__VerifiedCertificateClient<runtime.Types.Result.GetResult<Prisma.$VerifiedCertificatePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VerifiedCertificate that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VerifiedCertificateFindFirstOrThrowArgs} args - Arguments to find a VerifiedCertificate
   * @example
   * // Get one VerifiedCertificate
   * const verifiedCertificate = await prisma.verifiedCertificate.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VerifiedCertificateFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, VerifiedCertificateFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__VerifiedCertificateClient<runtime.Types.Result.GetResult<Prisma.$VerifiedCertificatePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more VerifiedCertificates that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VerifiedCertificateFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all VerifiedCertificates
   * const verifiedCertificates = await prisma.verifiedCertificate.findMany()
   * 
   * // Get first 10 VerifiedCertificates
   * const verifiedCertificates = await prisma.verifiedCertificate.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const verifiedCertificateWithIdOnly = await prisma.verifiedCertificate.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends VerifiedCertificateFindManyArgs>(args?: Prisma.SelectSubset<T, VerifiedCertificateFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VerifiedCertificatePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a VerifiedCertificate.
   * @param {VerifiedCertificateCreateArgs} args - Arguments to create a VerifiedCertificate.
   * @example
   * // Create one VerifiedCertificate
   * const VerifiedCertificate = await prisma.verifiedCertificate.create({
   *   data: {
   *     // ... data to create a VerifiedCertificate
   *   }
   * })
   * 
   */
  create<T extends VerifiedCertificateCreateArgs>(args: Prisma.SelectSubset<T, VerifiedCertificateCreateArgs<ExtArgs>>): Prisma.Prisma__VerifiedCertificateClient<runtime.Types.Result.GetResult<Prisma.$VerifiedCertificatePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many VerifiedCertificates.
   * @param {VerifiedCertificateCreateManyArgs} args - Arguments to create many VerifiedCertificates.
   * @example
   * // Create many VerifiedCertificates
   * const verifiedCertificate = await prisma.verifiedCertificate.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends VerifiedCertificateCreateManyArgs>(args?: Prisma.SelectSubset<T, VerifiedCertificateCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many VerifiedCertificates and returns the data saved in the database.
   * @param {VerifiedCertificateCreateManyAndReturnArgs} args - Arguments to create many VerifiedCertificates.
   * @example
   * // Create many VerifiedCertificates
   * const verifiedCertificate = await prisma.verifiedCertificate.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many VerifiedCertificates and only return the `id`
   * const verifiedCertificateWithIdOnly = await prisma.verifiedCertificate.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends VerifiedCertificateCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, VerifiedCertificateCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VerifiedCertificatePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a VerifiedCertificate.
   * @param {VerifiedCertificateDeleteArgs} args - Arguments to delete one VerifiedCertificate.
   * @example
   * // Delete one VerifiedCertificate
   * const VerifiedCertificate = await prisma.verifiedCertificate.delete({
   *   where: {
   *     // ... filter to delete one VerifiedCertificate
   *   }
   * })
   * 
   */
  delete<T extends VerifiedCertificateDeleteArgs>(args: Prisma.SelectSubset<T, VerifiedCertificateDeleteArgs<ExtArgs>>): Prisma.Prisma__VerifiedCertificateClient<runtime.Types.Result.GetResult<Prisma.$VerifiedCertificatePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one VerifiedCertificate.
   * @param {VerifiedCertificateUpdateArgs} args - Arguments to update one VerifiedCertificate.
   * @example
   * // Update one VerifiedCertificate
   * const verifiedCertificate = await prisma.verifiedCertificate.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends VerifiedCertificateUpdateArgs>(args: Prisma.SelectSubset<T, VerifiedCertificateUpdateArgs<ExtArgs>>): Prisma.Prisma__VerifiedCertificateClient<runtime.Types.Result.GetResult<Prisma.$VerifiedCertificatePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more VerifiedCertificates.
   * @param {VerifiedCertificateDeleteManyArgs} args - Arguments to filter VerifiedCertificates to delete.
   * @example
   * // Delete a few VerifiedCertificates
   * const { count } = await prisma.verifiedCertificate.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends VerifiedCertificateDeleteManyArgs>(args?: Prisma.SelectSubset<T, VerifiedCertificateDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VerifiedCertificates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VerifiedCertificateUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many VerifiedCertificates
   * const verifiedCertificate = await prisma.verifiedCertificate.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends VerifiedCertificateUpdateManyArgs>(args: Prisma.SelectSubset<T, VerifiedCertificateUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VerifiedCertificates and returns the data updated in the database.
   * @param {VerifiedCertificateUpdateManyAndReturnArgs} args - Arguments to update many VerifiedCertificates.
   * @example
   * // Update many VerifiedCertificates
   * const verifiedCertificate = await prisma.verifiedCertificate.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more VerifiedCertificates and only return the `id`
   * const verifiedCertificateWithIdOnly = await prisma.verifiedCertificate.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends VerifiedCertificateUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, VerifiedCertificateUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VerifiedCertificatePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one VerifiedCertificate.
   * @param {VerifiedCertificateUpsertArgs} args - Arguments to update or create a VerifiedCertificate.
   * @example
   * // Update or create a VerifiedCertificate
   * const verifiedCertificate = await prisma.verifiedCertificate.upsert({
   *   create: {
   *     // ... data to create a VerifiedCertificate
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the VerifiedCertificate we want to update
   *   }
   * })
   */
  upsert<T extends VerifiedCertificateUpsertArgs>(args: Prisma.SelectSubset<T, VerifiedCertificateUpsertArgs<ExtArgs>>): Prisma.Prisma__VerifiedCertificateClient<runtime.Types.Result.GetResult<Prisma.$VerifiedCertificatePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of VerifiedCertificates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VerifiedCertificateCountArgs} args - Arguments to filter VerifiedCertificates to count.
   * @example
   * // Count the number of VerifiedCertificates
   * const count = await prisma.verifiedCertificate.count({
   *   where: {
   *     // ... the filter for the VerifiedCertificates we want to count
   *   }
   * })
  **/
  count<T extends VerifiedCertificateCountArgs>(
    args?: Prisma.Subset<T, VerifiedCertificateCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VerifiedCertificateCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a VerifiedCertificate.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VerifiedCertificateAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VerifiedCertificateAggregateArgs>(args: Prisma.Subset<T, VerifiedCertificateAggregateArgs>): Prisma.PrismaPromise<GetVerifiedCertificateAggregateType<T>>

  /**
   * Group by VerifiedCertificate.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VerifiedCertificateGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends VerifiedCertificateGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VerifiedCertificateGroupByArgs['orderBy'] }
      : { orderBy?: VerifiedCertificateGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, VerifiedCertificateGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVerifiedCertificateGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the VerifiedCertificate model
 */
readonly fields: VerifiedCertificateFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for VerifiedCertificate.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VerifiedCertificateClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the VerifiedCertificate model
 */
export interface VerifiedCertificateFieldRefs {
  readonly id: Prisma.FieldRef<"VerifiedCertificate", 'String'>
  readonly title: Prisma.FieldRef<"VerifiedCertificate", 'String'>
  readonly issuer: Prisma.FieldRef<"VerifiedCertificate", 'String'>
  readonly validUntil: Prisma.FieldRef<"VerifiedCertificate", 'String'>
  readonly type: Prisma.FieldRef<"VerifiedCertificate", 'String'>
  readonly icon: Prisma.FieldRef<"VerifiedCertificate", 'String'>
  readonly pdfUrl: Prisma.FieldRef<"VerifiedCertificate", 'String'>
  readonly sortOrder: Prisma.FieldRef<"VerifiedCertificate", 'Int'>
  readonly active: Prisma.FieldRef<"VerifiedCertificate", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"VerifiedCertificate", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"VerifiedCertificate", 'DateTime'>
}
    

// Custom InputTypes
/**
 * VerifiedCertificate findUnique
 */
export type VerifiedCertificateFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VerifiedCertificate
   */
  select?: Prisma.VerifiedCertificateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VerifiedCertificate
   */
  omit?: Prisma.VerifiedCertificateOmit<ExtArgs> | null
  /**
   * Filter, which VerifiedCertificate to fetch.
   */
  where: Prisma.VerifiedCertificateWhereUniqueInput
}

/**
 * VerifiedCertificate findUniqueOrThrow
 */
export type VerifiedCertificateFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VerifiedCertificate
   */
  select?: Prisma.VerifiedCertificateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VerifiedCertificate
   */
  omit?: Prisma.VerifiedCertificateOmit<ExtArgs> | null
  /**
   * Filter, which VerifiedCertificate to fetch.
   */
  where: Prisma.VerifiedCertificateWhereUniqueInput
}

/**
 * VerifiedCertificate findFirst
 */
export type VerifiedCertificateFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VerifiedCertificate
   */
  select?: Prisma.VerifiedCertificateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VerifiedCertificate
   */
  omit?: Prisma.VerifiedCertificateOmit<ExtArgs> | null
  /**
   * Filter, which VerifiedCertificate to fetch.
   */
  where?: Prisma.VerifiedCertificateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VerifiedCertificates to fetch.
   */
  orderBy?: Prisma.VerifiedCertificateOrderByWithRelationInput | Prisma.VerifiedCertificateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VerifiedCertificates.
   */
  cursor?: Prisma.VerifiedCertificateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VerifiedCertificates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VerifiedCertificates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VerifiedCertificates.
   */
  distinct?: Prisma.VerifiedCertificateScalarFieldEnum | Prisma.VerifiedCertificateScalarFieldEnum[]
}

/**
 * VerifiedCertificate findFirstOrThrow
 */
export type VerifiedCertificateFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VerifiedCertificate
   */
  select?: Prisma.VerifiedCertificateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VerifiedCertificate
   */
  omit?: Prisma.VerifiedCertificateOmit<ExtArgs> | null
  /**
   * Filter, which VerifiedCertificate to fetch.
   */
  where?: Prisma.VerifiedCertificateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VerifiedCertificates to fetch.
   */
  orderBy?: Prisma.VerifiedCertificateOrderByWithRelationInput | Prisma.VerifiedCertificateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VerifiedCertificates.
   */
  cursor?: Prisma.VerifiedCertificateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VerifiedCertificates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VerifiedCertificates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VerifiedCertificates.
   */
  distinct?: Prisma.VerifiedCertificateScalarFieldEnum | Prisma.VerifiedCertificateScalarFieldEnum[]
}

/**
 * VerifiedCertificate findMany
 */
export type VerifiedCertificateFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VerifiedCertificate
   */
  select?: Prisma.VerifiedCertificateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VerifiedCertificate
   */
  omit?: Prisma.VerifiedCertificateOmit<ExtArgs> | null
  /**
   * Filter, which VerifiedCertificates to fetch.
   */
  where?: Prisma.VerifiedCertificateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VerifiedCertificates to fetch.
   */
  orderBy?: Prisma.VerifiedCertificateOrderByWithRelationInput | Prisma.VerifiedCertificateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing VerifiedCertificates.
   */
  cursor?: Prisma.VerifiedCertificateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VerifiedCertificates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VerifiedCertificates.
   */
  skip?: number
  distinct?: Prisma.VerifiedCertificateScalarFieldEnum | Prisma.VerifiedCertificateScalarFieldEnum[]
}

/**
 * VerifiedCertificate create
 */
export type VerifiedCertificateCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VerifiedCertificate
   */
  select?: Prisma.VerifiedCertificateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VerifiedCertificate
   */
  omit?: Prisma.VerifiedCertificateOmit<ExtArgs> | null
  /**
   * The data needed to create a VerifiedCertificate.
   */
  data: Prisma.XOR<Prisma.VerifiedCertificateCreateInput, Prisma.VerifiedCertificateUncheckedCreateInput>
}

/**
 * VerifiedCertificate createMany
 */
export type VerifiedCertificateCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many VerifiedCertificates.
   */
  data: Prisma.VerifiedCertificateCreateManyInput | Prisma.VerifiedCertificateCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * VerifiedCertificate createManyAndReturn
 */
export type VerifiedCertificateCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VerifiedCertificate
   */
  select?: Prisma.VerifiedCertificateSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VerifiedCertificate
   */
  omit?: Prisma.VerifiedCertificateOmit<ExtArgs> | null
  /**
   * The data used to create many VerifiedCertificates.
   */
  data: Prisma.VerifiedCertificateCreateManyInput | Prisma.VerifiedCertificateCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * VerifiedCertificate update
 */
export type VerifiedCertificateUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VerifiedCertificate
   */
  select?: Prisma.VerifiedCertificateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VerifiedCertificate
   */
  omit?: Prisma.VerifiedCertificateOmit<ExtArgs> | null
  /**
   * The data needed to update a VerifiedCertificate.
   */
  data: Prisma.XOR<Prisma.VerifiedCertificateUpdateInput, Prisma.VerifiedCertificateUncheckedUpdateInput>
  /**
   * Choose, which VerifiedCertificate to update.
   */
  where: Prisma.VerifiedCertificateWhereUniqueInput
}

/**
 * VerifiedCertificate updateMany
 */
export type VerifiedCertificateUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update VerifiedCertificates.
   */
  data: Prisma.XOR<Prisma.VerifiedCertificateUpdateManyMutationInput, Prisma.VerifiedCertificateUncheckedUpdateManyInput>
  /**
   * Filter which VerifiedCertificates to update
   */
  where?: Prisma.VerifiedCertificateWhereInput
  /**
   * Limit how many VerifiedCertificates to update.
   */
  limit?: number
}

/**
 * VerifiedCertificate updateManyAndReturn
 */
export type VerifiedCertificateUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VerifiedCertificate
   */
  select?: Prisma.VerifiedCertificateSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VerifiedCertificate
   */
  omit?: Prisma.VerifiedCertificateOmit<ExtArgs> | null
  /**
   * The data used to update VerifiedCertificates.
   */
  data: Prisma.XOR<Prisma.VerifiedCertificateUpdateManyMutationInput, Prisma.VerifiedCertificateUncheckedUpdateManyInput>
  /**
   * Filter which VerifiedCertificates to update
   */
  where?: Prisma.VerifiedCertificateWhereInput
  /**
   * Limit how many VerifiedCertificates to update.
   */
  limit?: number
}

/**
 * VerifiedCertificate upsert
 */
export type VerifiedCertificateUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VerifiedCertificate
   */
  select?: Prisma.VerifiedCertificateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VerifiedCertificate
   */
  omit?: Prisma.VerifiedCertificateOmit<ExtArgs> | null
  /**
   * The filter to search for the VerifiedCertificate to update in case it exists.
   */
  where: Prisma.VerifiedCertificateWhereUniqueInput
  /**
   * In case the VerifiedCertificate found by the `where` argument doesn't exist, create a new VerifiedCertificate with this data.
   */
  create: Prisma.XOR<Prisma.VerifiedCertificateCreateInput, Prisma.VerifiedCertificateUncheckedCreateInput>
  /**
   * In case the VerifiedCertificate was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VerifiedCertificateUpdateInput, Prisma.VerifiedCertificateUncheckedUpdateInput>
}

/**
 * VerifiedCertificate delete
 */
export type VerifiedCertificateDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VerifiedCertificate
   */
  select?: Prisma.VerifiedCertificateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VerifiedCertificate
   */
  omit?: Prisma.VerifiedCertificateOmit<ExtArgs> | null
  /**
   * Filter which VerifiedCertificate to delete.
   */
  where: Prisma.VerifiedCertificateWhereUniqueInput
}

/**
 * VerifiedCertificate deleteMany
 */
export type VerifiedCertificateDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VerifiedCertificates to delete
   */
  where?: Prisma.VerifiedCertificateWhereInput
  /**
   * Limit how many VerifiedCertificates to delete.
   */
  limit?: number
}

/**
 * VerifiedCertificate without action
 */
export type VerifiedCertificateDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VerifiedCertificate
   */
  select?: Prisma.VerifiedCertificateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VerifiedCertificate
   */
  omit?: Prisma.VerifiedCertificateOmit<ExtArgs> | null
}
