/**
 * LSU Name + Technician pairs from Client Master sheet
 * (/Users/.../Sheets/CLient Master.xlsx — LSU Name / LSU Technician Name).
 * Himachal casing duplicates collapsed to "Himachal Pradesh".
 */
export const LSU_TEAMS_FROM_SHEETS: { lsuName: string; technicianName: string }[] = [
  { lsuName: "Agra", technicianName: "Deepak Rajauriya" },
  { lsuName: "Ahmedabad", technicianName: "Shubham Kurli" },
  { lsuName: "Almora", technicianName: "Pawan Singh Bisht" },
  { lsuName: "Amritsar", technicianName: "Abhishek Kumar Amritsar" },
  { lsuName: "Aurangabad", technicianName: "Nadeem" },
  { lsuName: "Bekal", technicianName: "Sathyanarayana H V" },
  { lsuName: "Bengaluru", technicianName: "Ravikumar" },
  { lsuName: "Bhopal", technicianName: "Rudra Prakash Aouchat" },
  { lsuName: "Bhubaneshwar", technicianName: "Sunil kumar Sahoo" },
  { lsuName: "Chandigarh", technicianName: "Rishavjeet Singh" },
  { lsuName: "Chennai", technicianName: "Senthil Kumar" },
  { lsuName: "Chittorgarh", technicianName: "Lokesh Prajapat" },
  { lsuName: "Darjeeling", technicianName: "Manthan Rai" },
  { lsuName: "Dehradun", technicianName: "Mohammad Maroof" },
  { lsuName: "Delhi NCR", technicianName: "Ashok Kumar Delhi" },
  { lsuName: "Ernakulam", technicianName: "Nizamuddin P" },
  { lsuName: "Goa", technicianName: "Akshay Jadhav" },
  { lsuName: "Gorakhpur", technicianName: "Suraj Kumar" },
  { lsuName: "Guwahati", technicianName: "Akhlak Rahman" },
  { lsuName: "Himachal Pradesh", technicianName: "Abhishek Kumar HP" },
  { lsuName: "Hyderabad", technicianName: "Mohd Jeelani Khan" },
  { lsuName: "Jaipur", technicianName: "Somendra Nagaji" },
  { lsuName: "Jaisalmer", technicianName: "Vishal Parasmal Sanckelcha" },
  { lsuName: "Jhanjheli/Manali", technicianName: "Sonu Mandyal" },
  { lsuName: "Jodhpur", technicianName: "Amit Kumar" },
  { lsuName: "Junagadh", technicianName: "Sondrava Prins Sanjaybhai" },
  { lsuName: "Kanha", technicianName: "Akash Yadav" },
  { lsuName: "Karnal", technicianName: "Ashok Kumar Karnal" },
  { lsuName: "Kolkata", technicianName: "Amresh Mishra" },
  { lsuName: "Kovalam", technicianName: "Abhinand KR" },
  { lsuName: "Lucknow", technicianName: "Manoj Kumar Verma" },
  { lsuName: "Madhurai", technicianName: "Mohammed Ali" },
  { lsuName: "Madikeri", technicianName: "Anantkumar" },
  { lsuName: "Mumbai", technicianName: "Imtiyaz Ahmed Shaikh" },
  { lsuName: "Mysuru", technicianName: "Yashwantha Raju TS" },
  { lsuName: "Nagpur", technicianName: "Shubham Bhimraj Fulzele" },
  { lsuName: "Nashik", technicianName: "Sagar Arun Vise" },
  { lsuName: "Netrang", technicianName: "Ram Krishana" },
  { lsuName: "Ooty", technicianName: "M Ajith" },
  { lsuName: "Pavagadh", technicianName: "Dhamesh" },
  { lsuName: "Pune", technicianName: "Sammeed Patil" },
  { lsuName: "Ranchi", technicianName: "Kalyan Beck" },
  { lsuName: "Sambhalpur", technicianName: "Ajay Kumar Babu" },
  { lsuName: "Shimla", technicianName: "Ashok Kumar Shimla" },
  { lsuName: "Srinagar", technicianName: "Unassigned" },
  { lsuName: "Surat/Bharuch", technicianName: "Shantilal Maganbhai Prajapati" },
  { lsuName: "Tirupati", technicianName: "R Shaktivel" },
  { lsuName: "Udaipur & Kumbhalgarh", technicianName: "Hafiz Khan" },
  { lsuName: "Vadodara", technicianName: "Shubham Kurli" },
  { lsuName: "Vapi", technicianName: "Manoj Kumar Viswakarma" },
  { lsuName: "Varanasi", technicianName: "Deepak Kumar Varanasi" },
  { lsuName: "Vizinagaram", technicianName: "Potnur Goutham" },
]
