/**
 * Partner logos from BuffIndia_React source - /supporters/partner-logo/
 */
export const SUPPORTER_PARTNERS = [
  { name: "Adani", logo: "/supporters/partner-logo/adani.png" },
  { name: "Wells Fargo", logo: "/supporters/partner-logo/wells.png" },
  { name: "GMR", logo: "/supporters/partner-logo/10-2.png" },
  { name: "Hyatt", logo: "/supporters/partner-logo/hyatt.png" },
  { name: "ITC Fortune Hotels", logo: "/supporters/partner-logo/fortune.png" },
  { name: "Royal Orchid Hotels", logo: "/supporters/partner-logo/royal-orchid.png" },
  { name: "Advani Hotels & Resorts", logo: "/supporters/partner-logo/advani.png" },
  { name: "Club Mahindra", logo: "/supporters/partner-logo/club-mahindra.png" },
  { name: "Taj Hotels", logo: "/supporters/partner-logo/taj.png" },
  { name: "Marriott", logo: "/supporters/partner-logo/marriott.png" },
  { name: "Chalet Hotels", logo: "/supporters/partner-logo/chalet-hotel.png" },
  { name: "Mahindra", logo: "/supporters/partner-logo/mahindra.png" },
  { name: "Caravela Beach Resort", logo: "/supporters/partner-logo/caravela.png" },
  { name: "WelcomHotel", logo: "/supporters/partner-logo/welcomhotel.png" },
  { name: "Radisson", logo: "/supporters/partner-logo/radisson.png" },
  { name: "La Ri Sa Hotels & Resorts", logo: "/supporters/partner-logo/la-ri-sa.png" },
  { name: "ARAIYA", logo: "/supporters/partner-logo/araiya.png" },
  { name: "Le Meridien", logo: "/supporters/partner-logo/meridien.png" },
  { name: "Accor", logo: "/supporters/partner-logo/accor.png" },
  { name: "Sterling", logo: "/supporters/partner-logo/sterling.png" },
  { name: "Embassy", logo: "/supporters/partner-logo/embassy.png" },
  { name: "Westin Hotels & Resorts", logo: "/supporters/partner-logo/westin.png" },
  { name: "Fairfield by Marriott Goa", logo: "/supporters/partner-logo/fairfield.png" },
  { name: "Conrad Hotels & Resorts", logo: "/supporters/partner-logo/conrad.png" },
  { name: "Crowne Plaza", logo: "/supporters/partner-logo/crowne.png" },
  { name: "Planet Hollywood", logo: "/supporters/partner-logo/planet-hollywood.png" },
  { name: "Holiday Inn", logo: "/supporters/partner-logo/holiday-inn.png" },
  { name: "Ibis Hotels", logo: "/supporters/partner-logo/ibis.png" },
  { name: "Happy Shack", logo: "/supporters/partner-logo/happy-snack.png" },
  { name: "Accenture", logo: "/supporters/partner-logo/accenture.png" },
  { name: "Hycinth", logo: "/supporters/partner-logo/hycinth.png" },
  { name: "The Lalit", logo: "/supporters/partner-logo/beatle.png" },
  { name: "LambdaTest", logo: "/supporters/partner-logo/lambdatest.png" },
  { name: "Carelon Global Solutions", logo: "/supporters/partner-logo/carelon.png" },
  { name: "Sarovar Portico", logo: "/supporters/partner-logo/sarovar.png" },
  { name: "Ginger Hotels", logo: "/supporters/partner-logo/ginger.png" },
  { name: "KEC International", logo: "/supporters/partner-logo/kec.png" },
  { name: "Prestige Group", logo: "/supporters/partner-logo/prestige-group.png" },
  { name: "Aloft Hotels", logo: "/supporters/partner-logo/aloft.png" },
  { name: "ExpoInn", logo: "/supporters/partner-logo/expol-inn.png" },
  { name: "Caravela Beach Resort Varca Goa", logo: "/supporters/partner-logo/caravela-resort.png" },
  { name: "Boulevard 9", logo: "/supporters/partner-logo/boulward.png" },
  { name: "Novotel", logo: "/supporters/partner-logo/novotel.png" },
  { name: "Collabera Digital", logo: "/supporters/partner-logo/collabera.png" },
  { name: "Howard Johnson", logo: "/supporters/partner-logo/howard.png" },
  { name: "Hilton Shillim", logo: "/supporters/partner-logo/hilton.png" },
  { name: "President", logo: "/supporters/partner-logo/president.png" },
  { name: "Taj Falaknuma Palace", logo: "/supporters/partner-logo/taj-palace.png" },
  { name: "The Dukes Retreat Khandala", logo: "/supporters/partner-logo/the-duke.png" },
  { name: "Umaid Bhawan Palace", logo: "/supporters/partner-logo/umaid.png" },
  { name: "DLF", logo: "/supporters/partner-logo/dlf.png" },
  { name: "Hyatt Centric Candolim Goa", logo: "/supporters/partner-logo/hyatt-centric.png" },
  { name: "Bagmane", logo: "/supporters/partner-logo/bagmane.png" },
  { name: "Vesta Hotels & Resorts", logo: "/supporters/partner-logo/vesta.png" },
  { name: "The Resort", logo: "/supporters/partner-logo/resort.png" },
  { name: "Conrad Bengaluru", logo: "/supporters/partner-logo/conrad-signatur.png" },
  { name: "DoubleTree by Hilton", logo: "/supporters/partner-logo/double-tree.png" },
  { name: "WeWork", logo: "/supporters/partner-logo/wework.png" },
  { name: "Baba Au Rhum", logo: "/supporters/partner-logo/baba.png" },
  { name: "New Goa International Airport", logo: "/supporters/partner-logo/new-love.png" },
  { name: "Amazon Development Centre India", logo: "/supporters/partner-logo/amazon.png" },
  { name: "Grand Mercure Bangalore", logo: "/supporters/partner-logo/grand-bangalore.png" },
  { name: "Futura Tech Park", logo: "/supporters/partner-logo/futura.png" },
  { name: "Ascot Hospitality", logo: "/supporters/partner-logo/ascot.png" },
  { name: "Adani Ahmedabad Airport", logo: "/supporters/partner-logo/adani-ahm.png" },
  { name: "Renaissance Ahmedabad Hotel", logo: "/supporters/partner-logo/renaissance.png" },
  { name: "Schindler", logo: "/supporters/partner-logo/schindler.png" },
  { name: "Kempegowda International Airport", logo: "/supporters/partner-logo/kempegowda.png" },
  { name: "Hyatt Place Gurgaon", logo: "/supporters/partner-logo/hyatt-place.png" },
  { name: "Holiday Inn Express", logo: "/supporters/partner-logo/holidayinn.png" },
  { name: "Radisson Hotels & Resorts", logo: "/supporters/partner-logo/radisson-resort.png" },
  { name: "McCain", logo: "/supporters/partner-logo/macain.png" },
  { name: "Fiserv", logo: "/supporters/partner-logo/fiserv.png" },
  { name: "The Leela", logo: "/supporters/partner-logo/the-leela.png" },
  { name: "Amoravida by Topple Resorts", logo: "/supporters/partner-logo/amoravida.png" },
  { name: "Park Hyatt Chennai", logo: "/supporters/partner-logo/park-hyatt.png" },
  { name: "Hyatt Regency Chennai", logo: "/supporters/partner-logo/hyatt-regency.png" },
  { name: "Housing.com", logo: "/supporters/partner-logo/housing.png" },
  { name: "Associated Power Structure", logo: "/supporters/partner-logo/21-2.png" },
  { name: "Goldman Sachs", logo: "/supporters/partner-logo/goldman.png" },
  { name: "CBRE", logo: "/supporters/partner-logo/cbre.png" },
  { name: "Brigade Group", logo: "/supporters/partner-logo/brigade.png" },
  { name: "LYFE Hotels", logo: "/supporters/partner-logo/lyfe.png" },
  { name: "RaajKutir", logo: "/supporters/partner-logo/raajkutir.png" },
  { name: "Grape County", logo: "/supporters/partner-logo/grape.png" },
  { name: "Anand Rathi", logo: "/supporters/partner-logo/anandrathi.png" },
  { name: "GEP", logo: "/supporters/partner-logo/gep.png" },
  { name: "Lake Palace", logo: "/supporters/partner-logo/lake-palace.png" },
  { name: "Born to Ride Gujarat", logo: "/supporters/partner-logo/gaar.png" },
  { name: "The Fern Residency", logo: "/supporters/partner-logo/the-fern.png" },
  { name: "IHCL", logo: "/supporters/partner-logo/ihcl.png" },
  { name: "ITC Hotels", logo: "/supporters/partner-logo/itc-hotel.png" },
  { name: "Grand Hotels", logo: "/supporters/partner-logo/grand.png" },
  { name: "Denali", logo: "/supporters/partner-logo/denali.png" },
  { name: "Savoy Suites", logo: "/supporters/partner-logo/savoy-suites.png" },
  { name: "IndiQube", logo: "/supporters/partner-logo/indioube.png" },
  { name: "Vivanta", logo: "/supporters/partner-logo/vivanta.png" },
  { name: "Andaz", logo: "/supporters/partner-logo/andaz.png" },
]
