import { type NextRequest, NextResponse } from "next/server"
import { prisma } from "@/lib/prisma"
import { ensureMonthlyReportForPeriod, getCurrentMonthKey } from "@/lib/monthly-reports"
import { resolveCustomerScope } from "@/lib/customer-api-auth"

function formatReport(row: {
  id: string
  name: string
  date: Date
  type: string | null
  period: string | null
  description: string | null
  driveFileUrl: string | null
  size: string | null
  generatedBy: string | null
}) {
  return {
    id: row.id,
    name: row.name,
    date: row.date.toISOString(),
    type: row.type || "monthly",
    period: row.period,
    description: row.description,
    driveFileUrl: row.driveFileUrl,
    size: row.size,
    generatedBy: row.generatedBy,
  }
}

export async function GET(request: NextRequest) {
  try {
    const locationId = request.nextUrl.searchParams.get("locationId")
    const auth = await resolveCustomerScope(
      request.nextUrl.searchParams.get("customerId"),
      locationId,
    )
    if (!auth.ok) return auth.response

    // Only ensure current month exists — full history is generated by admin / on demand
    const monthKey = getCurrentMonthKey()
    await Promise.all(auth.customerIds.map((cid) => ensureMonthlyReportForPeriod(cid, monthKey)))

    const reports = await prisma.report.findMany({
      where: { customerId: { in: auth.customerIds } },
      orderBy: { date: "desc" },
    })

    const customerMap = new Map<string, string>()
    if (auth.customerIds.length > 1) {
      const customers = await prisma.customer.findMany({
        where: { id: { in: auth.customerIds } },
        select: { id: true, companyName: true },
      })
      for (const c of customers) customerMap.set(c.id, c.companyName)
    }

    return NextResponse.json({
      success: true,
      reports: reports.map((r) => ({
        ...formatReport(r),
        locationName: customerMap.get(r.customerId),
      })),
    })
  } catch (error) {
    console.error("Error fetching reports:", error)
    return NextResponse.json({ success: false, error: "Server error" }, { status: 500 })
  }
}
