"use client"

import { Reveal, RevealGroup, RevealItem } from "@/components/landing/reveal"

const metrics = [
  {
    num: "01",
    value: "3,000",
    unit: "filters / kg",
    title: "Cigarette butts",
    body: "Waste is weighed at the collection point and again at local storage, then translated into an estimated filter count.",
    accent: true,
  },
  {
    num: "02",
    value: "82–94%",
    unit: "",
    title: "Toxic waste upcycled",
    body: "The source framework estimates the toxic filter fraction as a share of total collected waste.",
  },
  {
    num: "03",
    value: "100 L",
    unit: "per filter",
    title: "Water protected",
    body: "Reporting uses a conservative assumption of 100 litres protected for every filter prevented from littering.",
  },
  {
    num: "04",
    value: "Reach",
    unit: "× awareness",
    title: "Awareness created",
    body: "Behavioural reach combines observed users with estimated word-of-mouth awareness generated by kiosks and service use.",
    dark: true,
  },
]

export function LandingImpact() {
  return (
    <section id="impact" className="scroll-mt-24 border-t border-[var(--l-line)] py-20 sm:py-28">
      <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
        <Reveal>
          <p className="landing-section-label mb-6">04 / Impact, made visible</p>
          <h2 className="landing-display max-w-3xl text-[clamp(2.25rem,5vw,3.75rem)] leading-[1.1] tracking-tight">
            Not just collected. <em className="italic text-[var(--l-green)]">Counted.</em>
          </h2>
          <p className="mt-6 max-w-2xl text-[16px] leading-relaxed text-[var(--l-muted)]">
            BuffIndia’s monthly reporting framework connects operational data with environmental and
            behavioural indicators.
          </p>
        </Reveal>

        <RevealGroup className="mt-14 grid gap-5 sm:grid-cols-2">
          {metrics.map((m) => (
            <RevealItem key={m.num}>
              <article
                className={`h-full border p-6 transition-transform duration-300 hover:-translate-y-1 sm:p-7 ${
                  m.dark
                    ? "border-[var(--l-ink)] bg-[var(--l-ink)] text-[#F7F6F2]"
                    : m.accent
                      ? "border-[var(--l-green)]/30 bg-[#E8F5E9]/50"
                      : "border-[var(--l-line)] bg-white/60"
                }`}
              >
                <p
                  className={`text-[11px] font-semibold tracking-[0.16em] ${
                    m.dark ? "text-[var(--l-orange)]" : "text-[var(--l-orange)]"
                  }`}
                >
                  {m.num}
                </p>
                <p className="landing-display mt-3 text-4xl tracking-tight">
                  {m.value}
                  {m.unit ? (
                    <span
                      className={`ml-2 text-lg not-italic ${m.dark ? "text-white/55" : "text-[var(--l-muted)]"}`}
                    >
                      {m.unit}
                    </span>
                  ) : null}
                </p>
                <h3 className="mt-3 text-[15px] font-semibold">{m.title}</h3>
                <p
                  className={`mt-2 text-[14px] leading-relaxed ${m.dark ? "text-white/60" : "text-[var(--l-muted)]"}`}
                >
                  {m.body}
                </p>
              </article>
            </RevealItem>
          ))}
        </RevealGroup>

        <Reveal delay={0.15}>
          <p className="mt-10 max-w-3xl border-l-2 border-[var(--l-line)] pl-4 text-[13px] leading-relaxed text-[var(--l-muted)]">
            Methodology note: figures and assumptions above are retained from the supplied BuffIndia
            write-up. They should be validated and date-stamped before external publication.
          </p>
        </Reveal>
      </div>
    </section>
  )
}
